force-app/main/default/objects/Campaign/fields/Banner_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Banner_Received_Date__c</fullName>
    <label>Banner Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Business_Card_Holder_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Card_Holder_Received_Date__c</fullName>
    <label>Business Card Holder Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Collateral_Holder_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Collateral_Holder_Received_Date__c</fullName>
    <label>Collateral Holder Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/iPad_Stand_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>iPad_Stand_Received_Date__c</fullName>
    <label>iPad Stand Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Primary_BD__c.field-meta.xml
<CustomField>
    <fullName>Primary_BD__c</fullName>
    <label>BD Primary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Tablecloth_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Tablecloth_Received_Date__c</fullName>
    <label>Tablecloth Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/X10_Days_Date_Received_Reminder__c.field-meta.xml
<CustomField>
    <fullName>X10_Days_Date_Received_Reminder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>10 Days Date Received Reminder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/X10X10_Booth_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>X10X10_Booth_Received_Date__c</fullName>
    <label>10X10 Booth Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/X20_Days_Date_Received_Reminder__c.field-meta.xml
<CustomField>
    <fullName>X20_Days_Date_Received_Reminder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>20 Days Date Received Reminder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>All Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/classes/TestMaterialsRecDateReminderTrg.cls
@isTest
public class TestMaterialsRecDateReminderTrg {
        
     Static testMethod void MaterialsRecDateReminderTrgTest(){
        Test.StartTest();
        Boolean blankFlag = true ;
        Boolean sendEmail = true ;
        Id campRecTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Conference').getRecordTypeId();
        Campaign c = new Campaign();
        c.Name = 'Testing';
        c.RecordTypeId = campRecTypeId ;
        c.Primary_BD__c = 'Buena Cloud Development';
        c.X10_Days_Date_Received_Reminder__c = false;
        c.X20_Days_Date_Received_Reminder__c = false;
        insert c;
               
        c.X10_Days_Date_Received_Reminder__c = true;
        c.X20_Days_Date_Received_Reminder__c = true;
        update c; 
        
        Campaign c1 = new Campaign();
        c1.Name = 'Testing';
        c1.Primary_BD__c = 'Buena Cloud Development' ;        
        c1.X20_Days_Date_Received_Reminder__c = true ;
        c1.X10X10_Booth_Received_Date__c = null ;
        c1.Banner_Received_Date__c = null ;
        c1.Business_Card_Holder_Received_Date__c = null ;
        c1.Collateral_Holder_Received_Date__c = null ;
        c1.iPad_Stand_Received_Date__c = null ;
        c1.Tablecloth_Received_Date__c = null ;        
        insert c1;
                                      
        Test.StopTest();  
    }
}