force-app/main/default/objects/Campaign/fields/BDAttending__c.field-meta.xml
<CustomField>
    <fullName>BDAttending__c</fullName>
    <description>Other Bussinss Development Reps attending the conference</description>
    <label>BD Attending</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Brittany Baker</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>Christian James</fullName>
            </value>
            <value>
                <fullName>Christopher Head</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Den Chou</fullName>
            </value>
            <value>
                <fullName>Farida Bahadoor</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kimberly Gavrilles</fullName>
            </value>
            <value>
                <fullName>Krystal Windley</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <description>Person will be presenting at the conference, training or workshop</description>
    <label>Presenting</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Betsy Mayotte</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Fidel Calero</fullName>
            </value>
            <value>
                <fullName>Gina Lucente-Cole</fullName>
            </value>
            <value>
                <fullName>Jacqueline Carroll</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>Joanne Dashiell</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Jonathan Sparling</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kevin Fudge</fullName>
            </value>
            <value>
                <fullName>Lorinda Diehl</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Paul Combe</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Susan Nathan</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Primary_BD__c.field-meta.xml
<CustomField>
    <fullName>Primary_BD__c</fullName>
    <label>BD Primary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>All Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/objects/Campaign_ASA_Attendees__c/Campaign_ASA_Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee Feedback</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/ASA_Attendee__c.field-meta.xml
<CustomField>
    <fullName>ASA_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASA Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Attendee Feedback</relationshipLabel>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestBatchCreateCampaignAttendee.cls
/**
@Name            : TestBatchCreateCampaignAttendee
@Author          : Monika CONAM
@Date            : Jan 2 2017
@Description     : Test class for 'BatchCreateCampaignAttendee' Batch Class 
**/
@isTest

private class TestBatchCreateCampaignAttendee
{
    static testmethod void BatchCreateCampaignAttendee() {
        Test.startTest();
        
            RecordType camprt = [SELECT Id,Name FROM RecordType WHERE SobjectType='Campaign' AND Name='Conference']; 
            Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
            User u = new User(Alias = 'standt', Email='standarduser@test.com', 
                     EmailEncodingKey='UTF-8',Firstname='Attendee', Lastname='Testing', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, 
                     TimeZoneSidKey='America/Los_Angeles', UserName='testusr22@test.com');
            insert u;         
            User u1 = new User(Alias = 'standt2', Email='standarduser123@test1.com', 
                     EmailEncodingKey='UTF-8',Firstname='Attendee', Lastname='Test', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, 
                     TimeZoneSidKey='America/Los_Angeles', UserName='usrtst111@testorg1.com');         
            insert u1;   
            
            System.runAs(u){    
                Campaign camp =new Campaign(Name='Camp1',Status='Completed',RecordTypeId=camprt.id,StartDate=system.today(),EndDate=system.today().addDays(2),BDAttending__c='Attendee Testing',Primary_BD__c='Attendee Testing',Presenting__c='Attendee Testing');
                insert camp;  
                
                Campaign camp2 =new Campaign(Name='Camp2',Status='Completed',RecordTypeId=camprt.id,StartDate=system.today(),EndDate=system.today().addDays(3),BDAttending__c='Attendee Testing;Attendee Test',Primary_BD__c='Attendee Testing',Presenting__c='Attendee Testing;Attendee Test');
                insert camp2;
                
                Campaign camp3 =new Campaign(Name='Camp3',Status='Completed',RecordTypeId=camprt.id,StartDate=system.today(),EndDate=system.today().addDays(3),BDAttending__c='Attendee Testing;Attendee Test',Primary_BD__c='Attendee Test',Presenting__c='Attendee Testing;Attendee Test');
                insert camp3;
                
                Campaign_ASA_Attendees__c campASA = new Campaign_ASA_Attendees__c(Campaign__c=camp3.id,ASA_Attendee__c=u.id);
                insert campASA; 
                    
                BatchCreateCampaignAttendee  objTest = new BatchCreateCampaignAttendee();
                Database.executebatch(objTest);
            }
        
        Test.stopTest();
    }
}