force-app/main/default/objects/Campaign/fields/BDAttending__c.field-meta.xml
<CustomField>
    <fullName>BDAttending__c</fullName>
    <description>Other Bussinss Development Reps attending the conference</description>
    <label>BD Attending</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Brittany Baker</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>Christian James</fullName>
            </value>
            <value>
                <fullName>Christopher Head</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Den Chou</fullName>
            </value>
            <value>
                <fullName>Farida Bahadoor</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kimberly Gavrilles</fullName>
            </value>
            <value>
                <fullName>Krystal Windley</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/CPS_Center_Affiliation_Intake_Location__c.field-meta.xml
<CustomField>
    <fullName>CPS_Center_Affiliation_Intake_Location__c</fullName>
    <inlineHelpText>If a new Contact is created from the auto-check-in process (as may be the case for TS), this field is mapped to the Contact Intake Location.</inlineHelpText>
    <label>CPS Center Affiliation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOC Boston</fullName>
            </value>
            <value>
                <fullName>EOC Brockton</fullName>
            </value>
            <value>
                <fullName>TS Boston</fullName>
            </value>
            <value>
                <fullName>TS Brockton</fullName>
            </value>
            <value>
                <fullName>UB Brockton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>What City State is the conference being help in</description>
    <label>Location</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <description>Person will be presenting at the conference, training or workshop</description>
    <label>Presenting</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Betsy Mayotte</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Fidel Calero</fullName>
            </value>
            <value>
                <fullName>Gina Lucente-Cole</fullName>
            </value>
            <value>
                <fullName>Jacqueline Carroll</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>Joanne Dashiell</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Jonathan Sparling</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kevin Fudge</fullName>
            </value>
            <value>
                <fullName>Lorinda Diehl</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Paul Combe</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Susan Nathan</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>All Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/objects/Contact/fields/BirthDate_Text__c.field-meta.xml
<CustomField>
    <fullName>BirthDate_Text__c</fullName>
    <label>BirthDate Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventCheckInFormControllerTest.cls
/**
@Name            : EventCheckInFormControllerTest
@Author          : Ashutosh
@Date            : July 5 2018
@Description     : Test class for 'EventCheckInFormController' Class 
**/
@isTest

private class EventCheckInFormControllerTest
{
    static testmethod void TestEventCheckInFormController() {
        Test.startTest();
        
        RecordType camprt = [SELECT Id,Name FROM RecordType WHERE SobjectType='contact' AND Name='CPS - EOC']; 
        RecordType camprt2 = [SELECT Id,Name FROM RecordType WHERE SobjectType='contact' AND Name='CPS - TS']; 
         
        Account accNew = new Account();     
        accNew.name='College Planning Services '+system.today().year();        
        insert accNew;
    
        Contact conNew = new Contact(LastName = 'Test Con1',FirstName ='test First',BirthDate_Text__c= 'date.today()-2220',AccountId = accNew.Id, Title = 'Test',recordTypeId =camprt.Id);
        insert conNew;
        
        Contact conRecord = [SELECT Id,LastName FROM Contact WHERE Id =: conNew.Id];
        System.assertEquals('Test Con1',conRecord.LastName); 
        
        RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='Campaign' AND Name='Conference'];
        
        Campaign camp = new Campaign(Name='Campaign1',RecordTypeId= rt.id,Location__c='Test loc',CPS_Center_Affiliation_Intake_Location__c = 'EOC Boston',StartDate=System.today(),EndDate=System.today()+5,BDAttending__c='Testing;Testingnew',Presenting__c='Testingnew',isActive=true);             
        insert camp;
        
        Campaign campRecord = [SELECT Id,Name FROM Campaign WHERE Id =: camp.Id];
        System.assertEquals('Campaign1',campRecord.Name);
        
        
        Cookie cookie = new Cookie('campId', camp.id, null, -1, false);
        ApexPages.currentPage().setCookies(new Cookie[]{cookie});
        
        EventCheckInFormController aCtrl=new EventCheckInFormController ();
        
        aCtrl.firstName = 'test First';
        aCtrl.lastName= 'Test Con2';
        aCtrl.studentId = '456852';
        aCtrl.birthDate = Date.newInstance(2016, 12, 9);
        aCtrl.email = 'test@gmail.com';
        aCtrl.mobilePhone = '9999999999';
        //aCtrl.CPS_Center_Affiliation_Intake_Location__c = 'EOC Boston';
        aCtrl.createRecords();
        aCtrl.createContact();
        aCtrl.okPopUp();
        aCtrl.cancelPopUp();
        aCtrl.createCampaignMember(conNew.Id);
        
        PageReference pageRef = Page.EventCheckIn;
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }
    
    static testmethod void TestEventCheckInFormController2() {
        Test.startTest();
        
            RecordType camprt = [SELECT Id,Name FROM RecordType WHERE SobjectType='contact' AND Name='CPS - EOC']; 
            RecordType camprt2 = [SELECT Id,Name FROM RecordType WHERE SobjectType='contact' AND Name='CPS - TS']; 
            system.debug('=========camprt2'+camprt2);
             
            Account accNew = new Account();     
            accNew.name='College Planning Services '+system.today().year();       
            insert accNew;
        
            
            Contact conNew2 = new Contact(LastName = 'Test Con11',FirstName ='test First1',BirthDate_Text__c= 'date.today()-2220',AccountId = accNew.Id, Title = 'Test',recordTypeId =camprt2.Id);
            insert conNew2;
            
            Contact conRecord2 = [SELECT Id,LastName FROM Contact WHERE Id =: conNew2.Id];
            System.assertEquals('Test Con11',conRecord2.LastName);  
            
            
            RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='Campaign' AND Name='Conference'];
            
            Campaign camp = new Campaign(Name='Campaign1',RecordTypeId= rt.id,Location__c='Test loc',CPS_Center_Affiliation_Intake_Location__c = 'TS Boston',StartDate=System.today(),EndDate=System.today()+5,BDAttending__c='Testing;Testingnew',Presenting__c='Testingnew',isActive=true);             
            insert camp;
            
            Campaign campRecord2 = [SELECT Id,Name FROM Campaign WHERE Id =: camp.Id];
            System.assertEquals('Campaign1',campRecord2.Name);
            
            
            Cookie cookie = new Cookie('campId', camp.id, null, -1, false);
            ApexPages.currentPage().setCookies(new Cookie[]{cookie});
            
            //ApexPages.CurrentPage().getCookies().put('campId',new Cookie(cookie));
            EventCheckInFormController aCtrl=new EventCheckInFormController ();
            
            aCtrl.redirectToHome();
            //aCtrl.createCampaignMember();
             aCtrl.firstName = 'test First2111';
            aCtrl.lastName= 'test last name 001';
            aCtrl.studentId = '456852';
            aCtrl.birthDate = Date.newInstance(2016, 12, 9);
            aCtrl.email = 'test@gmail.com';
            aCtrl.mobilePhone = '9999999999';
            aCtrl.createRecords();
            //aCtrl.createContact();
            aCtrl.okPopUp();
            aCtrl.cancelPopUp();
            aCtrl.createCampaignMember(conNew2.Id);
            
            PageReference pageRef = Page.EventCheckIn;
            //pageRef.getParameters().put('campId', aCtrl.campId);
            Test.setCurrentPage(pageRef);
            
            
            Test.stopTest();
    }
}