force-app/main/default/objects/Campaign/fields/BDAttending__c.field-meta.xml
<CustomField>
    <fullName>BDAttending__c</fullName>
    <description>Other Bussinss Development Reps attending the conference</description>
    <label>BD Attending</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Brittany Baker</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>Christian James</fullName>
            </value>
            <value>
                <fullName>Christopher Head</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Den Chou</fullName>
            </value>
            <value>
                <fullName>Farida Bahadoor</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kimberly Gavrilles</fullName>
            </value>
            <value>
                <fullName>Krystal Windley</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <description>Person will be presenting at the conference, training or workshop</description>
    <label>Presenting</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Betsy Mayotte</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Fidel Calero</fullName>
            </value>
            <value>
                <fullName>Gina Lucente-Cole</fullName>
            </value>
            <value>
                <fullName>Jacqueline Carroll</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>Joanne Dashiell</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Jonathan Sparling</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kevin Fudge</fullName>
            </value>
            <value>
                <fullName>Lorinda Diehl</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Paul Combe</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Susan Nathan</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Primary_BD__c.field-meta.xml
<CustomField>
    <fullName>Primary_BD__c</fullName>
    <label>BD Primary</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>All Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/objects/Campaign_ASA_Attendees__c/Campaign_ASA_Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee Feedback</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/ASA_Attendee__c.field-meta.xml
<CustomField>
    <fullName>ASA_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASA Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Attendee Feedback</relationshipLabel>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BatchCreateCampaignAttendee.cls
/*
@Name                : BatchCreateCampaignAttendee
@Author              : Monika Conam
@Date                : Dec 28, 2016
@Description         : Batch class to Create AttendeeFeeback object for Campaign Object .
*/
global class BatchCreateCampaignAttendee implements Database.Batchable<sObject> { 
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'Select Id,Name,Primary_BD__c,BDAttending__c,Presenting__c,(Select Id,ASA_Attendee__r.Name from Campaign_Email_Surveys__r) from Campaign where Enddate > today and Recordtype.Name=\'Conference\' and (Primary_BD__c!= null OR BDAttending__c!= null OR Presenting__c!= null)';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Campaign> campList){       
        try{ 
            List<Campaign_ASA_Attendees__c> newAttendee = new List<Campaign_ASA_Attendees__c>();
            Set<String> attendiesshouldexist = new Set<String>();
            Set<String> existingattendies = new Set<String>(); 
            
            for(Campaign c: campList){
                if(c.Primary_BD__c!=null ){
                    attendiesshouldexist.add(c.Primary_BD__c);
                }
                if(c.BDAttending__c!=null ){
                    if(c.BDAttending__c.contains(';')){
                        List<String> BDAttending = c.BDAttending__c.split(';');
                        for(String s : BDAttending){
                           attendiesshouldexist.add(s);
                        }
                    } 
                    else{
                        attendiesshouldexist.add(c.BDAttending__c); 
                    }
                }
                if(c.Presenting__c!=null){
                    if(c.Presenting__c.contains(';')){
                        List<String> Presenting= c.Presenting__c.split(';');
                        for(String s : Presenting){
                           attendiesshouldexist.add(s);
                        }
                    } 
                    else{
                        attendiesshouldexist.add(c.Presenting__c);
                    }
                } 
            }
            
            Map<String,Id> userIdMap = new Map<String,Id>();
            List<User> usrList = [Select Id,Name From User Where Name In : attendiesshouldexist];
            for(User usrTemp : usrList){
                userIdMap.put(usrTemp.Name,usrTemp.Id);   
            }
                      
            for(Campaign c: campList){ 
                attendiesshouldexist = new Set<String>();
                existingattendies = new Set<String>();    
                if(c.Primary_BD__c!=null ){
                    attendiesshouldexist.add(c.Primary_BD__c);
                }
                if(c.BDAttending__c!=null ){
                    if(c.BDAttending__c.contains(';')){
                        List<String> BDAttending = c.BDAttending__c.split(';');
                        for(String s : BDAttending){
                           attendiesshouldexist.add(s);
                        }
                    } 
                    else{
                        attendiesshouldexist.add(c.BDAttending__c); 
                    }
                }
                if(c.Presenting__c!=null){
                    if(c.Presenting__c.contains(';')){
                        List<String> Presenting= c.Presenting__c.split(';');
                        for(String s : Presenting){
                           attendiesshouldexist.add(s);
                        }
                    } 
                    else{
                        attendiesshouldexist.add(c.Presenting__c);
                    }
                }   
                for(Campaign_ASA_Attendees__c Camp1 : c.Campaign_Email_Surveys__r){
                    existingattendies.add(Camp1.ASA_Attendee__r.Name);
                }
                for(String str1 : attendiesshouldexist){
                    Boolean exist = false;
                    for(String str2 : existingattendies){
                        if(str2 == str1){
                            exist = true;    
                        }
                    }
                    if(!exist){
                        Campaign_ASA_Attendees__c campAttendee = new Campaign_ASA_Attendees__c();
                        campAttendee.Campaign__c = c.id;
                        if(userIdMap.containsKey(str1)){
                            campAttendee.ASA_Attendee__c = userIdMap.get(str1); 
                        }
                        if(campAttendee.ASA_Attendee__c != null){       
                            newAttendee.add(campAttendee); 
                        }  
                    }
                } 
            }
            if(newAttendee.size()>0){
                insert newAttendee;
            }
        }  
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - '  + e.getLineNumber());
        }
    }           
    
    global void finish(Database.BatchableContext BC){
    }
}