force-app/main/default/objects/Campaign/fields/CPS_Center_Affiliation_Intake_Location__c.field-meta.xml
<CustomField>
    <fullName>CPS_Center_Affiliation_Intake_Location__c</fullName>
    <inlineHelpText>If a new Contact is created from the auto-check-in process (as may be the case for TS), this field is mapped to the Contact Intake Location.</inlineHelpText>
    <label>CPS Center Affiliation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOC Boston</fullName>
            </value>
            <value>
                <fullName>EOC Brockton</fullName>
            </value>
            <value>
                <fullName>TS Boston</fullName>
            </value>
            <value>
                <fullName>TS Brockton</fullName>
            </value>
            <value>
                <fullName>UB Brockton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Check_In_Notes__c.field-meta.xml
<CustomField>
    <fullName>Check_In_Notes__c</fullName>
    <inlineHelpText>This corresponds to the field on the CPS Event check-in form where the Client is asked to note any recent updates to their Contact information.  The Advisor will later review these notes and make any Contact record updates, as needed.</inlineHelpText>
    <label>Check In Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Contact_Created_From_Event_Check_In__c.field-meta.xml
<CustomField>
    <fullName>Contact_Created_From_Event_Check_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact Created From Event Check In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Auto_Created_Source__c.field-meta.xml
<CustomField>
    <fullName>Auto_Created_Source__c</fullName>
    <inlineHelpText>If this field has a value, it means the Contact record was created as part of an automated process (&quot;CPS Event Check In&quot;, or &quot;CPS Sign On&quot;)</inlineHelpText>
    <label>Auto-Created Source</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/BirthDate_Text__c.field-meta.xml
<CustomField>
    <fullName>BirthDate_Text__c</fullName>
    <label>BirthDate Text</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Date__c.field-meta.xml
<CustomField>
    <fullName>Intake_Date__c</fullName>
    <inlineHelpText>For EOC/TS, this is the date the Client fills out the Intake form (set one-time for TS, and updated yearly for EOC).  For UB, this is the date of first service.</inlineHelpText>
    <label>Intake Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Form_Expire_Date_EOC__c.field-meta.xml
<CustomField>
    <fullName>Intake_Form_Expire_Date_EOC__c</fullName>
    <formula>IF(ISBLANK(Intake_Date__c),Date(1900,1,1),
IF (AND(OR(ISPICKVAL(Intake_Location__c, &#39;EOC Boston&#39;),ISPICKVAL(Intake_Location__c, &#39;EOC Brockton&#39;)), MONTH( Intake_Date__c) &lt;= 8),
Date(YEAR(Intake_Date__c), 8,31),
IF (OR(ISPICKVAL(Intake_Location__c, &#39;EOC Boston&#39;),ISPICKVAL(Intake_Location__c, &#39;EOC Brockton&#39;)), 
(Date(YEAR(Intake_Date__c) + 1,8,31)),Date(1900,1,1)
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Intake Form Expire Date EOC</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Location__c.field-meta.xml
<CustomField>
    <fullName>Intake_Location__c</fullName>
    <label>Intake Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPS_Intake_location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MobilePhoneNumeric__c.field-meta.xml
<CustomField>
    <fullName>MobilePhoneNumeric__c</fullName>
    <description>This field is used by the CPS matching logic in sign-on advising and group event check-in. It is needed so that a mobile phone number match can be made on the numbers alone, without any formatting.</description>
    <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(MobilePhone,&quot;(&quot;,&quot;&quot;),&quot;)&quot;,&quot;&quot;),&quot;-&quot;,&quot;&quot;),&quot;+&quot;,&quot;&quot;),&quot; &quot;,&quot;&quot;),&quot;,&quot;,&quot;&quot;)</formula>
    <label>MobilePhoneNumeric</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <label>Student ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event i.e. In person campus meeting, online meeting, conference meeting or substantive call</description>
    <label>Event</label>
</RecordType>

force-app/main/default/classes/EventCheckInFormControllerMobile.cls
public class EventCheckInFormControllerMobile{
    //Event CheckIn Form Variables
    public String firstName{get; set;}
    public String lastName{get; set;}
    public String studentId{get; set;}
    public Date birthDate{get; set;}
    public String email{get; set;}
    public String mobilePhone{get; set;}
    public String checkInNotes{get; set;}
    public String campaignName{get;set;}
    public String zipCode{get; set;}
    
    //Backend Variables
    String location;
    String campaignId;
    Id idRecordTypeEOCContact;
    Id idRecordTypeTSContact;
    Id idRecordTypeUBContact; //Added on 23 Oct 2018, by Ajay************** 
    Id accountId;
    List<Campaign> lstCampaign;
    Date currentDate;
    public boolean renderPgMsgBox{get;set;} //To render pagemessage box on the page
    public boolean renderStudentId{get;set;} //To render Student ID field the page
    public boolean showPopup{get;set;} //Render popup or main page
        
    List<CampaignMemberStatus> lstCMStatus = new List<CampaignMemberStatus>(); //Added on 22 Oct 2018, by Ajay************** 
    Set<String> setCMRespondedStatus = new Set<String>(); //Added on 22 Oct 2018, by Ajay**************
    
    public eventCheckinFormControllerMobile(){
        try{
            renderPgMsgBox = false; //set page message visibility
        
            //Set showPopup
            showPopup = false;
            
            //Set current date
            currentDate = System.today();
                        
            //Get campaign id
            if(apexpages.currentPage().getCookies() != null && apexpages.currentPage().getCookies().containsKey('campId')){
                campaignId = apexpages.currentPage().getCookies().get('campId').getValue();
                System.debug('campaignId>>>>>>>'+campaignId);
            }
            
            //Get record type ids
            idRecordTypeEOCContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CPS - EOC').getRecordTypeId();
            idRecordTypeTSContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CPS - TS').getRecordTypeId();
            idRecordTypeUBContact = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('CPS - UB').getRecordTypeId();
            
            
            //Get valid Account
            String accountName = 'College Planning Services '+system.today().year();
            
            system.debug('======accountName '+accountName);
            for(Account objAcc : [select Id from Account where Name =: accountName limit 1]){
                accountId = objAcc.id;
            }
            
            //Get Campaign info
            lstCampaign = [select id,Name,CPS_Center_Affiliation_Intake_Location__c,ownerid 
                           from Campaign 
                           where id =: campaignId limit 1];
            
            //Added on 22 Oct 2018, by Ajay**************
            //Get responded status for the campaign
            for(CampaignMemberStatus objCampMemberStatus : [select id,Label
                                                            from CampaignMemberStatus 
                                                            where CampaignId =: campaignId and HasResponded = true]){
                lstCMStatus.add(objCampMemberStatus);
                setCMRespondedStatus.add(objCampMemberStatus.Label);
            }
            //************************************************
            
            //Get location name               
            if(lstCampaign != null && lstCampaign.size()>0){
                System.debug('lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c>>>>>'+lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c);
                location = String.isNotBlank(lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c)?lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c:null;
                campaignName = lstCampaign[0].Name;
            }
            System.debug('locagtion>>>>>>>>>>'+location);
            renderStudentId = (location.containsIgnoreCase('TS') || location.containsIgnoreCase('UB'))?true:false;
        }
        catch(Exception ex){
            renderPgMsgBox = true;
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Something went wrong! please contact your administrator!'));
        }
    }
    
    
    //Method to redirect to input location page
    public PageReference redirectToHome(){
        if(String.isBlank(campaignId)){
            System.debug('>>>>inside redirectToHome');
            PageReference homePage = new PageReference('/apex/Mobile_Phone_Demo1');
            homePage.setRedirect(true);
            return homePage;
        }
        return null;
    }
    
    
    
    public pageReference createRecords(){
        try{
            String mobilePhoneNumeric;
            //remove leading and ending space
            firstName = firstName.trim();
            lastName = lastName.trim();
            email = string.isNotBlank(email)?email.trim():null;
            
            //remove alpha and special characters from mobilePhone
            if(String.isNotBlank(mobilePhone)){
                mobilePhone = mobilePhone.trim();
                Pattern numberOnly = Pattern.compile('[a-zA-Z,(,),\\-,,[,], ]');
                Matcher matcher = numberOnly.matcher(mobilePhone);
                mobilePhoneNumeric = matcher.replaceAll('');
                system.debug('mobilePhoneNumeric>>>>>'+mobilePhoneNumeric);
            }
            
            String query;
            Set<String> setCPSRecordTypeName = new Set<String>{'CPS - EOC','CPS - TS','CPS - UB'};
            query = 'select id,name,Intake_Date__c,Intake_Form_Expire_Date_EOC__c,accountid,(select id,Status from CampaignMembers where campaignId =: campaignId) from contact where RecordType.Name in : setCPSRecordTypeName AND';
            
            //If studentId not null
            if(studentId != null && studentId != ''){
                query += ' ((LastName =: lastName AND Student_ID__c =: studentId) OR';
            }
            
            System.debug('birthDate>>>>>'+birthDate);
            String strBirthDate = String.valueOf(birthDate).trim() + ' 00:00:00';
            System.debug('strBirthDate>>>>>>>>>>'+strBirthDate);
            query += ' (LastName =: lastName AND BirthDate_Text__c =: strBirthDate AND (FirstName =: firstName';
            
            //If mobilePhone not blank
            query = String.isNotBlank(mobilePhoneNumeric)?query+' OR MobilePhoneNumeric__c =: mobilePhoneNumeric':query;
            
            //If mobilePhone not email
            query = email != null?query+' OR email =: email':query;
            
            query += '))';
            
            if(String.isNotBlank(location) && (location.containsIgnoreCase('TS') || location.containsIgnoreCase('UB')) && studentId != null && studentId != ''){
                query += ')';
            }
            
            query += ' order by lastModifiedDate desc limit 1';
            
            System.debug('lastName>>>>>'+lastName);
            System.debug('mobilePhone>>>>>'+mobilePhone);
            System.debug('strBirthDate>>>>>'+strBirthDate);
            System.debug('firstName>>>>>'+firstName);
            
            if(
                query != null 
                && String.isNotBlank(location) 
                && (location.containsIgnoreCase('EOC') || location.containsIgnoreCase('TS') || location.containsIgnoreCase('UB'))
            ){
                System.debug('query>>>>>>'+query);
                
                List<Contact> lstMatchedContact = Database.query(query);
                system.debug('=======lstMatchedContact'+lstMatchedContact);
                CampaignMember objCampMemToUpdate = new CampaignMember(); //Added on 22 Oct 2018, by Aj*********
                
                if(lstMatchedContact != null && lstMatchedContact.size()>0){
                    System.debug('lstMatchedContact@@@@@'+lstMatchedContact[0].Id);
                    
                    //To check if already linked
                    if(lstMatchedContact[0].CampaignMembers.size()>0){
                        //Added on 22 Oct 2018, by Aj*********
                        if(setCMRespondedStatus.contains(lstMatchedContact[0].CampaignMembers[0].Status)){
                            showPopup = true;
                            return null;
                        }
                        else{
                            objCampMemToUpdate.Id = lstMatchedContact[0].CampaignMembers[0].id;
                            objCampMemToUpdate.Status = lstCMStatus[0].Label;
                            update objCampMemToUpdate;
                        }
                        //************************************
                    }
                    else{
                        //To create campaign member
                        createCampaignMember(lstMatchedContact[0].id);
                    }
                }
                else{
                    Contact objContact = createContact();
                    createCampaignMember(objContact.id);
                }
                //Redirect to confirmation page
                PageReference confirmationPage = new PageReference('/apex/EventCheckInConfirmation');
                confirmationPage.setRedirect(true);
                return confirmationPage;
            }   
            return null;
        }
        catch(Exception ex){
            system.debug('ex.getMessage()>>>>>>'+ex.getMessage());
            renderPgMsgBox = true;
            String message = 'Something went wrong! please contact your administrator!';
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,message));
            return null;
        }
    }
    
    public PageReference okPopUp(){
        showPopup = false;
        return null;
    }
    
    public PageReference cancelPopUp(){
        //Redirect to confirmation page
        PageReference confirmationPage = new PageReference('/apex/EventCheckInConfirmation');
        confirmationPage.setRedirect(true);
        return confirmationPage;
    }
    
    //Method to insert CampaignMember
    public void createCampaignMember(Id contactId){
        System.debug('checkInNotes>>>>>'+checkInNotes);
        
        CampaignMember objCM =  new CampaignMember();
        objCM.CampaignId = campaignId;
        objCM.Contactid = contactId;
        if(lstCMStatus != null && lstCMStatus.size()>0){
            objCM.Status = lstCMStatus[0].Label;
        }
        if(String.isNotBlank(checkInNotes)){
            objCM.Check_In_Notes__c = checkInNotes;
        }
        objCM.Contact_Created_From_Event_Check_In__c = true; //Modified on 22 Oct 2018, by Aj***********
        insert objCM;
    }
    
    //Method to create contact
    public Contact createContact(){
        Contact objContact = new Contact();
        
        objContact.LastName = lastName;
        if(String.isNotBlank(firstName)){
            objContact.FirstName = firstName;
        }
        if(String.isNotBlank(zipCode)){
            objContact.MailingPostalCode = zipCode;
        }
        if(birthDate != null){
            objContact.BirthDate = Date.valueOf(birthDate);
            System.debug('objContact.BirthDate>>>>>>>'+objContact.BirthDate);
        }
        if(String.isNotBlank(email)){
            objContact.Email = email;
        }
        if(String.isNotBlank(mobilePhone)){
            objContact.MobilePhone = mobilePhone;
        }
        if(String.isNotBlank(location)){
            if(location.containsIgnoreCase('EOC')){
                objContact.recordTypeId = idRecordTypeEOCContact;
            }
            else if(location.containsIgnoreCase('TS')){
                objContact.recordTypeId = idRecordTypeTSContact;
            }
            else if(location.containsIgnoreCase('UB')){
                objContact.recordTypeId = idRecordTypeUBContact;
            }
        }
        if(accountId != null){
            objContact.AccountId = accountId;
        }
        objContact.Auto_Created_Source__c = 'CPS Event Check In';
        if(lstCampaign != null && lstCampaign.size()>0){
            if(lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c != null){
                objContact.Intake_Location__c = lstCampaign[0].CPS_Center_Affiliation_Intake_Location__c;
            }
            objContact.OwnerId = lstCampaign[0].ownerId;
        }
        if(String.isNotBlank(studentId)){
            objContact.Student_ID__c = studentId;
        }
        System.debug('objContact.LastName>>>'+objContact.LastName);
        insert objContact;
        return objContact;
    }
}