force-app/main/default/objects/Campaign/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Email Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <description>Person will be presenting at the conference, training or workshop</description>
    <label>Presenting</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Betsy Mayotte</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Fidel Calero</fullName>
            </value>
            <value>
                <fullName>Gina Lucente-Cole</fullName>
            </value>
            <value>
                <fullName>Jacqueline Carroll</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>Joanne Dashiell</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Jonathan Sparling</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kevin Fudge</fullName>
            </value>
            <value>
                <fullName>Lorinda Diehl</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Paul Combe</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Susan Nathan</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/Campaign_ASA_Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee Feedback</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/ASA_Attendee__c.field-meta.xml
<CustomField>
    <fullName>ASA_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASA Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Attendee Feedback</relationshipLabel>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/Pro_Services_Offering__c.object-meta.xml
<CustomObject>
    <customHelp>PSOfferings_CustomHelp</customHelp>
    <description>Individual offerings that will be conducted by the Financial Education Services team.</description>
    <label>Pro Services Offering</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pro Services Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingAssignedTo__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingAssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who has been assigned to this event?</description>
    <inlineHelpText>This is the ProServices@ASA team member who has been assigned to conduct this Offering.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_OfferingAssignedTo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingCampaign__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingCampaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What campaign is this event related to?</description>
    <inlineHelpText>If this Offering is related to a specific Campaign, please use this lookup field to select the appropriate Campaign.</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>PS_OfferingCampaign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingCity__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingCity__c</fullName>
    <description>What is the city where this event will be held?</description>
    <label>City</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingRequestedBy__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingRequestedBy__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Please identify the ASA team member who is requesting this event.</description>
    <inlineHelpText>Please identify the ASA team member who is requesting this event.</inlineHelpText>
    <label>Requested By (ASA)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PS_OfferingRequestedBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingState__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingState__c</fullName>
    <description>What is the 2-digit state code for the location where this offering will be held?</description>
    <inlineHelpText>Please enter the 2 character state abbreviation for this Offering. This is primarily used for reporting by the ProServices@ASA team.</inlineHelpText>
    <label>State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingStatus__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingStatus__c</fullName>
    <description>What is the current status of this offering request?</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
                <default>true</default>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingTargetDate__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingTargetDate__c</fullName>
    <description>What is the target date for this offering?</description>
    <inlineHelpText>This field contains the date requested for this Offering. This date may change depending on intervening factors and the availability of resources to accommodate your request.</inlineHelpText>
    <label>Target Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/fields/PS_OfferingTopic__c.field-meta.xml
<CustomField>
    <fullName>PS_OfferingTopic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What is the topic of this offering?</description>
    <inlineHelpText>Each offering must be related to a specific Topic offered by the ProServices@ASA team. If an existing Topic does not meet your needs, you may select New Topic Request to request that the ProServices@ASA team create a new Topic for you.</inlineHelpText>
    <label>Pro Services Topic</label>
    <referenceTo>Pro_Services_Topic__c</referenceTo>
    <relationshipLabel>Pro Services Offerings</relationshipLabel>
    <relationshipName>PS_OfferingTopic</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pro_Services_Offering__c/recordTypes/Article.recordType-meta.xml
<RecordType>
    <fullName>Article</fullName>
    <active>false</active>
    <description>Newsletter article submissions</description>
    <label>Article</label>
</RecordType>

force-app/main/default/objects/Pro_Services_Topic__c/Pro_Services_Topic__c.object-meta.xml
<CustomObject>
    <customHelp>PSTopics_CustomHelp</customHelp>
    <description>Topics available for individual Offerings conducted by the Professional Services @ ASA team.</description>
    <label>Pro Services Topic</label>
    <nameField>
        <label>Topic Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pro Services Topics</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pro_Services_Topic__c/fields/PS_TopicDescription__c.field-meta.xml
<CustomField>
    <fullName>PS_TopicDescription__c</fullName>
    <description>Describe this topic.</description>
    <label>Description</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestEmailSurvey.cls
@isTest

private class TestEmailSurvey{

    static testMethod void surveyTest(){
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            
            User u1 = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, 
                                TimeZoneSidKey='America/Los_Angeles', UserName='stdarduser@testog.com');
            insert u1;
                            
            Campaign camp = new Campaign(Name = 'Test Campaign',IsActive = true);
            insert camp;
            
            Campaign camp2 = new Campaign(Name = 'Test Campaign2',IsActive = true,Presenting__c = 'Casey Wallen');
            insert camp2;
            
            Campaign camp3 = new Campaign(Name = 'Test Campaign3',IsActive = true,Presenting__c = 'Casey Wallen;Bob Cole');
            insert camp3;
            
            Pro_Services_Topic__c pst = new Pro_Services_Topic__c(Name = 'Test', PS_TopicDescription__c = 'Test...');
            insert pst;
            
            Pro_Services_Offering__c pso = new Pro_Services_Offering__c(PS_OfferingStatus__c = 'Approved',PS_OfferingAssignedTo__c = u1.Id, 
                                                                        PS_OfferingCampaign__c = camp.Id,PS_OfferingRequestedBy__c = u1.Id,
                                                                        PS_OfferingTargetDate__c = System.Today(),Name = 'MASFAA (MS)-Newsletter Article-Fall 2015',
                                                                        PS_OfferingTopic__c = pst.Id,PS_OfferingCity__c = 'New York City',PS_OfferingState__c = 'NY');
            insert pso;
            
            Pro_Services_Offering__c pso2 = new Pro_Services_Offering__c(PS_OfferingStatus__c = 'Approved',PS_OfferingAssignedTo__c = u1.Id, 
                                                                        PS_OfferingCampaign__c = camp2.Id,PS_OfferingRequestedBy__c = u1.Id,
                                                                        PS_OfferingTargetDate__c = System.Today(),Name = 'MASFAA (MS)-Newsletter Article-Fall 2016',
                                                                        PS_OfferingTopic__c = pst.Id,PS_OfferingCity__c = 'New York City',PS_OfferingState__c = 'NY');
            insert pso2;
            
            Pro_Services_Offering__c pso3 = new Pro_Services_Offering__c(PS_OfferingStatus__c = 'Approved',PS_OfferingAssignedTo__c = u1.Id, 
                                                                        PS_OfferingCampaign__c = camp3.Id,PS_OfferingRequestedBy__c = u1.Id,
                                                                        PS_OfferingTargetDate__c = System.Today(),Name = 'MASFAA (MS)-Newsletter Article-Fall 2014',
                                                                        PS_OfferingTopic__c = pst.Id,PS_OfferingCity__c = 'New York City',PS_OfferingState__c = 'NY');
            insert pso3;
                    
            Campaign_ASA_Attendees__c cASA = new Campaign_ASA_Attendees__c(ASA_Attendee__c = u1.Id, Campaign__c = camp2.Id);
            insert cASA;
            
            camp2.Flag__c = true;
            update camp2;
            try{
                PageReference newPageRef = Page.CampaignSurveyPage;
                Test.setCurrentPage(newPageRef);
                ApexPages.CurrentPage().getParameters().put('campId', camp2.Id);
                ApexPages.CurrentPage().getParameters().put('assignedTo', u1.Id);
                
                CampaignSurveyController csctrl = new CampaignSurveyController();               
                csctrl.saveSurvey();
            }
            catch(Exception e){
                System.debug('An exception has occurred: ' + e.getMessage() + '-' + e.getLineNumber());
            }
        }
        
    }
}