force-app/main/default/objects/Campaign/fields/QR_Code_Valid_FRom__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_Valid_FRom__c</fullName>
    <label>QR Code Valid From</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/QR_Code_Valid_Until__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_Valid_Until__c</fullName>
    <label>QR Code Valid Until</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <label>Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CPSQRCodeGeneratorTest.cls
@isTest
public class CPSQRCodeGeneratorTest
{
    
    @isTest
    public static void generateQRFirstTime()
    {
        Campaign objCamp = new Campaign();
        objCamp.Name = 'Test Campaign';
        objCamp.IsActive = TRUE;
        objCamp.Start_DateTime__c = Date.today();
        insert objCamp;
        
        Campaign campRec = [Select Id,QR_Code_Valid_From__c,QR_Code_Valid_Until__c from Campaign Where Id =: objCamp.Id];
        System.assertEquals(campRec.QR_Code_Valid_From__c,Null);
        System.assertEquals(campRec.QR_Code_Valid_Until__c,Null);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(objCamp);
        CPSQRCodeGenerator objCodeGenerator = new CPSQRCodeGenerator(sc);
        objCodeGenerator.generateCode();
        
    }
    
    @isTest
    public static void generateQRConditionMeet()
    {
        Campaign objCamp = new Campaign();
        objCamp.Name = 'Test Campaign';
        objCamp.IsActive = TRUE;
        objCamp.Start_DateTime__c = Date.today();
        insert objCamp;
        
        Timezone tz = Timezone.getTimeZone('America/New_York');
        DateTime timeQRValidFrom = DateTime.newInstanceGMT(2018, 10, 1, 11, 0, 0);
        DateTime timeQRValidUntill = DateTime.newInstanceGMT(2019, 10, 1, 0, 0, 0);


        objCamp.QR_Code_Valid_From__c = timeQRValidFrom;
        objCamp.QR_Code_Valid_Until__c = timeQRValidUntill;
        update objCamp;
        
        Campaign campRec = [Select Id,QR_Code_Valid_From__c,QR_Code_Valid_Until__c from Campaign Where Id =: objCamp.Id];
        System.assertEquals(campRec.QR_Code_Valid_From__c,timeQRValidFrom);
        System.assertEquals(campRec.QR_Code_Valid_Until__c,timeQRValidUntill);
       
        
        ApexPages.StandardController sc = new ApexPages.StandardController(objCamp);
        CPSQRCodeGenerator objCodeGenerator = new CPSQRCodeGenerator(sc);
        objCodeGenerator.generateCode();
        
    }
    
    @isTest
    public static void generateQR()
    {
        Campaign objCamp = new Campaign();
        objCamp.Name = 'Test Campaign';
        objCamp.IsActive = TRUE;
        objCamp.Start_DateTime__c = Date.today();
        insert objCamp;
        
        Timezone tz = Timezone.getTimeZone('America/New_York');
        DateTime timeQRValidFrom = DateTime.newInstanceGMT(2018, 10, 1, 10, 0, 0);
        DateTime timeQRValidUntill = DateTime.newInstanceGMT(2019, 10, 1, 0, 0, 0);


        objCamp.QR_Code_Valid_From__c = timeQRValidFrom;
        objCamp.QR_Code_Valid_Until__c = timeQRValidUntill;
        update objCamp;
        
        Campaign campRec = [Select Id,QR_Code_Valid_From__c,QR_Code_Valid_Until__c from Campaign Where Id =: objCamp.Id];
        System.assertEquals(campRec.QR_Code_Valid_From__c,timeQRValidFrom);
        System.assertEquals(campRec.QR_Code_Valid_Until__c,timeQRValidUntill);
       
        
        ApexPages.StandardController sc = new ApexPages.StandardController(objCamp);
        CPSQRCodeGenerator objCodeGenerator = new CPSQRCodeGenerator(sc);
        objCodeGenerator.generateCode();
        
    }
}