force-app/main/default/objects/Case/fields/Barrier__c.field-meta.xml
<CustomField>
    <fullName>Barrier__c</fullName>
    <label>Secondary Barrier Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date NOT Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack Of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date in Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Barrier_to_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Barrier_to_Implementation__c</fullName>
    <inlineHelpText>Select the value that best describes the primary reason for Barrier to Implementation.</inlineHelpText>
    <label>Barrier to Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date Not Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date In Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Implementation.recordType-meta.xml
<RecordType>
    <fullName>Implementation</fullName>
    <active>false</active>
    <businessProcess>Implementation</businessProcess>
    <description>Case used to track (Full-Service/Split) Implementations</description>
    <label>Implementation</label>
</RecordType>

force-app/main/default/objects/Case_Barrier__c/Case_Barrier__c.object-meta.xml
<CustomObject>
    <label>Case_Barrier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Barriers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Barrier__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Barriers</relationshipLabel>
    <relationshipName>Case_Barriers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestUpdateCasePrimaryRiskReason.cls
@isTest

private class TestUpdateCasePrimaryRiskReason {
 
    static testmethod void testUpdateCasePrimaryRiskReason() {
    
        String query = 'select id, BARRIER_TO_IMPLEMENTATION__C ,BARRIER__C from case where BARRIER_TO_IMPLEMENTATION__C!=\'\' AND Id =:cs.id' ;
        Account acc = new Account();
        acc.Name = ' College Planning Services';
        insert acc;
        
        Contact ct = new Contact();
        ct.AccountId = acc.Id;
        ct.LastName = 'test Name';
        ct.title = 'test';
        ct.FirstName = 'First Name';
        insert ct;
        
        Case cs = new Case();
        cs.ContactId = ct.id;
        cs.Origin = 'Email';
        cs.Status = 'WIP';
        cs.Type = 'Implementation';
        cs.Barrier__c = 'Connect Date Set'+ ';'+'Demographic File' + ';' + 'Lack Of Campus Support'+ ';' ;
        cs.BARRIER_TO_IMPLEMENTATION__C = 'Connect Date Set';
        insert cs;
        
        Case_Barrier__c csbar = new Case_Barrier__c();
        csbar.Case__c = cs.Id;
        insert csbar;
        test.startTest();
        
        try{             
                UpdateCasePrimaryRiskReason BatchObj1 = new UpdateCasePrimaryRiskReason();
                ID batch_processId=Database.executebatch(BatchObj1, 2);
                system.debug('batch_processId' + batch_processId);  
                system.debug('Database.executebatch(BatchObj1, 2)' + Database.executebatch(BatchObj1, 2));  
                UpdateCasePrimaryRiskReason m = new UpdateCasePrimaryRiskReason ();
            }
            catch(Exception e){
                System.assert( e.getMessage().contains('An exception has occured '+e.getMessage()+'-'+e.getLineNumber()), e.getMessage() );
            }
            test.stopTest();
        
    }
}