force-app/main/default/objects/Case/fields/Barrier__c.field-meta.xml
<CustomField>
    <fullName>Barrier__c</fullName>
    <label>Secondary Barrier Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date NOT Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack Of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date in Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Barrier_to_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Barrier_to_Implementation__c</fullName>
    <inlineHelpText>Select the value that best describes the primary reason for Barrier to Implementation.</inlineHelpText>
    <label>Barrier to Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date Not Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date In Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Implementation.recordType-meta.xml
<RecordType>
    <fullName>Implementation</fullName>
    <active>false</active>
    <businessProcess>Implementation</businessProcess>
    <description>Case used to track (Full-Service/Split) Implementations</description>
    <label>Implementation</label>
</RecordType>

force-app/main/default/objects/Case_Barrier__c/Case_Barrier__c.object-meta.xml
<CustomObject>
    <label>Case_Barrier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Barriers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Barrier__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Barriers</relationshipLabel>
    <relationshipName>Case_Barriers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Barrier__c/fields/Sort_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order_No__c</fullName>
    <label>Sort Order No</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CaseBarrier__c/CaseBarrier__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CaseBarrier</label>
</CustomObject>

force-app/main/default/classes/TestCaseBarrierController.cls
@isTest
public class TestCaseBarrierController {
static testMethod void CaseBarrierMultiPickTestMethod(){
        
        Test.startTest();
        Account accNew = new Account();        
        accNew.Name = 'College Planning Services';
        insert accNew;

        Contact contactA = new Contact();
        contactA.FirstName = 'John';
        contactA.Lastname = 'Doe';
        contactA.AccountId = accNew.Id;
        insert contactA;
    
        Case casevalue = new Case();
        casevalue.AccountId = accNew.Id;
        casevalue.Origin = 'Email';
        casevalue.Subject = 'Test';
        casevalue.Status = 'WIP';
        casevalue.Type = 'Implementation';
        casevalue.ContactId = contactA.Id;
        casevalue.Barrier__c = 'No Implementation Call' + ';' + 'Demographic File' + ';' ;
        casevalue.Barrier_to_Implementation__c = '';
        Insert casevalue;
        System.debug('casevalue '+casevalue);
        
        CaseBarrier__c cb1 =NEW CaseBarrier__c();
        cb1.name='Reason1';
        insert cb1;
       
        CaseBarrier__c cb2 =NEW CaseBarrier__c();
        cb2.name='Reason12';
        insert cb2;

        CaseBarrier__c cb3 =NEW CaseBarrier__c();
        cb3.name='Reason3';
        insert cb3;
       
       List<Case_Barrier__c> barrier = new List<Case_Barrier__c>{};
      for(Integer i = 0; i < 30; i++){
        Case_Barrier__c bar = new Case_Barrier__c(Name = 'Test Case Barrier ' + i , Case__c = casevalue.id , Sort_Order_No__c = 7 );
        barrier.add(bar);
      }
        insert barrier;
        System.debug('barrier'+barrier);
        
        PageReference pageRef = Page.CaseBarrier;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id',casevalue.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(casevalue);
        CaseBarrierController controller = new CaseBarrierController(sc);
        MultiselectController mCtrl=new MultiselectController ();
        mCtrl.accountId=accNew.id;
        mCtrl.leftOptions= new List<SelectOption>();
        mCtrl.rightOptions=new List<SelectOption>();
        mCtrl.leftOptions.add(new SelectOption('Reason1','Reason1'));
        mCtrl.rightOptions.add(new SelectOption('Reason2','Reason2'));
        mCtrl.rightOptionsHidden='Reason2&Reason2';
        mCtrl.leftOptionsHidden='Reason1&Reason1';
        mCtrl.accid=casevalue.id;
        mCtrl.sobjType='Case';
        mCtrl.saveCase();
        
        Test.stopTest();
        }
        
       static testMethod void myUnitTest2() {
        
        Test.startTest();
        Account accNew = new Account();        
        accNew.Name = 'College Planning Services';
        insert accNew;

        Contact contactA = new Contact();
        contactA.FirstName = 'John';
        contactA.Lastname = 'Doe';
        contactA.AccountId = accNew.Id;
        insert contactA;
    
        Case casevalue = new Case();
        casevalue.AccountId = accNew.Id;
        casevalue.Origin = 'Email';
        casevalue.Subject = 'Test';
        casevalue.Status = 'WIP';
        casevalue.Type = 'Implementation';
        casevalue.ContactId = contactA.Id;
        Insert casevalue;
        System.debug('casevalue '+casevalue);
        
        PageReference pNew=Page.AccountRiskReasons;
        Test.setCurrentPage(pNew);
        ApexPages.CurrentPage().getParameters().put('id',casevalue.id);
        ApexPages.standardController controller = new ApexPages.standardController(casevalue);
        CaseBarrierController caseCtrl = new CaseBarrierController(controller );
        
        Test.stopTest();
   
    }
}