force-app/main/default/objects/Case/fields/Barrier__c.field-meta.xml
<CustomField>
    <fullName>Barrier__c</fullName>
    <label>Secondary Barrier Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date NOT Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack Of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date in Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Barrier_to_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Barrier_to_Implementation__c</fullName>
    <inlineHelpText>Select the value that best describes the primary reason for Barrier to Implementation.</inlineHelpText>
    <label>Barrier to Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date Not Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date In Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Barrier__c/Case_Barrier__c.object-meta.xml
<CustomObject>
    <label>Case_Barrier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Barriers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Barrier__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Barriers</relationshipLabel>
    <relationshipName>Case_Barriers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Barrier__c/fields/Sort_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order_No__c</fullName>
    <label>Sort Order No</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateCasePrimaryRiskReason.cls
global class UpdateCasePrimaryRiskReason implements Database.Batchable<sobject>
{

    global DataBase.querylocator start(Database.BatchableContext bc)
    {
        return Database.getQueryLocator('select id, BARRIER_TO_IMPLEMENTATION__C ,BARRIER__C from case where BARRIER_TO_IMPLEMENTATION__C!=\'\' order by id');
    }

    global void execute(Database.BatchableContext bc ,List<sobject> scope)
    {
        List< Case_Barrier__c> cList =new List< Case_Barrier__c>();
        List<Case> aList =new List<case>();
        for(Sobject s: scope)
        {
            Case aTemp=(Case) s;
            System.debug('Account id '+aTemp);    
            String newS=aTemp.BARRIER_TO_IMPLEMENTATION__C;
            Boolean first=true;
            integer count=1;

            Case_Barrier__c cTemp =new Case_Barrier__c();
            cTemp.name=newS;
            cTemp.case__c=aTemp.id;
            cTemp.Sort_Order_No__c=count;
                    
            cList.add(cTemp);
        
        }
        
        System.debug('An cList '+cList);
        
        try
            {
                if(cList.size()>0)
                    insert cList;
            }
            catch(Exception e)
            {
                System.debug('An exception has occured '+e.getMessage()+'-'+e.getLineNumber());
            
            }
    
    }
    
    global void finish(Database.BatchableContext bc)
    {
    
    }
    

}