force-app/main/default/objects/Case/fields/Opportunity_Link__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Link__c</fullName>
    <label>Opportunity Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Implementation.recordType-meta.xml
<RecordType>
    <fullName>Implementation</fullName>
    <active>false</active>
    <businessProcess>Implementation</businessProcess>
    <description>Case used to track (Full-Service/Split) Implementations</description>
    <label>Implementation</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ByPassRolloverWFRules__c.field-meta.xml
<CustomField>
    <fullName>ByPassRolloverWFRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPassRolloverWFRules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Create_Rollover_Oppty__c.field-meta.xml
<CustomField>
    <fullName>Create_Rollover_Oppty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Rollover Oppty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loss__c.field-meta.xml
<CustomField>
    <fullName>Loss__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When the opportunity is lost check this box and fill out the loss reasons.</description>
    <inlineHelpText>Don&#39;t forget to choose the loss reasons.</inlineHelpText>
    <label>Loss</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Loss_Reason__c</fullName>
    <label>Primary Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Loss__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Budget Cycle/Lack of Funds</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Currently under contract</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>In house solution</fullName>
            </value>
            <value>
                <fullName>Interested, but not ready yet</fullName>
            </value>
            <value>
                <fullName>No Response</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
            <value>
                <fullName>RFP Selection</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Opp__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Opp__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if this is a Renewal Opportunity.</inlineHelpText>
    <label>Renewal Opp?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rollover__c.field-meta.xml
<CustomField>
    <fullName>Rollover__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rollover</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/**************************
Name : DevTeam
Changes : Set 'ByPassRolloverWFRules' field value on rollover opportunity true
Date : 9/22/2016
**************************/

public class OpportunityTriggerHandler{
    
    //public static boolean firstRun = true;
    public static boolean runOnce_createImpCase = false;
    public static boolean runOnce_rolloverOpportunity = false;

    //Class to create Case for Implementation
    public static void createImpCase(Set<Id> opptyKeySet) {
        
        //Instantiate a list of Cases to insert
        List<Case> caseList = new List<Case>();
        ID recTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Implementation Consumer Services').getRecordTypeId();
        
        //Query the entire list of updated Opportunities
        List<Opportunity> opptyList = [SELECT Name,
                                            RecordTypeId,
                                            StageName, 
                                            Renewal_Opp__c,
                                            Account.OwnerId,
                                            Account.Owner.isActive, 
                                            Account.Name, 
                                            (SELECT ContactId, Role FROM OpportunityContactRoles WHERE isPrimary = true LIMIT 1) 
                                    From Opportunity 
                                    WHERE Id IN :opptyKeySet];
        
        //Check Opportunities for criteria and create cases if it passes 
        for(Opportunity o : opptyList){
            
            //Record Type = Business Development AND Stage = Implementation BUT NOT Renewal = true OR OpportunityName contains renewal
            Case c = new Case();
            c.Subject = o.Account.Name + ' - Implementation';
            c.RecordTypeId = recTypeId; //Record Type: Implementation Consumer Services
            c.Origin = 'Email';
            c.Status = 'WIP';
            c.Type = 'Implementation';
            c.Opportunity_Link__c = URL.getSalesforceBaseUrl().toExternalForm().replace('http://','https://') + '/' + o.id;
            c.AccountId = o.AccountId;

            if(o.Account.Owner.isActive == true){
                //Change Owner
                c.OwnerId = o.Account.OwnerId;
            }
            if(o.OpportunityContactRoles.size() > 0){
                c.ContactId = o.OpportunityContactRoles[0].ContactId;
            }
            caseList.add(c);                
        }
        if(caseList.size()>0){
            Database.insert(caseList,false);
            runOnce_createImpCase = true;
        }
    }

    public static void rolloverOpportunity(List<Opportunity> opptyList){

        List<Opportunity> insertOppty = new List<Opportunity>();

        for(Opportunity oppty : opptyList){

            Date nextFYDate;
            String nextFYString;
            String[] listOfFY = new String[]{};

            listOfFY.add(System.today().addYears(-2).year().format().remove(','));
            listOfFY.add(System.today().addYears(-1).year().format().remove(','));
            listOfFY.add(System.today().year().format().remove(','));
            listOfFY.add(System.today().addYears(1).year().format().remove(','));
            listOfFY.add(System.today().addYears(2).year().format().remove(','));

            //Determine last day of the next fiscal year
            if(System.today() < Date.newInstance(System.today().year(),7,1)){
                //This FY
                nextFYDate = Date.newInstance(System.today().addYears(1).year(),6,30);
                nextFYString = System.today().addYears(1).year().format().remove(',');

            } else{
                //Next FY
                nextFYDate = Date.newInstance(System.today().addYears(2).year(),6,30);
                nextFYString = System.today().addYears(2).year().format().remove(',');
            }

            //Create new rollover Opportunity
            for(String year : listOfFY){

                if(oppty.Name.contains(year)){
                    oppty.Name = oppty.Name.replace(year,nextFYString);
                }
            }
            if(oppty.StageName == 'Closed - Lost'){
                oppty.StageName = 'Prospect';
                oppty.Primary_Loss_Reason__c = null;
                oppty.Loss__c = false;
            }
            oppty.CloseDate = nextFYDate;
            oppty.Rollover__c = false;
            oppty.Create_Rollover_Oppty__c = false;
            oppty.ByPassRolloverWFRules__c=True; 
            insertOppty.add(oppty);
        }

        insert insertOppty;
        runOnce_rolloverOpportunity = true;
    }
}