force-app/main/default/objects/CPS_Location_Code__mdt/CPS_Location_Code__mdt.object-meta.xml
<CustomObject>
    <label>CPS Location Code</label>
    <pluralLabel>CPS Location Codes</pluralLabel>
</CustomObject>

force-app/main/default/objects/CPS_Location_Code__mdt/fields/Location_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Code__c</fullName>
    <label>Location Code</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CPS_Location_Code__mdt/fields/Location_Name__c.field-meta.xml
<CustomField>
    <fullName>Location_Name__c</fullName>
    <label>Location Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CPSInputLocationCodeTest.cls
/**
@Name            : CPSInputLocationCodeTest
@Description     : Test class for 'CPSInputLocationCode' Class 
**/
@isTest
public class CPSInputLocationCodeTest{
    @isTest
    public static void unitTest(){
        CPSInputLocationCode objCPSInputLocation = new CPSInputLocationCode();
        List<CPS_Location_Code__mdt> lstCpsData = [Select location_name__c,Location_Code__c
                               from CPS_Location_Code__mdt where location_name__c = 'EOC Boston'];
        if(lstCpsData != null && lstCpsData.size()>0){
            objCPSInputLocation.cpsLocationCode = lstCpsData[0].Location_Code__c;   
        }
        objCPSInputLocation.fetchLocationName();
    }
    
    @isTest
    public static void unitTest2(){
        CPSInputLocationCode objCPSInputLocation = new CPSInputLocationCode();
        List<CPS_Location_Code__mdt> lstCpsData = [Select location_name__c,Location_Code__c
                               from CPS_Location_Code__mdt where location_name__c = 'TS Boston'];
        if(lstCpsData != null && lstCpsData.size()>0){
            objCPSInputLocation.cpsLocationCode = lstCpsData[0].Location_Code__c;   
        }
        objCPSInputLocation.fetchLocationName();
    }
    
    @isTest
    public static void unitTest3(){
        CPSInputLocationCode objCPSInputLocation = new CPSInputLocationCode();
        objCPSInputLocation.cpsLocationCode = 'xyz';
        objCPSInputLocation.fetchLocationName();
    }
}