force-app/main/default/objects/Campaign_ASA_Attendees__c/Campaign_ASA_Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee Feedback</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendee Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/ASA_Attendee__c.field-meta.xml
<CustomField>
    <fullName>ASA_Attendee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ASA Attendee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Attendee Feedback</relationshipLabel>
    <relationshipName>Campaign_Email_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Recommendation_for_Next_Year_s_Show__c.field-meta.xml
<CustomField>
    <fullName>Recommendation_for_Next_Year_s_Show__c</fullName>
    <label>Recommendation for Next Year&#39;s Show</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Attend</fullName>
            </value>
            <value>
                <fullName>Present &amp; Attend</fullName>
            </value>
            <value>
                <fullName>Don&#39;t Go</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Total_Cost_of_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_of_Attendance__c</fullName>
    <inlineHelpText>This includes airfare, hotel, meals, transportation.</inlineHelpText>
    <label>Total Cost of Attendance?</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_ASA_Attendees__c/fields/Why_did_they_attend__c.field-meta.xml
<CustomField>
    <fullName>Why_did_they_attend__c</fullName>
    <label>Reason for Attending</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/CampaignSurveyController.cls
public class CampaignSurveyController{

    public Campaign_ASA_Attendees__c campsurvey{get;set;}
    
    public CampaignSurveyController(){
    
        campsurvey = new Campaign_ASA_Attendees__c();
        String campId = ApexPages.CurrentPage().getParameters().get('campId');
        String assignedTo = ApexPages.CurrentPage().getParameters().get('assignedTo'); 
        campsurvey = [Select Campaign__c,ASA_Attendee__c,Recommendation_for_Next_Year_s_Show__c,Total_Cost_of_Attendance__c,Why_did_they_attend__c From Campaign_ASA_Attendees__c Where Campaign__c =: campId AND ASA_Attendee__c =: assignedTo];
    }
    
    public PageReference saveSurvey(){
        try{
            update campsurvey;
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your changes have been saved successfully.'));
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
        return null;
    }       
}