force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>School record type</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Onboarding_Form__c/Onboarding_Form__c.object-meta.xml
<CustomObject>
    <label>Onboarding Form</label>
    <nameField>
        <label>Onboarding Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Form__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>Organization Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboarding Forms</relationshipLabel>
    <relationshipName>EDMS_Onboarding_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestOnboardingFormEditcls.cls
@isTest
private class TestOnboardingFormEditcls{

    static testmethod void testMethod1() {
      
              
            RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='Account' AND Name='School'];           
            Account acc = new Account(Name = 'Onboarding Test Acc',RecordTypeId=rt.id,Type='School - 3 Year School');
            insert acc;
            
            Account acc1 = new Account(Name = 'Onboarding Test Acc1',RecordTypeId=rt.id,Type='School - 4 Year School');
            insert acc1;
                                 
            Onboarding_Form__c onn = new Onboarding_Form__c(School_Name__c = acc.Id);
            Onboarding_Form__c onn1 = new Onboarding_Form__c(School_Name__c = acc1.Id);
                 
            OnboardingFormEditcls obj = new OnboardingFormEditcls (new ApexPages.StandardController(onn));
            obj.saveOff();
            OnboardingFormEditcls obj1 = new OnboardingFormEditcls (new ApexPages.StandardController(onn1));
            obj1.saveOff();
            
            
    }
}