force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>School record type</description>
    <label>School</label>
</RecordType>

force-app/main/default/objects/Onboarding_Form__c/Onboarding_Form__c.object-meta.xml
<CustomObject>
    <label>Onboarding Form</label>
    <nameField>
        <label>Onboarding Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Onboarding Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Onboarding_Form__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <label>Organization Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Onboarding Forms</relationshipLabel>
    <relationshipName>EDMS_Onboarding_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Onboarding_Form__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>School - 2 Year Private</fullName>
            </value>
            <value>
                <fullName>School - 2 Year Public</fullName>
            </value>
            <value>
                <fullName>School - 3 Year School</fullName>
            </value>
            <value>
                <fullName>School - 4 Year Private</fullName>
            </value>
            <value>
                <fullName>School - 4 Year Public</fullName>
            </value>
            <value>
                <fullName>School - Foreign School</fullName>
            </value>
            <value>
                <fullName>School - Grad/Profession</fullName>
            </value>
            <value>
                <fullName>School - Liberal Arts</fullName>
            </value>
            <value>
                <fullName>School - Proprietary</fullName>
            </value>
            <value>
                <fullName>School - Voc or Tech</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OnboardingFormEditcls.cls
public class OnboardingFormEditcls {

    public Onboarding_Form__c oObject{get;set;}
    public OnboardingFormEditcls (ApexPages.StandardController stdController){
        this.oObject= (Onboarding_Form__c )stdController.getrecord();
        for(Account acc : [SELECT Id,Name,Type,Recordtype.Name FROM Account WHERE Id =: oObject.School_Name__c and Recordtype.Name = 'School']){
           oObject.Name = acc.Name + ' '+'Onboarding' +' ' + date.today().month() + '-'+ date.today().Year();
           oObject.Type__c  = acc.Type;
        }
   }
   
   public PageReference saveOff(){
       
       try{
            if(oObject != null){
            insert oObject;
            }
          }
       catch(system.dmlException e) 
          {
            Apexpages.AddMessages(e);
            return null;
          }
        PageReference page = new Pagereference('/'+oObject.Id);
        page.setRedirect(true);
        return page;
   }
}