force-app/main/default/objects/Account/fields/Campus_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Campus_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campus Consultant</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This user is not a designated Campus Consultant.</errorMessage>
        <filterItems>
            <field>User.Cost_Center__c</field>
            <operation>equals</operation>
            <value>16350</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CACs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>School record type</description>
    <label>School</label>
</RecordType>

force-app/main/default/classes/BatchAccountTeamOnAccount.cls
global class BatchAccountTeamOnAccount implements Database.Batchable<sObject>, Schedulable{
   
    // Start Method
    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'Select Name,OwnerId,Campus_Consultant__c,Regional_Account_Executive__c,(Select AccountId,TeamMemberRole,UserId From AccountTeamMembers) From Account';
        return Database.getQueryLocator(query);
    }
    
    // Execute Method
    global void execute(Database.BatchableContext BC, List<Account> accList){
        try{
            Map<Id,Account> accMap = new Map<Id,Account>();
            
            for(Account accTemp : accList){
                if(accTemp.AccountTeamMembers.size()>0){
                    Boolean ccTeamRoleExist = false;
                    Boolean raeTeamRoleExist = false;    
                    for(AccountTeamMember teamMem : accTemp.AccountTeamMembers){
                        if(teamMem.TeamMemberRole == 'Campus Consultant'){
                            ccTeamRoleExist = true;    
                        }
                        if(teamMem.TeamMemberRole == 'Business Development AE'){
                            raeTeamRoleExist = true;    
                        }
                    }
                    
                    for(AccountTeamMember teamMemTemp : accTemp.AccountTeamMembers){
                        if(teamMemTemp.TeamMemberRole == 'School Client Manager' && accTemp.OwnerId != teamMemTemp.UserId){
                            if(!accMap.containsKey(teamMemTemp.AccountId)){
                                accMap.put(teamMemTemp.AccountId,new Account(Id=teamMemTemp.AccountId,OwnerId = teamMemTemp.UserId));
                            } else{
                                accMap.get(teamMemTemp.AccountId).OwnerId = teamMemTemp.UserId;
                            }
                        }
                        if(teamMemTemp.TeamMemberRole == 'Campus Consultant' && accTemp.Campus_Consultant__c != teamMemTemp.UserId){
                            if(!accMap.containsKey(teamMemTemp.AccountId)){
                                accMap.put(teamMemTemp.AccountId,new Account(Id=teamMemTemp.AccountId,Campus_Consultant__c = teamMemTemp.UserId));
                            } else{
                                accMap.get(teamMemTemp.AccountId).Campus_Consultant__c = teamMemTemp.UserId;
                            } 
                        } 
                        if(teamMemTemp.TeamMemberRole == 'Business Development AE' && accTemp.Regional_Account_Executive__c != teamMemTemp.UserId){
                            if(!accMap.containsKey(teamMemTemp.AccountId)){
                                accMap.put(teamMemTemp.AccountId,new Account(Id=teamMemTemp.AccountId,Regional_Account_Executive__c = teamMemTemp.UserId));
                            } else{
                                accMap.get(teamMemTemp.AccountId).Regional_Account_Executive__c = teamMemTemp.UserId;
                            }  
                        }
                        if(accTemp.Campus_Consultant__c != null && !ccTeamRoleExist){
                            if(!accMap.containsKey(teamMemTemp.AccountId)){
                                accMap.put(teamMemTemp.AccountId,new Account(Id=teamMemTemp.AccountId,Campus_Consultant__c = null));
                            } else{
                                accMap.get(teamMemTemp.AccountId).Campus_Consultant__c = null;
                            } 
                        }
                        if(accTemp.Regional_Account_Executive__c != null && !raeTeamRoleExist){
                            if(!accMap.containsKey(teamMemTemp.AccountId)){
                                accMap.put(teamMemTemp.AccountId,new Account(Id=teamMemTemp.AccountId,Regional_Account_Executive__c = null));
                            } else{
                                accMap.get(teamMemTemp.AccountId).Regional_Account_Executive__c = null;
                            }       
                        }
                    }
                }else{
                     if(accTemp.Campus_Consultant__c != null || accTemp.Regional_Account_Executive__c != null){
                         if(!accMap.containsKey(accTemp.Id)){
                                accMap.put(accTemp.Id,new Account(Id=accTemp.Id,Regional_Account_Executive__c = null,Campus_Consultant__c = null));
                            } else{
                                accMap.get(accTemp.Id).Campus_Consultant__c = null;
                                accMap.get(accTemp.Id).Regional_Account_Executive__c = null;
                            } 
                     }  
                }
            }
            Database.update (accMap.values(),false);
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
    
    //Schedule Method
    global void execute(SchedulableContext sc) {
        BatchAccountTeamonAccount b1 = new BatchAccountTeamonAccount();
        ID batchprocessid = Database.executeBatch(b1);    
    }
    
    // Finish Method      
    global void finish(Database.BatchableContext BC){
            
    }
}