force-app/main/default/objects/Account/fields/Campus_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Campus_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campus Consultant</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This user is not a designated Campus Consultant.</errorMessage>
        <filterItems>
            <field>User.Cost_Center__c</field>
            <operation>equals</operation>
            <value>16350</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CACs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/OE_Code__c.field-meta.xml
<CustomField>
    <fullName>OE_Code__c</fullName>
    <label>OE Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/Account_Planning__c.object-meta.xml
<CustomObject>
    <description>This new object / related list will be the place in which school &amp;/or lender CMs will post annual account plans.</description>
    <label>Account Planning</label>
    <nameField>
        <label>Account Plan Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Planning</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Planning__c/fields/Account_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field displays the current account for which the plan is being reported.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>R00N60000001Y5A0EAK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/fields/Account_Owner_Client_Manager__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Client_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field shows the name of the Client Manager for this account.</description>
    <inlineHelpText>This field contains the name of the School Client Manager for this account.</inlineHelpText>
    <label>Account Owner/Client Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N60000001Y3PlEAK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/fields/Campus_Consultant__c.field-meta.xml
<CustomField>
    <fullName>Campus_Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campus Consultant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Planning</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/fields/OE_Code__c.field-meta.xml
<CustomField>
    <fullName>OE_Code__c</fullName>
    <description>This field contains the OE Code of the Account for which this plan is being reported.</description>
    <inlineHelpText>This field contains the OE Code of the Account for which this plan is being reported.</inlineHelpText>
    <label>OE Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Planning__c/fields/regional_account_executive__c.field-meta.xml
<CustomField>
    <fullName>regional_account_executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the Regional Account Executive responsible for this account.</description>
    <inlineHelpText>This field contains the Regional Account Executive responsible for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00N60000001Y3PqEAK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountPlanningTriggerHandler.cls
public class AccountPlanningTriggerHandler{

    public static void populate_fields_from_account(List<Account_Planning__c> apList){
    
        Set<Id> accId = new Set<Id>();
        Map<Id,Account> accMap = new Map<Id,Account>();
        
        try{
            for(Account_Planning__c apTemp : apList){
                if(apTemp.Account_Name_2__c != null){
                    accId.add(apTemp.Account_Name_2__c);
                }
            }
            if(accId.size()>0){
                List<Account> accList = [Select Id,Campus_Consultant__c,OwnerId,Regional_Account_Executive__c,Contract_Start__c,OE_Code__c From Account Where Id IN : accId];
                for(Account acc : accList){
                    accMap.put(acc.Id,acc);
                }
                for(Account_Planning__c ap: apList){
                    if(ap.Account_Name_2__c != null){
                        if(accMap.containsKey(ap.Account_Name_2__c)){
                            ap.Contract_Start_Date__c = accMap.get(ap.Account_Name_2__c).Contract_Start__c;
                            ap.OE_Code__c = accMap.get(ap.Account_Name_2__c).OE_Code__c;
                            ap.regional_account_executive__c = accMap.get(ap.Account_Name_2__c).Regional_Account_Executive__c;
                            ap.account_owner_client_manager__c = accMap.get(ap.Account_Name_2__c).OwnerId;
                            ap.Campus_Consultant__c = accMap.get(ap.Account_Name_2__c).Campus_Consultant__c;
                        }
                    }
                }
            }
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
}