force-app/main/default/objects/Account/fields/Contract_End__c.field-meta.xml
<CustomField>
    <fullName>Contract_End__c</fullName>
    <label>Contract End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start__c</fullName>
    <label>Contract Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/School.recordType-meta.xml
<RecordType>
    <fullName>School</fullName>
    <active>true</active>
    <description>School record type</description>
    <label>School</label>
</RecordType>

force-app/main/default/classes/MarketShareMap_Ctrl_TEST.cls
@ISTEST
public class MarketShareMap_Ctrl_TEST
{
    public static testmethod void run()
    {    id rTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('School').getRecordTypeId();
        Account acc=new Account(recordtypeid=rTypeId,name='test',Contract_Start__c=system.today()-10,Contract_end__c=System.today()+10,BillingState='CT');
        insert acc;   
        
       Datetime myDatetime = Datetime.now().adddays(1);
       String myDatetimeStr = myDatetime.format('MM/dd/yyyy');
       
        MarketShareMap_Ctrl.generateMap(myDatetimeStr,'');
        
        PageReference pageRef = Page.MarketShareMapPDF;
Test.setCurrentPage(pageRef);
ApexPages.currentPage().getParameters().put('date',myDatetimeStr );


        
        MarketShareMap_Ctrl obj =new MarketShareMap_Ctrl();
        obj.GenerateMapPDF();
        
        
        obj.dateP=myDatetimeStr;
        obj.stateP='CT';
        obj.fullState='Connecticut';
        obj.generateTable();
        
    }


}