force-app/main/default/objects/Account/fields/Full_Time_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Full_Time_Enrollment__c</fullName>
    <label>Full-Time Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Any type of Account which does not fall under any of the other &quot;Type&quot; categories</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Create_Rollover_Oppty__c.field-meta.xml
<CustomField>
    <fullName>Create_Rollover_Oppty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Rollover Oppty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Full_Time_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Full_Time_Enrollment__c</fullName>
    <label>Full-Time Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rollover__c.field-meta.xml
<CustomField>
    <fullName>Rollover__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rollover</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestBatchCreateRolloverOppty.cls
@isTest

private class TestBatchCreateRolloverOppty {

    static testmethod void testBatchCreateOppty() {
        
        Test.startTest();
        
        Account acc = new Account(Name = 'Account 2016',Full_Time_Enrollment__c = 1);
        insert acc;
        
        Opportunity opp = new Opportunity(Name = 'Oppty-2016',Rollover__c = true, Create_Rollover_Oppty__c = false,AccountId = acc.Id,CloseDate = System.Today(),StageName = 'Prospect',LeadSource = 'Other');
        insert opp;
        
        BatchCreateRolloverOppty batch1 = new BatchCreateRolloverOppty();
        ID batchprocessid = Database.executeBatch(batch1);
        
        Test.stopTest();
    }
}