force-app/main/default/objects/Account/fields/OE_Code__c.field-meta.xml
<CustomField>
    <fullName>OE_Code__c</fullName>
    <label>OE Code</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SALT_Product__c/SALT_Product__c.object-meta.xml
<CustomObject>
    <description>This object will capture the products that are purchased by schools from SALT</description>
    <label>SALT Product</label>
    <nameField>
        <label>SALT Item Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SALT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SALT_Product__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>This field will capture the cost of the product</description>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SALT_Product__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This field will capture the product item description</description>
    <label>Product Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SALT_Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <description>This field will capture the family to which the product belongs</description>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Printed Materials</fullName>
            </value>
            <value>
                <fullName>Premiums</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALT_Record__c/SALT_Record__c.object-meta.xml
<CustomObject>
    <description>Custom Object to hold  all purchases made under account records.</description>
    <label>SALT Purchases</label>
    <nameField>
        <label>Salt Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SALT Purchases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SALT_Record__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>Field contains the item cost.</description>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/ItemCode__c.field-meta.xml
<CustomField>
    <fullName>ItemCode__c</fullName>
    <description>Field to uniquely identify the Item</description>
    <label>Item Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/OE_Code__c.field-meta.xml
<CustomField>
    <fullName>OE_Code__c</fullName>
    <description>Field to hold the Customer Number(OE Code)</description>
    <label>OE Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/ProductLine__c.field-meta.xml
<CustomField>
    <fullName>ProductLine__c</fullName>
    <inlineHelpText>Field  refers specifically to what you sell</inlineHelpText>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premiums</fullName>
            </value>
            <value>
                <fullName>Printed Materials</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Field holds the Quantity of Items.</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/SALT_Product__c.field-meta.xml
<CustomField>
    <fullName>SALT_Product__c</fullName>
    <label>SALT Product</label>
    <referenceTo>SALT_Product__c</referenceTo>
    <relationshipName>Salt_Records</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SALT_Record__c/fields/ShipDate__c.field-meta.xml
<CustomField>
    <fullName>ShipDate__c</fullName>
    <description>Field use to hold the shipping date and time.</description>
    <label>Ship Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestGetDetailsFromProduct.cls
@istest
public class TestGetDetailsFromProduct{

    public static testMethod void unitTest()
    {
        Test.startTest();
        SALT_Product__C pTemp=new SALT_Product__C();
        pTemp.name='Item';
        pTemp.cost__c=1;
        pTemp.Description__c='Item Description';
        pTemp.Family__c='TestFamily';
        
        insert pTemp;
        
        Account acc=new Account();
        acc.name='test Account';
        acc.OE_Code__c='1234';
        insert acc;
        
        SALT_Record__c rTemp=new SALT_Record__c();
        rTemp.name='Item';
        rTemp.itemCode__c='Item';
        rTemp.ShipDate__c=System.today();
        rTemp.Quantity__C=1;
        rTemp.ProductLine__c='TestFamily';
        rTemp.OE_Code__c='1234';
        insert rTemp;
    
        SALT_Record__c rTemp2=new SALT_Record__c();
        rTemp2.name='Item';
        rTemp.itemCode__c='Item';
        rTemp2.ShipDate__c=System.today();
        rTemp2.Quantity__C=1;
        rTemp2.ProductLine__c='TestFamily';
        rTemp2.OE_Code__c='12345';
       try
       {
        insert rTemp2;
       }
       catch(exception e)
       {
           system.assertEquals(e.getMessage().contains('exception'),true);
       } 
     
       Test.stopTest();
        
    }
}