force-app/main/default/objects/Account/fields/Primary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Risk_Lost_Reason__c</fullName>
    <inlineHelpText>Select the most significant reason that puts this account at risk/lost.</inlineHelpText>
    <label>Primary Risk/Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Risk_Lost_Reason__c</fullName>
    <description>If the rating is = to anything but Stable need to put in a reason why the volume is at risk or lost.</description>
    <label>Secondary Risk/Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/Secondary_Risk_Lost_Reason__c.object-meta.xml
<CustomObject>
    <label>Secondary Risk/Lost Reason</label>
    <nameField>
        <label>Selected Values</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Risk/Lost Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Risk/Lost Reasons</relationshipLabel>
    <relationshipName>Secondary_Risk_Lost_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SecondaryRisk__c/SecondaryRisk__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Secondary Risk Values</description>
    <label>Secondary Risk</label>
</CustomObject>

force-app/main/default/classes/MultiselectPickListController.cls
public with sharing class MultiselectPickListController {


    public SelectOption[] selectedRisks { get;set;}
    public SelectOption[] allRisks { get;set;}
    public String id;
    public String message { get;set;}
    public String PrimaryMessage { get;set;}
    public String outputMessage {
        get {
            IF(outputMessage.length()> 100) outputMessage = outputMessage.subString(0, 100) + '...';

            return outputMessage;
        }
        set;
    }
    public Boolean show { get;set;}
    public Boolean showLink{ get;set;}
    public Account acc { get;set;}

    public MultiselectPickListController() {
        outputMessage = '';
        Boolean fTime = false;
        String url = ApexPages.currentPage().getUrl();
        System.debug('url ' + url);
        id = Apexpages.currentPage().getParameters().get('id'); // Account Id

        if (id != null) {
            acc = [SELECT Id, Primary_Risk_Lost_Reason__c FROM Account where id = : id];

            selectedRisks = new List <SelectOption> ();

            List <String> risks = generateList([SELECT Name, id FROM SecondaryRisk__c]);

            List <String> riskByAccount = generateList([select name from Secondary_Risk_Lost_Reason__c where parentId__C = : id  order by sort_Order__C ASC ]);
            Map<Decimal,String> sortMap=new Map<Decimal,String>();
            
            for(Secondary_Risk_Lost_Reason__c sTemp :  [ select sort_Order__C, name from Secondary_Risk_Lost_Reason__c where parentId__C = : id  order by sort_Order__C ASC ])
            {
                    
            sortMap.put(sTemp.sort_Order__C,sTEmp.name);
            
            }
            
            System.debug('XXXXXXXXX '+sortMap);
            //create set to remove selected element
            Set <String> setRisks = new Set <String> ();
            setRisks.addAll(risks);

            Set <String> setRiskByAccount = new Set <String> ();
            setRiskByAccount.addAll(riskByAccount);

            setRisks.removeAll(setRiskByAccount);

            allRisks = new List <SelectOption> ();
            for (String c: setRisks) {
                allRisks.add(new SelectOption(c, c));
            }
/*
            for (String c: setRiskByAccount) {
                selectedRisks.add(new SelectOption(c, c));
            }
*/
/*
            for (Decimal c: sortMap.keyset()) {
             System.debug('XXXXXXX '+c);
                selectedRisks.add(new SelectOption(sortMap.get(c), sortMap.get(c)));
            }
            */
            
            list<decimal> ranksList = new list<decimal>();
            ranksList.addAll(sortMap.keySet());

            //now sort them
            ranksList.sort();
            
            system.debug('keys sorted '+ ranksList);
            
            for(Decimal dTemp : ranksList)
            {
                String sTemp=sortMap.get(dTemp);
               system.debug('keys sorted values '+ sTemp);
                selectedRisks.add(new SelectOption(sTemp, sTemp));
            
            }
            
            
            List <Secondary_Risk_Lost_Reason__c> tempList = [select id, name from Secondary_Risk_Lost_Reason__c where parentId__C = : id order by sort_Order__C ASC];
            for (Secondary_Risk_Lost_Reason__c scTemp: tempList) {
                if (fTime == false) {
                    outputMessage = scTemp.name;
                    fTime = true;
                    PrimaryMessage = scTemp.name;
                } else {
                    outputMessage += ';' + scTemp.name;
                }

            }

            if (outputMessage == '') {
                show = False;
                showLink = true;
                outputMessage = 'Select Secondary Reason';
            } else {
                show = true;
                showLink = False;
            }
        }
    }

    private List <String> generateList(List <sobject> sobj) {

        List <String> retStr = new List <String> ();

        for (sobject sTemp: sobj) {
            if (sTemp.getSObjectType() == Secondary_Risk_Lost_Reason__c.sObjectType) {
                sTemp = (Secondary_Risk_Lost_Reason__c) sTemp;
            } else if (sTemp.getSObjectType() == SecondaryRisk__c.sObjectType) {
                sTemp = (SecondaryRisk__c) sTemp;
            }

            retStr.add(String.valueOf(sTemp.get('Name')));
        }
        return retStr;


    }
}