force-app/main/default/objects/Account/fields/Primary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Risk_Lost_Reason__c</fullName>
    <inlineHelpText>Select the most significant reason that puts this account at risk/lost.</inlineHelpText>
    <label>Primary Risk/Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Risk_Lost_Reason__c</fullName>
    <description>If the rating is = to anything but Stable need to put in a reason why the volume is at risk or lost.</description>
    <label>Secondary Risk/Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Barrier__c.field-meta.xml
<CustomField>
    <fullName>Barrier__c</fullName>
    <label>Secondary Barrier Reasons</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date NOT Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack Of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date in Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Barrier_to_Implementation__c.field-meta.xml
<CustomField>
    <fullName>Barrier_to_Implementation__c</fullName>
    <inlineHelpText>Select the value that best describes the primary reason for Barrier to Implementation.</inlineHelpText>
    <label>Barrier to Implementation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Implementation Call</fullName>
            </value>
            <value>
                <fullName>Connect Date Not Set</fullName>
            </value>
            <value>
                <fullName>Demographic File and NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Demographic File</fullName>
            </value>
            <value>
                <fullName>NSLDS Access</fullName>
            </value>
            <value>
                <fullName>Lack of Campus Support</fullName>
            </value>
            <value>
                <fullName>Connect Date In Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Barrier__c/Case_Barrier__c.object-meta.xml
<CustomObject>
    <label>Case_Barrier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case_Barriers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Barrier__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case_Barriers</relationshipLabel>
    <relationshipName>Case_Barriers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Barrier__c/fields/Sort_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order_No__c</fullName>
    <label>Sort Order No</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/Secondary_Risk_Lost_Reason__c.object-meta.xml
<CustomObject>
    <label>Secondary Risk/Lost Reason</label>
    <nameField>
        <label>Selected Values</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Risk/Lost Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Risk/Lost Reasons</relationshipLabel>
    <relationshipName>Secondary_Risk_Lost_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/MultiselectController.cls
Public with sharing class MultiselectController {
    
    // SelectOption lists for public consumption
    public SelectOption[] leftOptions {get;set;}
    public SelectOption[] rightOptions {get;set;}
    public String accid {get;set;}
    public String accountid {get;set;}
    public String sObjType {get;set;}

    // Parse &-separated values and labels from value and 
    // put them in option
    private void setOptions(SelectOption[] options, String value) {
        options.clear();
        String[] parts = value.split('&');
        for (Integer i = 0; i < parts.size() / 2; i++) {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }
    }

    // Backing for hidden text field containing the options from the left list
    public String leftOptionsHidden {
        get;
        set {
            leftOptionsHidden = value;
            setOptions(leftOptions, value);
        }
    }

    // Backing for hidden text field containing the options from the right list
    public String rightOptionsHidden {
        get;
        set {
            rightOptionsHidden = value;
            setOptions(rightOptions, value);
        }
    }

    public PageReference saveAccount() {
        List <SelectOption> options = new List <SelectOption> ();
        System.debug('rightOptionsHidden  is ' + rightOptionsHidden);
        String message='';
        String[] parts = rightOptionsHidden.split('&');
        for (Integer i = 0; i <parts.size() / 2; i++) {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }

        List <Secondary_Risk_Lost_Reason__c> newRecordsList = new List <Secondary_Risk_Lost_Reason__c> ();
 
        Boolean first = true;
        String Primary;
        integer sortOrder = 0;
        for (SelectOption so: options) {
            sortOrder++;
            Secondary_Risk_Lost_Reason__c newRecord = new Secondary_Risk_Lost_Reason__c();
            newRecord.ParentId__c = accountid;
            newRecord.Name = so.getLabel();
            newRecord.Sort_Order__c = sortOrder;

            if (first == true) {
              //  message = so.getLabel();
                Primary = so.getLabel();
                first = false;
            } else {
                message = message + ';';
                message += so.getLabel();
            }


            newRecordsList.add(newRecord);

        }
        System.debug('message ' + message);
        System.debug('newRecordsList.size ' + newRecordsList.size());
        if (newRecordsList.size() >= 0) {
            // get existing records and delete them and insert new record
            List <Secondary_Risk_Lost_Reason__c> delRecordsList = new List <Secondary_Risk_Lost_Reason__c> ();
            delRecordsList = [select id from Secondary_Risk_Lost_Reason__c where parentId__C = : accountid];
            List <Account> accTemp = [select Primary_Risk_Lost_Reason__c,Secondary_Risk_Lost_Reason__c from account where id = : accountid];
            SavePoint sp = Database.setSavePoint();
            try {
                if (delRecordsList.size() > 0) delete delRecordsList;
                if (newRecordsList.size() > 0) {
                    accTemp[0].Primary_Risk_Lost_Reason__c = Primary;
                    accTemp[0].Secondary_Risk_Lost_Reason__c=message;
                    update accTemp;
                    insert newRecordsList;

                } else if (newRecordsList.size() == 0) {
                    accTemp[0].Primary_Risk_Lost_Reason__c = '';
                    accTemp[0].Secondary_Risk_Lost_Reason__c='';
                    update accTemp;

                }


            } catch (Exception e) {
                System.Debug('An exception has occured ' + e.getLineNumber() + ' ' + e.getMessage());
                Database.Rollback(sp);
            }

        }

        return null;


    }


    public PageReference saveCase() {
        List <SelectOption> options = new List <SelectOption> ();
        System.debug('rightOptionsHidden  is ' + rightOptionsHidden);
        String message='';
        Integer sortOrder = 0;
        String[] parts = rightOptionsHidden.split('&');
        for (Integer i = 0; i < parts.size() / 2; i++) {
            options.add(new SelectOption(EncodingUtil.urlDecode(parts[i * 2], 'UTF-8'),
            EncodingUtil.urlDecode(parts[(i * 2) + 1], 'UTF-8')));
        }

        List <Case_Barrier__c> newRecordsList = new List <Case_Barrier__c> ();
        Boolean first = true;
        String Primary;
        for (SelectOption so: options) {
            sortOrder++;
            Case_Barrier__c newRecord = new Case_Barrier__c();
            newRecord.Case__c = accountid;
            newRecord.Name = so.getLabel();
            newRecord.Sort_Order_No__c = sortOrder;

            if (first == true) {
              //  message = so.getLabel();
                Primary = so.getLabel();
                first = false;
            } else {
                message = message + ';';
                message += so.getLabel();
            }

            newRecordsList.add(newRecord);

        }
        System.debug('message ' + message);
        System.debug('newRecordsList.size ' + newRecordsList.size());
        if (newRecordsList.size() >= 0) {
            // get existing records and delete them and insert new record
            List <Case_Barrier__c> delRecordsList = new List <Case_Barrier__c> ();
            delRecordsList = [select id from Case_Barrier__c where case__C = : accountid];
            List <Case> caseTemp = [select Barrier__c from  case where id = : accountid];
            SavePoint sp = Database.setSavePoint();
            try {
                if (delRecordsList.size() > 0) delete delRecordsList;
                if (newRecordsList.size() > 0) {
                    caseTemp[0].Barrier__c = message;
                    caseTemp[0].Barrier_to_Implementation__c=Primary;
                    update caseTemp;
                    insert newRecordsList;

                } else if (newRecordsList.size() == 0) {
                    caseTemp[0].Barrier__c = '';
                    caseTemp[0].Barrier_to_Implementation__c='';
                    update caseTemp;

                }


            } catch (Exception e) {
                System.Debug('An exception has occured ' + e.getLineNumber() + ' ' + e.getMessage());
                Database.Rollback(sp);
            }

        }

        return null;
    }
}