force-app/main/default/objects/Account/fields/Primary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Risk_Lost_Reason__c</fullName>
    <inlineHelpText>Select the most significant reason that puts this account at risk/lost.</inlineHelpText>
    <label>Primary Risk/Lost Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Risk_Lost_Reason__c</fullName>
    <description>If the rating is = to anything but Stable need to put in a reason why the volume is at risk or lost.</description>
    <label>Secondary Risk/Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Why_at_Risk__c.field-meta.xml
<CustomField>
    <fullName>Why_at_Risk__c</fullName>
    <description>If the rating is = to anything but Stable need to put in a reason why the volume is at risk or lost.</description>
    <label>At Risk/Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/Secondary_Risk_Lost_Reason__c.object-meta.xml
<CustomObject>
    <label>Secondary Risk/Lost Reason</label>
    <nameField>
        <label>Selected Values</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Risk/Lost Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestUpdateAccountPrimaryRiskReason.cls
@isTest

private class TestUpdateAccountPrimaryRiskReason {
 
    static testmethod void testAccountPrimaryRiskReason() {
        
        Account acc1 = new Account();
        acc1.Name = 'test Account';
        acc1.Secondary_Risk_Lost_Reason__c = 'Competition'+ ';'+'SALT Customer Service Issues' + ';' + 'SALT Product Issues'+ ';' ;
        acc1.Why_at_Risk__c = 'SALT Outcomes;Competition';
        insert acc1;
                        
        /*Account acc2 = new Account();
        acc2.Name = 'test Account2';
        acc2.Secondary_Risk_Lost_Reason__c = 'Competition';
        insert acc2;*/
        
        //List<Account> acclist = [select id,Name,Secondary_Risk_Lost_Reason__c,Primary_Risk_Lost_Reason__c from Account where id =: acc1.id OR id =: acc2.id]; 
        
            test.startTest();
            try{             
                UpdateAccountPrimaryRiskReason BatchObj1 = new UpdateAccountPrimaryRiskReason();
                ID batch_processId=Database.executebatch(BatchObj1, 2);
                system.debug('batch_processId' + batch_processId);  
                system.debug('Database.executebatch(BatchObj1, 2)' + Database.executebatch(BatchObj1, 2));  
                UpdateAccountPrimaryRiskReason m = new UpdateAccountPrimaryRiskReason ();
            }
            catch(Exception ex){}
            test.stopTest();
    
        }
    
}