force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event i.e. In person campus meeting, online meeting, conference meeting or substantive call</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RAE Name</description>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/recordTypes/M2O.recordType-meta.xml
<RecordType>
    <fullName>M2O</fullName>
    <active>true</active>
    <description>Mutually Agreed to Objectives</description>
    <label>M2O</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/StageName_Changed_Date__c.field-meta.xml
<CustomField>
    <fullName>StageName_Changed_Date__c</fullName>
    <label>StageName Changed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EventTriggerHandler.cls
public class EventTriggerHandler{
    
    public static void eventFlagCheck(List<Event> evntList){
        
        try{
            Set<String> whatIDs = new Set<String>();
            List<Event> tList = new List<Event>();
           
            for(Event e : evntList){
                if(e.whatId != null){
                    Schema.SObjectType tType = e.whatId.getSObjectType();
                    if(tType == Opportunity.Schema.SObjectType){
                        tList.add(e);
                        whatIds.add(e.WhatId);
                    }
                }
            }
            if(whatIds.size()>0){
                List<Opportunity> opplist = [SELECT Id,OwnerId,Name FROM Opportunity WHERE Id In : whatIDs];
            
                for(Event eve : tList){
                    for(integer i=0;i<oppList.size();i++){
                        if((eve.WhatId == oppList[i].Id) && (eve.OwnerId == oppList[i].OwnerId)){
                            eve.Assigned_to_Opty_Owner__c = true;
                            eve.Related_to_Opportunity__c = true;
                        }
                    }
                }
            }
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }    
    }
    
    public static void recalcSubstantiveVisitsM2O(List<Event> evntList){
    
        Id[] acctListId = new Id[]{}; 
        Id[] userListId = new Id[]{};
        Date lastYear = System.today().addYears(-1);
        
        try{
            //Filter only events that is related to Accounts & Opportunities
            for(Event e : evntList){
        
                //Minimize the # of Events to recalculate - Filter for Account, Opportunity Events
                if(e.AccountId != null && e.WhatId != null &&
                    (e.Type == 'Substantive Call' ||
                    e.Type == 'In-Person Meeting' ||
                    e.Type == 'Booth Meeting' ||
                    e.Type == 'Collateral Drop Off' ||
                    e.Type == 'Online Meeting' ||
                    e.Type == 'Conference Meeting')){
        
                    if(e.WhatId.getSObjectType() == Schema.Account.getSobjectType() 
                        || e.WhatId.getSObjectType() == Schema.Opportunity.getSobjectType()){
        
                        acctListId.add(e.AccountId);
                        userListId.add(e.OwnerId);
                    }
                }
            }
        
            //Recalculate Top Targeted Schools and Mutually Agreed to Objectives
            if(acctListId.size() > 0){ 
                    
                //CalculateSubstantiveVisits.firstRun = false;
                CalculateSubstantiveVisits.reCalcVisits(acctListId);
                List<Mutually_Agreed_to_Objectives__c> m2o = [SELECT Id 
                                                            FROM Mutually_Agreed_to_Objectives__c 
                                                            WHERE objective_plan_date__c >= :lastYear AND 
                                                                    Regional_Account_Executive__c In : userListId];
                                                                    
                Utilities.SetExecuted.add('MasterEventTrigger');                                                    
                Database.update(m2o,false);
            }
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }    
    }
    
    public static void noActivityOnOpp(List<Event> evntList){
    
        Set<ID> oppId = new Set<ID>();
        List<Opportunity> oppList = new List<Opportunity>();
        
        try{
            for(Event e : evntList){  
                if(e.Whatid !=null && e.WhatId.getSobjectType() == Schema.Opportunity.sObjectType)      
                oppId.add(e.Whatid) ;       
            }
            if(oppId.size()>0){
                for(Opportunity o : [SELECT StageName_Changed_Date__c FROM Opportunity WHERE Id In :oppId]){
                    o.StageName_Changed_Date__c = System.Today() ;
                    oppList.add(o);
                }
            }    
            if(oppList.size()>0)
                Database.update(oppList,false);    
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());    
        }
    }
}