force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event i.e. In person campus meeting, online meeting, conference meeting or substantive call</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RAE Name</description>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Top_Targeted_School__c/Top_Targeted_School__c.object-meta.xml
<CustomObject>
    <label>Top Targeted School</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top Targeted Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Top_Targeted_School__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Top Targeted Schools</relationshipLabel>
    <relationshipName>Top_Targeted_Schools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Top_Targeted_School__c/fields/Mutually_Agreed_to_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Mutually_Agreed_to_Objectives__c</fullName>
    <label>Mutually Agreed to Objectives</label>
    <referenceTo>Mutually_Agreed_to_Objectives__c</referenceTo>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Top_Targeted_School__c/fields/Substantive_Visits__c.field-meta.xml
<CustomField>
    <fullName>Substantive_Visits__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Substantive Visits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculateSubstantiveVisits.cls
public without sharing class CalculateSubstantiveVisits {
    
    public static boolean firstRun = true;

    public static void reCalcVisits(Id[] acctIdList) {

        DateTime lastYearDT = System.now().addYears(-1);

        Map<Id,Map<Date,Integer>> acctEventMap = new Map<Id,Map<Date,Integer>>();
        String[] typeOfEvents = new String[]{'Substantive Call','In-Person Meeting','Booth Meeting','Online Meeting', 'Collateral Drop Off','Conference Meeting'};

        // Select all Account & Opportunity events related to the Account
        Event[] eventList = [SELECT StartDateTime, AccountId, OwnerId 
                                FROM Event 
                                WHERE Type != null AND AccountId IN :acctIdList AND
                                        What.Type IN ('Account', 'Opportunity') AND
                                        StartDateTime >= :lastYearDT AND
                                        Type IN :typeOfEvents];


        Top_Targeted_School__c[] targetList = [SELECT Mutually_Agreed_to_Objectives__c,
                                                        Mutually_Agreed_to_Objectives__r.objective_plan_date__c,
                                                        Mutually_Agreed_to_Objectives__r.Regional_Account_Executive__c,
                                                        Account__c, 
                                                        Substantive_Visits__c
                                                FROM Top_Targeted_School__c 
                                                WHERE Account__c IN :acctIdList AND
                                                        Mutually_Agreed_to_Objectives__r.objective_plan_date__c >= :lastYearDT.date()];

        //If the objective date is after present date, it won't find the record because it only sees the last 365 days from that day

        //Loop through all events, count Events per Account, store in Map<Id,Map<Date,Integer>>
        for(Event e : eventList){

            if(acctEventMap.containsKey(e.AccountId)){

                //Check if the Account already have the a count on the month
                if(acctEventMap.get(e.AccountId).containsKey(e.StartDateTime.date().toStartOfMonth())){

                    //If the count for the month exist, increment by 1
                    acctEventMap.get(e.AccountId).put(e.StartDateTime.date().toStartOfMonth(), acctEventMap.get(e.AccountId).get(e.StartDateTime.date().toStartOfMonth()) + 1); 
                
                }else{

                    //If the count for the month exist, initialize it with 1
                    acctEventMap.get(e.AccountId).put(e.StartDateTime.date().toStartOfMonth(), 1);
                }

            } else{

                //If account doesn't it exist, initialize it with month and 1 event
                acctEventMap.put(e.AccountId, new Map<Date,Integer>{e.StartDateTime.date().toStartOfMonth() => 1});
            }

        }

        //Place all the # of Events for that Account according to the Top Target Schools records
        for(Top_Targeted_School__c t : targetList){

            t.Substantive_Visits__c = 0;

            for(Event e : eventList){

                if(e.AccountId == t.Account__c && 
                    e.OwnerId == t.Mutually_Agreed_to_Objectives__r.Regional_Account_Executive__c &&
                    e.StartDateTime.date().toStartOfMonth() == t.Mutually_Agreed_to_Objectives__r.objective_plan_date__c.toStartOfMonth()){

                    t.Substantive_Visits__c += 1;
                }
            }

        }

        update targetList;

    }
}