force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RFP_Process__c/RFP_Process__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the RFP Process for SALT opportunities.</description>
    <label>RFP Process</label>
    <nameField>
        <label>RFP Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFP Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Account__c.field-meta.xml
<CustomField>
    <fullName>RFP_Account__c</fullName>
    <inlineHelpText>This is the Account for which the RFP is being processed.</inlineHelpText>
    <label>RFP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RFP Processes</relationshipLabel>
    <relationshipName>RFP_Processes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>RFP_Due_Date__c</fullName>
    <label>RFP Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>RFP_Received_Date__c</fullName>
    <label>RFP Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Status__c.field-meta.xml
<CustomField>
    <fullName>RFP_Status__c</fullName>
    <label>RFP Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Receipt of the Request for RFP</fullName>
            </value>
            <value>
                <fullName>Approval to Respond to RFP</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Response to RFP Sent</fullName>
            </value>
            <value>
                <fullName>Invited to Participate in 2nd Round</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Type__c.field-meta.xml
<CustomField>
    <fullName>RFP_Type__c</fullName>
    <label>RFP Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reactive</fullName>
            </value>
            <value>
                <fullName>Proactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Value__c.field-meta.xml
<CustomField>
    <fullName>RFP_Value__c</fullName>
    <description>Estimated value of proposal.</description>
    <label>RFP Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FscYrResultsController.cls
public class FscYrResultsController{
    
    public List<RFP_Process__c> rfpList{get;set;}
    public FscYrResultsController(ApexPages.StandardController controller) {
        rfpList = new List<RFP_Process__c>();
        Annual_Sales_Plan__c asp = (Annual_Sales_Plan__c)controller.getRecord();
        asp = [SELECT ID,OwnerID,Start_Date__c,End_Date__c FROM Annual_Sales_Plan__c WHERE ID =:asp.id];
        List<RFP_Process__c> rfpListNew = [Select RFP_Account__c,RFP_Account__r.Name,RFP_Type__c,RFP_Due_Date__c,RFP_Status__c,RFP_Value__c,RFP_Received_Date__c From RFP_Process__c Where RFP_Account__r.Regional_Account_Executive__c =: asp.OwnerId];
        for(RFP_Process__c rftTemp : rfpListNew){
            if(rftTemp.RFP_Due_Date__c!=null){
                if(rftTemp.RFP_Due_Date__c >= asp.Start_Date__c && rftTemp.RFP_Due_Date__c <= asp.End_Date__c ){
                   rfpList.add(rftTemp);
                }
            }else if(rftTemp.RFP_Received_Date__c!=null){
                if(rftTemp.RFP_Received_Date__c >= asp.Start_Date__c && rftTemp.RFP_Received_Date__c <= asp.End_Date__c){
                    rfpList.add(rftTemp);
                }
            }else{
                rfpList.add(rftTemp);
            }
        }
    }
}