force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Number_of_Expected_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expected_Contracts__c</fullName>
    <label>Number of Expected Contracts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RAE Name</description>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Targeted_Substantive_Visits_for_Month__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Substantive_Visits_for_Month__c</fullName>
    <description>Please put in the target number of substantive visits</description>
    <label>Targeted Substantive Visits for Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/recordTypes/M2O.recordType-meta.xml
<RecordType>
    <fullName>M2O</fullName>
    <active>true</active>
    <description>Mutually Agreed to Objectives</description>
    <label>M2O</label>
</RecordType>

force-app/main/default/objects/Top_Targeted_School__c/Top_Targeted_School__c.object-meta.xml
<CustomObject>
    <label>Top Targeted School</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Top Targeted Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Top_Targeted_School__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Top Targeted Schools</relationshipLabel>
    <relationshipName>Top_Targeted_Schools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Top_Targeted_School__c/fields/Mutually_Agreed_to_Objectives__c.field-meta.xml
<CustomField>
    <fullName>Mutually_Agreed_to_Objectives__c</fullName>
    <label>Mutually Agreed to Objectives</label>
    <referenceTo>Mutually_Agreed_to_Objectives__c</referenceTo>
    <relationshipName>Visits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestNewTopTargetedClientController.cls
/*
@Name                : TestNewTopTargetedClientController 
@Author              : GS Dev Team
@Date                : January 12, 2016
@Description         : Test class for NewTopTargetedClientController class
*/ 

@isTest

private class TestNewTopTargetedClientController{

    static testMethod void NewTopTargetedClientTest() {
        
        Test.startTest();
        //user test data
        User u = [SELECT Id FROM User WHERE isActive = true LIMIT 1];
        
        //m2o test data
        Mutually_Agreed_to_Objectives__c m2o1 = new Mutually_Agreed_to_Objectives__c();
        m2o1.Name = 'test m2o1';
        m2o1.Regional_Manager__c = u.Id;
        m2o1.objective_plan_date__c = Date.parse('1/1/2016');
        m2o1.Targeted_Substantive_Visits_for_Month__c = 10;
        m2o1.Number_of_Expected_Contracts__c = 10;
        m2o1.Regional_Account_Executive__c = u.id;
        insert m2o1;
        
        //account test data
        Account acc1 = new Account(name='test acc1');
        insert acc1;
        
        Account acc2 = new Account(name='test acc2');
        insert acc2;
        
        Account acc3 = new Account(name='test acc3');
        insert acc3;
        
        Account acc4 = new Account(name='test acc4');
        insert acc4;
        
        //Without top target records test
        ApexPages.StandardController sc2 = new ApexPages.StandardController(m2o1);
        NewTopTargetedClientController newTtcController2 = new NewTopTargetedClientController(sc2);
        
        //new button test
        newTtcController2.showTtcRelatedlist = 'false';
        newTtcController2.prepareTopTargetList();
        
        //cancel button test
        newTtcController2.showTtcRelatedlist = 'true';
        newTtcController2.prepareTopTargetList();
        
        //new button and save test
        newTtcController2.showTtcRelatedlist = 'false';
        newTtcController2.prepareTopTargetList();
        newTtcController2.addRows();
        for(NewTopTargetedClientController.TopTargetedWrapper tmp : newTtcController2.listTopTargeted){
            if(tmp.index=='1'){
                tmp.tts.Account__c = acc4.Id;
            }
        }
        
        //fail save with 3 account validation
        newTtcController2.saveTargetClient();
        
        //Top_Targeted_School__c test data
        Top_Targeted_School__c target1 = new Top_Targeted_School__c();
        target1.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target1.Account__c = acc1.Id; 
        insert target1;
        
        Top_Targeted_School__c target2 = new Top_Targeted_School__c();
        target2.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target2.Account__c = acc2.Id; 
        insert target2;
        
        Top_Targeted_School__c target3= new Top_Targeted_School__c();
        target3.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target3.Account__c = acc3.Id; 
        insert target3;
        
        
        PageReference pageRef = Page.NewTopTargetedClient;
        Test.setCurrentPage(pageRef);
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(m2o1);
        NewTopTargetedClientController newTtcController = new NewTopTargetedClientController(sc);
        
        //new button test
        newTtcController.showTtcRelatedlist = 'false';
        newTtcController.prepareTopTargetList();
        
        //cancel button test
        newTtcController.showTtcRelatedlist = 'true';
        newTtcController.prepareTopTargetList();
        
        //new button and save test
        newTtcController.showTtcRelatedlist = 'false';
        newTtcController.prepareTopTargetList();
        newTtcController.addRows();
        for(NewTopTargetedClientController.TopTargetedWrapper tmp : newTtcController.listTopTargeted){
            if(tmp.index=='4'){
                tmp.tts.Account__c = acc4.Id;
            }
            if(tmp.index=='5'){
                tmp.tts.Account__c = acc4.Id;
            }
        }
        
        //fail save with unique account validation
        newTtcController.saveTargetClient();
        
        for(NewTopTargetedClientController.TopTargetedWrapper tmp : newTtcController.listTopTargeted){
            if(tmp.index=='4'){
                tmp.tts.Account__c = acc4.Id;
            }
            if(tmp.index=='5'){
                tmp.tts.Account__c = null;
            }
        }
        
        //save exception test
        newTtcController.saveTargetClient();
        
        ApexPages.currentPage().getParameters().put('id',m2o1.id);
        //save test
        newTtcController.saveTargetClient();
        
        Test.stopTest();
    }
    
    static testMethod void NewTopTargetedClientTest2() {
        
        Test.startTest();
        //user test data
        User u = [SELECT Id FROM User WHERE isActive = true LIMIT 1];
        
        //m2o test data
        Mutually_Agreed_to_Objectives__c m2o1 = new Mutually_Agreed_to_Objectives__c();
        m2o1.Name = 'test m2o1';
        m2o1.Regional_Manager__c = u.Id;
        m2o1.objective_plan_date__c = Date.parse('1/1/2016');
        m2o1.Targeted_Substantive_Visits_for_Month__c = 10;
        m2o1.Number_of_Expected_Contracts__c = 10;
        m2o1.Regional_Account_Executive__c = u.id;
        insert m2o1;
        
        //account test data
        Account acc1 = new Account(name='test acc1');
        insert acc1;
        
        Account acc2 = new Account(name='test acc2');
        insert acc2;
        
        Account acc3 = new Account(name='test acc3');
        insert acc3;
        
        Account acc4 = new Account(name='test acc4');
        insert acc4;
        
        //Top_Targeted_School__c test data
        Top_Targeted_School__c target1 = new Top_Targeted_School__c();
        target1.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target1.Account__c = acc1.Id; 
        insert target1;
        
        Top_Targeted_School__c target2 = new Top_Targeted_School__c();
        target2.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target2.Account__c = acc2.Id; 
        insert target2;
        
        Top_Targeted_School__c target3= new Top_Targeted_School__c();
        target3.Mutually_Agreed_to_Objectives__c = m2o1.Id; 
        target3.Account__c = acc3.Id; 
        insert target3;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(m2o1);
        NewTopTargetedClientController newTtcController = new NewTopTargetedClientController(sc);
        
        //new button test
        newTtcController.showTtcRelatedlist = 'true';
        newTtcController.prepareTopTargetList();
        newTtcController.addRows();
        for(NewTopTargetedClientController.TopTargetedWrapper tmp : newTtcController.listTopTargeted){
            if(tmp.index=='4'){
                tmp.tts.Account__c = acc4.Id;
            }
        }
        //remove rows test
        newTtcController.numberOfRowToRemove = target1.Id;
        newTtcController.removeRows();
        newTtcController.saveTargetClient();
        
        Test.stopTest();
    }
}