force-app/main/default/objects/Account/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the name of the Business Development Regional Account Executive for this account.</description>
    <inlineHelpText>This field contains the name of the Business Development Regional Account Executive for this account.</inlineHelpText>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RFP_Process__c/RFP_Process__c.object-meta.xml
<CustomObject>
    <description>This object is used to track the RFP Process for SALT opportunities.</description>
    <label>RFP Process</label>
    <nameField>
        <label>RFP Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFP Processes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Account__c.field-meta.xml
<CustomField>
    <fullName>RFP_Account__c</fullName>
    <inlineHelpText>This is the Account for which the RFP is being processed.</inlineHelpText>
    <label>RFP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RFP Processes</relationshipLabel>
    <relationshipName>RFP_Processes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RFP_Process__c/fields/RFP_Value__c.field-meta.xml
<CustomField>
    <fullName>RFP_Value__c</fullName>
    <description>Estimated value of proposal.</description>
    <label>RFP Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestFscYrResultsController.cls
@isTest
private class TestFscYrResultsController {
    static testMethod void validateFscYrResultsController(){
       
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='stsyuser@sfdc.com');
                                                      
            insert u;
                              
            Account acc = new Account(Name = 'Test Acc', Regional_Account_Executive__c =u.id);
            insert acc;
    
            Annual_Sales_Plan__c ann  = new Annual_Sales_Plan__c (Name='BusDev Plan FY2017 DTeam@GS',OwnerId = u.Id);
            insert ann;
            
            RFP_Process__c rfp= new RFP_Process__c(Name='Test',RFP_Account__c=acc.id,RFP_Value__c=200.00);
            insert rfp;
          
    
            
            ApexPages.StandardController apsc = new ApexPages.StandardController(ann);
            FscYrResultsController fsc =  new FscYrResultsController(apsc);
        }
        
    }
}