force-app/main/default/objects/Account/fields/Secondary_Risk_Lost_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Risk_Lost_Reason__c</fullName>
    <description>If the rating is = to anything but Stable need to put in a reason why the volume is at risk or lost.</description>
    <label>Secondary Risk/Lost Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Staff Changes</fullName>
            </value>
            <value>
                <fullName>Competition</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>SALT Customer Service Issues</fullName>
            </value>
            <value>
                <fullName>SALT Outcomes</fullName>
            </value>
            <value>
                <fullName>SALT Product Issues</fullName>
            </value>
            <value>
                <fullName>Unresponsive Staff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/Secondary_Risk_Lost_Reason__c.object-meta.xml
<CustomObject>
    <label>Secondary Risk/Lost Reason</label>
    <nameField>
        <label>Selected Values</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Risk/Lost Reasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Secondary_Risk_Lost_Reason__c/fields/ParentId__c.field-meta.xml
<CustomField>
    <fullName>ParentId__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Secondary Risk/Lost Reasons</relationshipLabel>
    <relationshipName>Secondary_Risk_Lost_Reasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SecondaryRisk__c/SecondaryRisk__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Secondary Risk Values</description>
    <label>Secondary Risk</label>
</CustomObject>

force-app/main/default/classes/AccountRiskReasonsController.cls
public class AccountRiskReasonsController {

    public SelectOption[] selectedRisks { get; set;}
    public SelectOption[] allRisks { get; set;}
    public String id;
    public String outputMessage {
        get {
            IF(outputMessage.length()> 100) outputMessage = outputMessage.subString(0, 100) + '...';

            return outputMessage;
        }
        set;
    }
    public Boolean show { get; set;}
    public Boolean showLink { get; set;}
    public String url { get; set;}

    public AccountRiskReasonsController(ApexPages.StandardController controller) {
        outputMessage = '';
        url = '/apex/MultiPickList?id=' + account.id;
        Boolean fTime = false;
        String url = ApexPages.currentPage().getUrl();
        System.debug('url ' + url);
        id = Apexpages.currentPage().getParameters().get('id'); // Account Id

        if (id != null) {
           

            selectedRisks = new List <SelectOption> ();

            List <String> risks = generateList([SELECT Name, id FROM SecondaryRisk__c]);
            List <String> riskByAccount = generateList([select name from Secondary_Risk_Lost_Reason__c where parentId__C = : id order by sort_Order__C ASC ]);


            //create set to remove selected element
            Set <String> setRisks = new Set <String> ();
            setRisks.addAll(risks);

            Set <String> setRiskByAccount = new Set <String> ();
            setRiskByAccount.addAll(riskByAccount);
            
            
            setRisks.removeAll(setRiskByAccount);
           
         
            

            allRisks = new List <SelectOption> ();
            for (String c: setRisks) {
                allRisks.add(new SelectOption(c, c));
            }
           
            for (String c: setRiskByAccount) {
                selectedRisks.add(new SelectOption(c, c));
            }
           
            
            List <Secondary_Risk_Lost_Reason__c> tempList = [select id, name from Secondary_Risk_Lost_Reason__c where parentId__C = : id order by sort_Order__C ASC];
            for (Secondary_Risk_Lost_Reason__c scTemp: tempList) {
                if (fTime == false) {
                    outputMessage = scTemp.name;
                    fTime = true;
                } else {
                    outputMessage += ';' + scTemp.name;
                }

            }
            System.debug('outputMessage is ' + outputMessage);
            System.debug('outputMessage is ' + outputMessage.length());
            if (outputMessage.length() == 0) {
                show = False;
                showLink = true;
                outputMessage = 'Select Risk Reasons';
            } else {
                show = true;
                showLink = False;
            }
        }
    }

    private List <String> generateList(List <sobject> sobj) {
        List <String> retStr = new List <String> ();

        for (sobject sTemp: sobj) {
            if (sTemp.getSObjectType() == Secondary_Risk_Lost_Reason__c.sObjectType) {
                sTemp = (Secondary_Risk_Lost_Reason__c) sTemp;
            } else if (sTemp.getSObjectType() == SecondaryRisk__c.sObjectType) {
                sTemp = (SecondaryRisk__c) sTemp;
            }

            retStr.add(String.valueOf(sTemp.get('Name')));
        }
        return retStr;
    }

}