force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Annual_Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Sales Plan</label>
    <referenceTo>Annual_Sales_Plan__c</referenceTo>
    <relationshipLabel>Mutually Agreed to Objectives</relationshipLabel>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Number_of_Expected_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expected_Contracts__c</fullName>
    <label>Number of Expected Contracts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Account_Executive__c.field-meta.xml
<CustomField>
    <fullName>Regional_Account_Executive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>RAE Name</description>
    <label>Regional Account Executive</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Targeted_Substantive_Visits_for_Month__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Substantive_Visits_for_Month__c</fullName>
    <description>Please put in the target number of substantive visits</description>
    <label>Targeted Substantive Visits for Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestvalidateM20ForASPFiscalYear.cls
@isTest
private class TestvalidateM20ForASPFiscalYear {
    static testmethod void validateM20ForASPFiscalYear() {
    
        Datetime myDateTime1 = Datetime.newInstance(2017, 07, 01);
        Datetime myDateTime2 = Datetime.newInstance(2019, 06, 30);
        
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com');
            
        Annual_Sales_Plan__c asp = new Annual_Sales_Plan__c(Name='BusDev Plan FY2018 DTeam@GS',Start_Date__c = myDateTime1.date(),End_Date__c = myDateTime2.date());
        insert asp;
           
        Mutually_Agreed_to_Objectives__c mutualObj =  new Mutually_Agreed_to_Objectives__c();
        mutualObj.Name='Test M20 2';
        mutualObj.Targeted_Substantive_Visits_for_Month__c = 12;
        mutualObj.Number_of_Expected_Contracts__c = 10;
        mutualObj.objective_plan_date__c= system.today();
        mutualObj.Regional_Account_Executive__c=u.id;
        mutualObj.Annual_Sales_Plan__c= asp.id;
        insert mutualObj;
                
        Annual_Sales_Plan__c asp1 = new Annual_Sales_Plan__c(Name='BusDev Plan FY2018 DTeam@GS',Start_Date__c = System.today(),End_Date__c = System.today().addmonths(7));
        insert asp1;
        
        try{
            mutualObj.Annual_Sales_Plan__c= asp1.id;
            update mutualObj;
        }
        catch(Exception e){
        }
        
     }
}