force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Annual_Sales_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Event i.e. In person campus meeting, online meeting, conference meeting or substantive call</description>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Annual_Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Annual Sales Plan</label>
    <referenceTo>Annual_Sales_Plan__c</referenceTo>
    <relationshipLabel>Mutually Agreed to Objectives</relationshipLabel>
    <relationshipName>Mutually_Agreed_to_Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Number_of_Expected_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expected_Contracts__c</fullName>
    <label>Number of Expected Contracts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Targeted_Substantive_Visits_for_Month__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Substantive_Visits_for_Month__c</fullName>
    <description>Please put in the target number of substantive visits</description>
    <label>Targeted Substantive Visits for Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/recordTypes/M2O.recordType-meta.xml
<RecordType>
    <fullName>M2O</fullName>
    <active>true</active>
    <description>Mutually Agreed to Objectives</description>
    <label>M2O</label>
</RecordType>

force-app/main/default/classes/TestUpdateInPersonMeetings.cls
@isTest
public class TestUpdateInPersonMeetings {
    static testMethod void updateMeetingsTest()
    {
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs (thisUser) {
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                              LocaleSidKey='en_US', ProfileId = p.Id, 
                              TimeZoneSidKey='America/Los_Angeles', UserName='stsyuser@sfdc.com');
            insert u;
            
            Account acc = new Account(Name = 'Test Acc', OwnerId = u.Id);
            insert acc;
            
            Event evnt1 = new Event(OwnerId=u.Id, Type='In-Person Meeting', StartDateTime=System.today(), EndDateTime=System.Today()+5, Subject= 'describe event',WhatId = acc.Id);
            insert evnt1;
            
            Annual_Sales_Plan__c asp = new Annual_Sales_Plan__c(Name = 'Test asp');
            insert asp;
            
            Mutually_Agreed_to_Objectives__c m2o1 = new Mutually_Agreed_to_Objectives__c(Name = 'm2o test1', Regional_Manager__c = u.Id, objective_plan_date__c = System.today(),Targeted_Substantive_Visits_for_Month__c= 10,Number_of_Expected_Contracts__c = 10,Annual_Sales_Plan__c=asp.Id);
            insert m2o1;
            
            delete m2o1;
        }  
    }
}