force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/Annual_Sales_Plan_Items__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan Items</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Annual Sales Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Aggregators_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Aggregators_Status_Update__c</fullName>
    <label>Aggregators Status Update</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Annual_Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Plan__c</fullName>
    <label>Annual Sales Plan</label>
    <referenceTo>Annual_Sales_Plan__c</referenceTo>
    <relationshipName>Proposed_Conference_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Approved_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Approved_Aggregator_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Aggregator Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Association</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Aggregator</value>
        </filterItems>
        <filterItems>
            <field>Account.Approved__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items (Approved Aggregator Name)</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Attending__c.field-meta.xml
<CustomField>
    <fullName>Attending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/of_Targets_in_Territory__c.field-meta.xml
<CustomField>
    <fullName>of_Targets_in_Territory__c</fullName>
    <label># of Targeted Schools in Territory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Aggregator_Name__c</fullName>
    <label>Target Aggregator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_ESSS_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Target_ESSS_Status_Update__c</fullName>
    <label>Target ESSS Status Update</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting signed contract</fullName>
            </value>
            <value>
                <fullName>Providing Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Total_Enrollments__c</fullName>
    <label>Total Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Membership__c.field-meta.xml
<CustomField>
    <fullName>Total_Membership__c</fullName>
    <label>Total Membership</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TargetAggController.cls
public with sharing class TargetAggController {

    public Annual_Sales_Plan__c asp { get; set; }
    public String showPCARelatedlist {get; set;}
    public String numberOfRowToRemove { get; set; }
    public List<PCAWrapper> listPCA {get; set;}
    public List<Annual_Sales_Plan_Items__c> pcaToBeDelList;

    public TargetAggController (ApexPages.StandardController sc) {
        if(sc != null && sc.getId() != null){
            asp = [Select Id,Name,(Select Id,Name,Annual_Sales_Plan__c,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,School_Name__c,Total_Enrollments__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r Where Target_Aggregator_Name__c != null) From Annual_Sales_Plan__c Where Id =: sc.getId()];
            showPCARelatedlist = 'true';
            preparePCAList();
        }
    }
    public void addRows(){
        PCAWrapper wrapper = new PCAWrapper();
        wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
        listPCA.add(wrapper);
    }
    public void removeRows(){
        List<PCAWrapper> pcawTemp = new List<PCAWrapper>();
        for(PCAWrapper pcaw : listPCA){
            if(pcaw.pca.Id == numberOfRowToRemove){
               pcaToBeDelList.add(pcaw.pca); 
            }
            else {
                pcawTemp.add(pcaw);
            }
        }
        listPCA = new List<PCAWrapper>();
        listPCA = pcawTemp;
    }
    
    public void saveTargetAgg() {
        try{
            List<Annual_Sales_Plan_Items__c> targetAggregatorsList = new List<Annual_Sales_Plan_Items__c>();
            
            for(PCAWrapper pcawTemp : listPCA) {
                if(pcawTemp.pca.Id==null && pcawTemp.pca.Target_Aggregator_Name__c != null){
                    targetAggregatorsList.add(pcawTemp.pca);    
                }else if(pcawTemp.pca.Id!=null){
                    targetAggregatorsList.add(pcawTemp.pca);    
                }
                if(pcawTemp.pca.Target_Aggregator_Name__c == null && (pcawTemp.pca.Total_Membership__c != null || pcawTemp.pca.of_Targets_in_Territory__c != null || pcawTemp.pca.Aggregators_Status_Update__c != null)) {
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'You must enter Target Aggregator Name'));
                    return;
                }
            }    
            upsert targetAggregatorsList;           
            delete pcaToBeDelList;
            asp = [Select Id,Name,(Select Id,Name,Annual_Sales_Plan__c,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,School_Name__c,Total_Enrollments__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r Where Target_Aggregator_Name__c != null) From Annual_Sales_Plan__c Where Id =: ApexPages.currentPage().getParameters().get('id')];
            showPCARelatedlist = 'true';
            preparePCAList();
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
    
    public void preparePCAList(){
        pcaToBeDelList = new List<Annual_Sales_Plan_Items__c>();
        listPCA = new List<PCAWrapper>();
            
        for(Integer i = 1; i<=asp.Proposed_Conference_Attendance__r.size(); i++){
            PCAWrapper wrapper = new PCAWrapper();
            wrapper.pca = asp.Proposed_Conference_Attendance__r[i-1];
            listPCA.add(wrapper) ;
        }
        if(showPCARelatedlist!='true'){
            PCAWrapper wrapper = new PCAWrapper();
            wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
            listPCA.add(wrapper) ;   
        }
    }
    
    public class PCAWrapper{
        public Annual_Sales_Plan_Items__c pca {get; set;}
    }
}