force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/Annual_Sales_Plan_Items__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan Items</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Annual Sales Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Aggregators_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Aggregators_Status_Update__c</fullName>
    <label>Aggregators Status Update</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Annual_Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Plan__c</fullName>
    <label>Annual Sales Plan</label>
    <referenceTo>Annual_Sales_Plan__c</referenceTo>
    <relationshipName>Proposed_Conference_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Approved_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Approved_Aggregator_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Aggregator Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Association</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Aggregator</value>
        </filterItems>
        <filterItems>
            <field>Account.Approved__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items (Approved Aggregator Name)</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Attending__c.field-meta.xml
<CustomField>
    <fullName>Attending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/of_Targets_in_Territory__c.field-meta.xml
<CustomField>
    <fullName>of_Targets_in_Territory__c</fullName>
    <label># of Targeted Schools in Territory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Annual Sales Plan Items</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Aggregator_Name__c</fullName>
    <label>Target Aggregator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_ESSS_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Target_ESSS_Status_Update__c</fullName>
    <label>Target ESSS Status Update</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting signed contract</fullName>
            </value>
            <value>
                <fullName>Providing Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_Record__c.field-meta.xml
<CustomField>
    <fullName>Target_Record__c</fullName>
    <label>Target Record</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Target ESSS Schools</fullName>
            </value>
            <value>
                <fullName>Target School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Total_Enrollments__c</fullName>
    <label>Total Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Membership__c.field-meta.xml
<CustomField>
    <fullName>Total_Membership__c</fullName>
    <label>Total Membership</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TargetESSSController.cls
public with sharing class TargetESSSController {

    public Annual_Sales_Plan__c asp { get; set; }
    public String showPCARelatedlist {get; set;}
    public String numberOfRowToRemove { get; set; }
    public List<PCAWrapper> listPCA {get; set;}
    public String selAccId{get;set;}
    public String selIndex{get;set;}
    public List<Annual_Sales_Plan_Items__c> pcaToBeDelList;
    Date startDate;
    Date endDate;

    public TargetESSSController(ApexPages.StandardController sc) {
        if(sc != null && sc.getId() != null){
            asp = [Select Id,Name,Start_Date__c,End_Date__c,(Select Id,Name,Opportunity__c,Opportunity__r.Name,Opportunity__r.StageName,Annual_Sales_Plan__c,CreatedDate,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,School_Name__c,School_Name__r.Name,Total_Enrollments__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r Where School_Name__c != null AND Target_Record__c = 'Target ESSS Schools') From Annual_Sales_Plan__c Where Id =: sc.getId()];
            startDate = asp.Start_Date__c;
            endDate = asp.End_Date__c;
            showPCARelatedlist = 'true';
            preparePCAList();
        }
    }
    public void addRows(){
        PCAWrapper wrapper = new PCAWrapper();
        wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
        wrapper.index = listPCA.size();
        wrapper.oppList = new List<SelectOption>();
        listPCA.add(wrapper);
    }
    public void removeRows(){
        List<PCAWrapper> pcawTemp = new List<PCAWrapper>();
        for(PCAWrapper pcaw : listPCA){
            if(pcaw.pca.Id == numberOfRowToRemove){
               pcaToBeDelList.add(pcaw.pca); 
            }
            else {
                pcawTemp.add(pcaw);
            }
        }
        listPCA = new List<PCAWrapper>();
        listPCA = pcawTemp;
    }
    
    public void saveTargetESSS() {
        try{
            List<Annual_Sales_Plan_Items__c> targetESSSList = new List<Annual_Sales_Plan_Items__c>(); 
            
            for(PCAWrapper pcawTemp : listPCA) {
                if(pcawTemp.pca.Id==null && pcawTemp.pca.School_Name__c != null){
                    pcawTemp.pca.Target_Record__c = 'Target ESSS Schools';
                    pcawTemp.pca.Opportunity__c = pcawTemp.selOppId;
                    targetESSSList.add(pcawTemp.pca);   
                } else if(pcawTemp.pca.Id!=null){
                    pcawTemp.pca.Opportunity__c = pcawTemp.selOppId;
                    targetESSSList.add(pcawTemp.pca);
                }
               
            }    
            upsert targetESSSList;
            
            delete pcaToBeDelList;
            asp = [Select Id,Name,(Select Id,Name,Opportunity__c,Opportunity__r.Name,Opportunity__r.StageName,Annual_Sales_Plan__c,CreatedDate,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,School_Name__c,School_Name__r.Name,Total_Enrollments__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r where School_Name__c != null AND Target_Record__c = 'Target ESSS Schools') From Annual_Sales_Plan__c Where Id =: ApexPages.currentPage().getParameters().get('id')];
            showPCARelatedlist = 'true';
            preparePCAList();
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
    
    public void preparePCAList(){
        pcaToBeDelList = new List<Annual_Sales_Plan_Items__c>();
        listPCA = new List<PCAWrapper>();
        
        Set<Id> accAspIds = new Set<Id>();
        for(Annual_Sales_Plan_Items__c a : asp.Proposed_Conference_Attendance__r){
            accAspIds.add(a.School_Name__c);
        }
        
        Map<Id,List<Opportunity>> accOppMap = new Map<Id,List<Opportunity>>();
        List<Opportunity> oppList = [Select Id,Name,AccountId From Opportunity Where AccountId IN :accAspIds AND CloseDate >=: startDate AND CloseDate <=: endDate];
        for(Opportunity o : oppList){
            if(!accOppMap.containsKey(o.AccountId)){accOppMap.put(o.AccountId,new List<Opportunity>());}
            accOppMap.get(o.AccountId).add(o);
        }
        
        Integer count = 0;    
        for(Integer i = 1; i<=asp.Proposed_Conference_Attendance__r.size(); i++){
            PCAWrapper wrapper = new PCAWrapper();
            wrapper.pca = asp.Proposed_Conference_Attendance__r[i-1];
            wrapper.index = count;
            wrapper.oppList = new List<SelectOption>();
            wrapper.oppList.add(new SelectOption ('','--None--'));
            
            if(accOppMap.containsKey(wrapper.pca.School_Name__c)){
                for(Opportunity opp : accOppMap.get(wrapper.pca.School_Name__c)){
                    wrapper.oppList.add(new SelectOption (opp.Id,opp.Name));
                }
            }
            wrapper.selOppId = wrapper.pca.Opportunity__c;
            listPCA.add(wrapper) ;
            count++;
        }
        if(showPCARelatedlist!='true'){
            PCAWrapper wrapper = new PCAWrapper();
            wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
            wrapper.index = count;
            wrapper.oppList = new List<SelectOption>();
            listPCA.add(wrapper) ; 
            count++;  
        }
        for(PCAWrapper fqNew : listPCA){
            if(fqNew.pca.CreatedDate >= startDate && fqNew.pca.CreatedDate <= startDate.addMonths(3)){
                fqNew.fiscalQuarter = 'Q1';
            }
            if(fqNew.pca.CreatedDate >= startDate.addMonths(3) && fqNew.pca.CreatedDate <= startDate.addMonths(6)){
                fqNew.fiscalQuarter = 'Q2';
            }
            if(fqNew.pca.CreatedDate >= startDate.addMonths(6) && fqNew.pca.CreatedDate <= startDate.addMonths(9)){fqNew.fiscalQuarter = 'Q3';}
            if(fqNew.pca.CreatedDate >= startDate.addMonths(9) && fqNew.pca.CreatedDate <= startDate.addMonths(12)){fqNew.fiscalQuarter = 'Q4';}
        }
    }
    
    public void retrieveOpps(){
        List<Opportunity> oppLst = [Select Id,Name From Opportunity Where AccountId = :selAccId AND CloseDate >=: startDate AND CloseDate <=: endDate Order By Name ASC];
        for(PCAWrapper w : listPCA){
            if(Integer.valueOf(selIndex) == w.index){
                w.oppList = new List<SelectOption>();
                w.oppList.add(new SelectOption ('','--None--'));
                for(Opportunity o : oppLst){
                    w.oppList.add(new SelectOption(o.Id,o.Name));
                }
            }
        }
    }
    
    public class PCAWrapper{
        public Annual_Sales_Plan_Items__c pca {get; set;}
        public String fiscalQuarter {get;set;}
        public String selOppId {get;set;}
        public List<SelectOption> oppList{get;set;}
        public Integer index {get;set;}
    }
}