force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <description>Please place the fiscal year of this opportunity</description>
    <label>Fiscal Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_in_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Total_in_Enrollment__c</fullName>
    <inlineHelpText>Complete this field if the number estimated to receive Education Debt Management is different from the Total # in Enrollment.</inlineHelpText>
    <label>Total # in Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuarterlyResultsController.cls
public class QuarterlyResultsController{

    public List<FQWrapper> listFQWrapper {get; set;}
    Period p = [Select StartDate, EndDate From Period Where type = 'Year' and StartDate = THIS_FISCAL_YEAR];
    
    public QuarterlyResultsController(ApexPages.StandardController controller) {
        Annual_Sales_Plan__c asp = (Annual_Sales_Plan__c)controller.getRecord();
        asp = [SELECT ID,OwnerID,Start_Date__c,End_Date__c FROM Annual_Sales_Plan__c WHERE ID =:asp.id];
        List<Opportunity> opps = [Select Id,Name,Total_in_Enrollment__c,CloseDate,StageName,Fiscal_Year__c From Opportunity Where (StageName = 'Implementation' OR StageName = 'In Production' OR StageName = 'Verbal Committment' OR StageName = 'Closed - Won') AND CloseDate >=: asp.Start_Date__c AND CloseDate <=: asp.End_Date__c AND OwnerId =:asp.OwnerId];
        listFQWrapper = new List<FQWrapper>();
        
        for(Opportunity opp : opps){
            FQWrapper fqNew = new FQWrapper();
            fqNew.oppFQ = opp ;
            if(opp.CloseDate >= asp.Start_Date__c && opp.CloseDate <= asp.Start_Date__c.addMonths(3)){
                fqNew.fiscalQuarter = 'Q1';
            }
            if(opp.CloseDate >= asp.Start_Date__c.addMonths(3) && opp.CloseDate <= asp.Start_Date__c.addMonths(6)){
                fqNew.fiscalQuarter = 'Q2';
            }
            if(opp.CloseDate >= asp.Start_Date__c.addMonths(6) && opp.CloseDate <= asp.Start_Date__c.addMonths(9)){
                fqNew.fiscalQuarter = 'Q3';
            }
            if(opp.CloseDate >= asp.Start_Date__c.addMonths(9) && opp.CloseDate <= asp.Start_Date__c.addMonths(12)){
                fqNew.fiscalQuarter = 'Q4';
            }
            listFQWrapper.add(fqNew);
        }
    }
    
    public class FQWrapper{
        public Opportunity oppFQ {get;set;}
        public String fiscalQuarter {get;set;}      
    }
}