force-app/main/default/objects/Annual_Sales_Plan__c/Annual_Sales_Plan__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan</label>
    <nameField>
        <label>Annual Sales Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Annual Sales Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/Annual_Sales_Plan_Items__c.object-meta.xml
<CustomObject>
    <label>Annual Sales Plan Items</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Annual Sales Plan Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Sales Plan Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Aggregators_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Aggregators_Status_Update__c</fullName>
    <label>Aggregators Status Update</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Annual_Sales_Plan__c.field-meta.xml
<CustomField>
    <fullName>Annual_Sales_Plan__c</fullName>
    <label>Annual Sales Plan</label>
    <referenceTo>Annual_Sales_Plan__c</referenceTo>
    <relationshipName>Proposed_Conference_Attendance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Approved_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Approved_Aggregator_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved Aggregator Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Association</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Aggregator</value>
        </filterItems>
        <filterItems>
            <field>Account.Approved__c</field>
            <operation>equals</operation>
            <value>Yes</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items (Approved Aggregator Name)</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Attending__c.field-meta.xml
<CustomField>
    <fullName>Attending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attending</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Advancement</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Career Services</fullName>
            </value>
            <value>
                <fullName>Enrollment Management</fullName>
            </value>
            <value>
                <fullName>Financial Aid</fullName>
            </value>
            <value>
                <fullName>Registrar</fullName>
            </value>
            <value>
                <fullName>Student Life</fullName>
            </value>
            <value>
                <fullName>Veterans Affairs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Conference_Name_Presentation_Proposed__c.field-meta.xml
<CustomField>
    <fullName>Conference_Name_Presentation_Proposed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conference Name/Presentation Proposed</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Conference</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Annual Sales Plan Items</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/of_Targets_in_Territory__c.field-meta.xml
<CustomField>
    <fullName>of_Targets_in_Territory__c</fullName>
    <label># of Targeted Schools in Territory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/PCA_Record__c.field-meta.xml
<CustomField>
    <fullName>PCA_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PCA Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Presenting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Proposed__c.field-meta.xml
<CustomField>
    <fullName>Proposed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proposed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Annual Sales Plan Items</relationshipLabel>
    <relationshipName>Annual_Sales_Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_Aggregator_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Aggregator_Name__c</fullName>
    <label>Target Aggregator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Target_ESSS_Status_Update__c.field-meta.xml
<CustomField>
    <fullName>Target_ESSS_Status_Update__c</fullName>
    <label>Target ESSS Status Update</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting signed contract</fullName>
            </value>
            <value>
                <fullName>Providing Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Total_Enrollments__c</fullName>
    <label>Total Enrollment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Sales_Plan_Items__c/fields/Total_Membership__c.field-meta.xml
<CustomField>
    <fullName>Total_Membership__c</fullName>
    <label>Total Membership</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/BDAttending__c.field-meta.xml
<CustomField>
    <fullName>BDAttending__c</fullName>
    <description>Other Bussinss Development Reps attending the conference</description>
    <label>BD Attending</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alan Ishida</fullName>
            </value>
            <value>
                <fullName>William Fortier</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Brittany Baker</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>Christian James</fullName>
            </value>
            <value>
                <fullName>Christopher Head</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Den Chou</fullName>
            </value>
            <value>
                <fullName>Farida Bahadoor</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kimberly Gavrilles</fullName>
            </value>
            <value>
                <fullName>Krystal Windley</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Reis Hagerman</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>What City State is the conference being help in</description>
    <label>Location</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Presenting__c.field-meta.xml
<CustomField>
    <fullName>Presenting__c</fullName>
    <description>Person will be presenting at the conference, training or workshop</description>
    <label>Presenting</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Betsy Mayotte</fullName>
            </value>
            <value>
                <fullName>Bob Cole</fullName>
            </value>
            <value>
                <fullName>Caroline Menendez</fullName>
            </value>
            <value>
                <fullName>Casey Wallen</fullName>
            </value>
            <value>
                <fullName>Chris Elam</fullName>
            </value>
            <value>
                <fullName>David Snow</fullName>
            </value>
            <value>
                <fullName>Fidel Calero</fullName>
            </value>
            <value>
                <fullName>Gina Lucente-Cole</fullName>
            </value>
            <value>
                <fullName>Jacqueline Carroll</fullName>
            </value>
            <value>
                <fullName>Jay Sweeney</fullName>
            </value>
            <value>
                <fullName>Jill Marr</fullName>
            </value>
            <value>
                <fullName>Joanne Dashiell</fullName>
            </value>
            <value>
                <fullName>John Kelly</fullName>
            </value>
            <value>
                <fullName>Jonathan Sparling</fullName>
            </value>
            <value>
                <fullName>Julie Esau</fullName>
            </value>
            <value>
                <fullName>Kevin Fudge</fullName>
            </value>
            <value>
                <fullName>Lorinda Diehl</fullName>
            </value>
            <value>
                <fullName>Mae St. Julien</fullName>
            </value>
            <value>
                <fullName>Michael Friedman</fullName>
            </value>
            <value>
                <fullName>Paul Combe</fullName>
            </value>
            <value>
                <fullName>Robert Tosh</fullName>
            </value>
            <value>
                <fullName>Sarah Arslanian</fullName>
            </value>
            <value>
                <fullName>Susan Nathan</fullName>
            </value>
            <value>
                <fullName>Tanya Tanaro</fullName>
            </value>
            <value>
                <fullName>Tracy Drechsler</fullName>
            </value>
            <value>
                <fullName>Vince Scalise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/Conference.recordType-meta.xml
<RecordType>
    <fullName>Conference</fullName>
    <active>true</active>
    <description>All Conferences</description>
    <label>Conference</label>
</RecordType>

force-app/main/default/classes/ProposedConferenceAttendanceController.cls
public with sharing class ProposedConferenceAttendanceController {

    public Annual_Sales_Plan__c asp { get; set; }
    public String showPCARelatedlist {get; set;}
    public String numberOfRowToRemove { get; set; }
    public List<PCAWrapper> listPCA {get; set;}
    public List<Annual_Sales_Plan_Items__c> pcaToBeDelList;

    public proposedConferenceAttendanceController (ApexPages.StandardController sc) {
        if(sc != null && sc.getId() != null){
            asp = [Select Id,Name,Owner.Name,(Select Id,Name,Annual_Sales_Plan__c,Conference_Name_Presentation_Proposed__c,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,Proposed__c,Presenting__c,Conference_Name_Presentation_Proposed__r.StartDate,Conference_Name_Presentation_Proposed__r.Name,Conference_Name_Presentation_Proposed__r.Location__c,Conference_Name_Presentation_Proposed__r.EndDate,Conference_Name_Presentation_Proposed__r.BDAttending__c,Conference_Name_Presentation_Proposed__r.Presenting__c,Audience__c,School_Name__c,Total_Enrollments__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r Where PCA_Record__c = true AND Conference_Name_Presentation_Proposed__c != null Order By Name) From Annual_Sales_Plan__c Where Id =: sc.getId()];
            showPCARelatedlist = 'true';
            preparePCAList();
            
        }
    }
    public void addRows(){
        PCAWrapper wrapper = new PCAWrapper();
        wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
        listPCA.add(wrapper);
    }
    public void removeRows(){
        List<PCAWrapper> pcawTemp = new List<PCAWrapper>();
        for(PCAWrapper pcaw : listPCA){
            if(pcaw.pca.Id == numberOfRowToRemove){
               pcaToBeDelList.add(pcaw.pca); 
            }
            else {
                pcawTemp.add(pcaw);
            }
        }
        listPCA = new List<PCAWrapper>();
        listPCA = pcawTemp;
    }
    public void savePCA() {
        try{
            List<Annual_Sales_Plan_Items__c> insertProposedConferenceList = new List<Annual_Sales_Plan_Items__c>();
            String campId;
            List<Campaign> campList = [Select Id,BDAttending__c,Presenting__c From Campaign Where RecordType.Name = 'Conference' AND isActive = true];
            Map<Id,Campaign> campMap = new Map<Id,Campaign>();
            
            for(Campaign campTemp : campList){
                campMap.put(campTemp.Id,campTemp);    
            }
            
            for(PCAWrapper pcawTemp : listPCA) {
                campId = pcawTemp.pca.Conference_Name_Presentation_Proposed__c;
                if((pcawTemp.pca.Id==null && pcawTemp.pca.Conference_Name_Presentation_Proposed__c !=null)){
                    pcawTemp.pca.PCA_Record__c = true;
                    Boolean checkBDAttending = false;
                    Boolean checkPresenting = false;
                    List<String> bDAttendingList;
                    List<String> presentingList;
                    
                    if(campMap.get(campId).BDAttending__c != null && campMap.get(campId).BDAttending__c.contains(';')){
                        BDAttendingList = campMap.get(campId).BDAttending__c.split(';');
                        for(String s : bDAttendingList){
                            if(s==asp.Owner.Name)
                                checkBDAttending = true;
                        }
                    }else if(campMap.get(campId).BDAttending__c != null && campMap.get(campId).BDAttending__c == asp.Owner.Name){
                        checkBDAttending = true;
                    }
                    if(campMap.get(campId).Presenting__c != null && campMap.get(campId).Presenting__c.contains(';')){
                        PresentingList = campMap.get(campId).Presenting__c.split(';');
                        for(String s : presentingList){
                            if(s==asp.Owner.Name)
                                checkPresenting = true;
                        }
                    }else if(campMap.get(campId).Presenting__c != null && campMap.get(campId).Presenting__c == asp.Owner.Name){
                        checkPresenting = true;
                    }
                    
                    if(campMap.containsKey(campId)){
                        if(checkBDAttending){
                            pcawTemp.pca.Attending__c = true;
                            pcawTemp.pca.Proposed__c = false;
                        } 
                        else{
                            pcawTemp.pca.Proposed__c = true;
                            pcawTemp.pca.Attending__c = false;
                        }
                        if(checkPresenting){pcawTemp.pca.Presenting__c = true;}
                        else{pcawTemp.pca.Presenting__c = false;}
                    }
                    
                    insertProposedConferenceList.add(pcawTemp.pca);
                } else if(pcawTemp.pca.Id!=null){
                    insertProposedConferenceList.add(pcawTemp.pca);    
                }
            }
             
            upsert insertProposedConferenceList;
                        
            delete pcaToBeDelList;
            asp = [Select Id,Name,Owner.Name,(Select Id,Name,Annual_Sales_Plan__c,Conference_Name_Presentation_Proposed__r.Name,Conference_Name_Presentation_Proposed__c,Target_Aggregator_Name__c,Approved_Aggregator_Name__c,of_Targets_in_Territory__c,Aggregators_Status_Update__c,Total_Membership__c,Attending__c,Proposed__c,Presenting__c,Conference_Name_Presentation_Proposed__r.StartDate,Conference_Name_Presentation_Proposed__r.Location__c,School_Name__c,Conference_Name_Presentation_Proposed__r.EndDate,Audience__c,Total_Enrollments__c,Conference_Name_Presentation_Proposed__r.BDAttending__c,Conference_Name_Presentation_Proposed__r.Presenting__c,Target_ESSS_Status_Update__c From Proposed_Conference_Attendance__r Where PCA_Record__c = true AND Conference_Name_Presentation_Proposed__c != null) From Annual_Sales_Plan__c Where Id =: ApexPages.currentPage().getParameters().get('id')];
            showPCARelatedlist = 'true';
            preparePCAList();
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
    
    public void preparePCAList(){
        try{
            pcaToBeDelList = new List<Annual_Sales_Plan_Items__c>();
            listPCA = new List<PCAWrapper>();
                
            for(Integer i = 1; i<=asp.Proposed_Conference_Attendance__r.size(); i++){
                PCAWrapper wrapper = new PCAWrapper();
                wrapper.pca = asp.Proposed_Conference_Attendance__r[i-1];
                listPCA.add(wrapper) ;
            }
            if(showPCARelatedlist!='true'){
                PCAWrapper wrapper = new PCAWrapper();
                wrapper.pca = new Annual_Sales_Plan_Items__c(Annual_Sales_Plan__c = asp.Id);
                listPCA.add(wrapper) ;
            }   
            
            List<Annual_Sales_Plan_Items__c> insertProposedConferenceList = new List<Annual_Sales_Plan_Items__c>();
            String campId;
            List<Campaign> campList = [Select Id,BDAttending__c,Presenting__c From Campaign Where RecordType.Name = 'Conference' AND isActive = true];
            Map<Id,Campaign> campMap = new Map<Id,Campaign>();
            
            for(Campaign campTemp : campList){
                campMap.put(campTemp.Id,campTemp);    
            }
            
            for(PCAWrapper pcawTemp : listPCA) {
                if(pcawTemp.pca.Conference_Name_Presentation_Proposed__c != null){campId = pcawTemp.pca.Conference_Name_Presentation_Proposed__c;}
                Boolean checkBDAttending = false;
                Boolean checkPresenting = false;
                List<String> bDAttendingList;
                List<String> presentingList;
                
                if(campMap.get(campId).BDAttending__c != null && campMap.get(campId).BDAttending__c.contains(';')){
                    BDAttendingList = campMap.get(campId).BDAttending__c.split(';');
                    for(String s : bDAttendingList){
                        if(s==asp.Owner.Name){
                            checkBDAttending = true;
                        }    
                    }
                }else if(campMap.get(campId).BDAttending__c != null && campMap.get(campId).BDAttending__c == asp.Owner.Name){
                    checkBDAttending = true;
                }
                if(campMap.get(campId).Presenting__c != null && campMap.get(campId).Presenting__c.contains(';')){
                    PresentingList = campMap.get(campId).Presenting__c.split(';');
                    for(String s : presentingList){
                        if(s==asp.Owner.Name)
                            checkPresenting = true;
                    }
                }else if(campMap.get(campId).Presenting__c != null && campMap.get(campId).Presenting__c == asp.Owner.Name){
                    checkPresenting = true;
                }
                
                if(campMap.containsKey(campId)){
                    if(checkBDAttending){
                        pcawTemp.pca.Attending__c = true;
                        pcawTemp.pca.Proposed__c = false;
                    } 
                    else{
                        pcawTemp.pca.Proposed__c = true;
                        pcawTemp.pca.Attending__c = false;
                    }
                    if(checkPresenting){pcawTemp.pca.Presenting__c = true;}
                    else{pcawTemp.pca.Presenting__c = false;}
                }
            }
        }
        catch(Exception e){
            System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
        }
    }
    
    public class PCAWrapper{
        public Annual_Sales_Plan_Items__c pca {get; set;}
    }
}