force-app/main/default/objects/CSARequests__c/CSARequests__c.object-meta.xml
<CustomObject>
    <description>Client Services Administrations Page</description>
    <label>CSA Requests</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSARequests__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account task is associated with.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>SPA</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Conference_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Conference_End_Date__c</fullName>
    <label>Conference End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Conference_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Conference_Start_Date__c</fullName>
    <label>Conference Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/CSA_Request__c.field-meta.xml
<CustomField>
    <fullName>CSA_Request__c</fullName>
    <description>List of the possible requests that could be made of CSA</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add/Edit Salesforce contacts</fullName>
            </value>
            <value>
                <fullName>Advisory Board Support</fullName>
            </value>
            <value>
                <fullName>Ambassador Program Request</fullName>
            </value>
            <value>
                <fullName>Business Cards</fullName>
            </value>
            <value>
                <fullName>Campaign Assistance</fullName>
            </value>
            <value>
                <fullName>Campus Activation Event</fullName>
            </value>
            <value>
                <fullName>Check Request</fullName>
            </value>
            <value>
                <fullName>Client Forum Support</fullName>
            </value>
            <value>
                <fullName>Collateral or Presentations</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Conference Presentation Assistance</fullName>
            </value>
            <value>
                <fullName>Conference Presentation Proposal</fullName>
            </value>
            <value>
                <fullName>Conference Registration</fullName>
            </value>
            <value>
                <fullName>Create Brand Name</fullName>
            </value>
            <value>
                <fullName>Data Depersonalization Request</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Marketing Request</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Research</fullName>
            </value>
            <value>
                <fullName>New/Renew Association Membership</fullName>
            </value>
            <value>
                <fullName>New Collateral</fullName>
            </value>
            <value>
                <fullName>Off-board Client</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Pre-Conference Email</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Meeting / In-Person Support</fullName>
            </value>
            <value>
                <fullName>Presentation Content Assistance</fullName>
            </value>
            <value>
                <fullName>President Pre-Renewal Letter</fullName>
            </value>
            <value>
                <fullName>Print/Copy Materials</fullName>
            </value>
            <value>
                <fullName>Purchasing Assistance</fullName>
            </value>
            <value>
                <fullName>Reports</fullName>
            </value>
            <value>
                <fullName>Return School Copy of Contract</fullName>
            </value>
            <value>
                <fullName>Salesforce Admininstrator Request</fullName>
            </value>
            <value>
                <fullName>Salt Demo / Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Please put in the details here</description>
    <inlineHelpText>Please put in the details here</inlineHelpText>
    <label>Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The date the task needs to be completed</description>
    <label>Due/Proposal Deadline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Engagement_Partner_Request__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Partner_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Select this checkbox if the request being submitted is specifically for ENGAGEMENT PARTNERS only - not for the SCHOOL CHANNEL.</description>
    <inlineHelpText>Select this checkbox if the request being submitted is specifically for ENGAGEMENT PARTNERS only - otherwise, leave this field blank.</inlineHelpText>
    <label>Engagement Partner Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CSARequests__c/fields/Expected_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Expected_Attendees__c</fullName>
    <label>Expected Attendees</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestCreate_ProServiceOffering.cls
@isTest
private class TestCreate_ProServiceOffering{
  
    
    static testmethod void testOff(){
    
        Test.startTest();
        
        RecordType rt = [SELECT id,Name FROM RecordType WHERE SobjectType='CSARequests__c' AND Name='Pro Services Request'];
        
        Account acc = new Account(Name='TestAcc');
        insert acc;
        
        CSARequests__c csa=new CSARequests__c(Name='Mail',End_Date__c=System.today().addDays(5),Due_Date__c=System.today(),Details__c='test test test',Meeting_Date__c=system.today(),Recordtypeid=rt.id,CSA_Request__c='Conference Presentation Proposal',Engagement_Partner_Request__c=False,Account__c=acc.id,Expected_Attendees__c =54,Conference_Start_Date__c=system.today(),Conference_End_Date__c=system.today().addDays(3));
        insert csa;
               
        Attachment attach=new Attachment();    
        attach.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.Description= 'xyz';
        attach.parentId=csa.id;
        insert attach;
        
        List<Attachment> attachments=[select id, name from Attachment where parent.id=:csa.id];
        System.assertEquals(1, attachments.size());
        
        csa.CSA_Request__c='';
        update csa;
        csa.CSA_Request__c='Salt Demo / Webinar';
        update csa;
        
        Test.stopTest();
       
    }
}