force-app/main/default/objects/Contact/fields/Ambassador_Account__c.field-meta.xml
<CustomField>
    <fullName>Ambassador_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Story S-54-16 - Create private contact based on record type</description>
    <label>Ambassador Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SALT Ambassadors &amp; Members</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The contact that the contract should go to.</description>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is REQUIRED for the School Channel process - if it is left empty the automated Renewal Opportunity porcess will fail to execute.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/Contract_Lines__c.object-meta.xml
<CustomObject>
    <label>Contract Lines</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Contract Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Lines__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Invoice_Count__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Auto generated count of how many invoices have been generated for this line</inlineHelpText>
    <label>Invoice Count</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Invoice_Freq__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Freq__c</fullName>
    <label>Invoice Freq #</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Total_number_invoices__c.field-meta.xml
<CustomField>
    <fullName>Total_number_invoices__c</fullName>
    <inlineHelpText>Total number of invoices that will generate over life of line</inlineHelpText>
    <label>Total # Invoices</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestSchedulerBatchSendReminder30.cls
@isTest(seeAllData=true)
private class TestSchedulerBatchSendReminder30{

    public static String CRON_EXP = '0 0 1 * * ?';

    static testmethod void test() {
        Test.startTest();
        
        Account acc=new Account(Name='College Planning Services');
        insert acc;
        
        Contact con=new Contact(LastName='Doe',Ambassador_Account__c=acc.id,FirstName = 'First Name',AccountId = acc.id);
        insert con;
        
        Opportunity opp = new Opportunity(Name = 'Opp 2016', AccountId = acc.Id, Type = 'Standard', LeadSource = 'RFI', CloseDate = Date.newInstance(System.today().year(), 5, 10), StageName = 'Prospecting');
        insert opp; 
        
        Contract cont = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
        insert cont;
        
        Contract_Lines__c conLines = new Contract_Lines__c();
        conLines.Contract__c = cont.Id;
        conLines.Total_number_invoices__c = 3;
        conLines.Invoice_Count__c = 2;
        conLines.Unit_Price__c = 50;
        conLines.Invoice_Freq__c = 3;
        insert conLines;
        
        User u1 = [SELECT Id FROM User WHERE Name='Andrew Marley' and isActive = true LIMIT 1];
            
        System.RunAs(u1){   
            c2g__codaInvoice__c newInvoice = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont.id,c2g__InvoiceDate__c = Date.today().addDays(-40),c2g__DueDate__c = System.today().addDays(-30));
            insert newInvoice;
        }
        
        Database.executeBatch(new BatchSendInvoiceRemider30(), 1000);
        
        Test.stopTest();
   }
}