force-app/main/default/objects/Contact/fields/Ambassador_Account__c.field-meta.xml
<CustomField>
    <fullName>Ambassador_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Story S-54-16 - Create private contact based on record type</description>
    <label>Ambassador Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SALT Ambassadors &amp; Members</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The contact that the contract should go to.</description>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Next_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Invoice_Date__c</fullName>
    <description>Next invoice date on contract header is earliest date on contract line</description>
    <inlineHelpText>Next invoice date on contract header is earliest date on contract line</inlineHelpText>
    <label>Next Invoice Date</label>
    <summarizedField>Contract_Lines__c.Next_Invoice_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Contract_Lines__c.Remaining_Invoices__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Contract_Lines__c.Contract__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field is REQUIRED for the School Channel process - if it is left empty the automated Renewal Opportunity porcess will fail to execute.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/Contract_Lines__c.object-meta.xml
<CustomObject>
    <label>Contract Lines</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Contract Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Lines__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Invoice_Count__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Auto generated count of how many invoices have been generated for this line</inlineHelpText>
    <label>Invoice Count</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Invoice_Freq__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Freq__c</fullName>
    <label>Invoice Freq #</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Next_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Invoice_Date__c</fullName>
    <label>Next Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Total_number_invoices__c.field-meta.xml
<CustomField>
    <fullName>Total_number_invoices__c</fullName>
    <inlineHelpText>Total number of invoices that will generate over life of line</inlineHelpText>
    <label>Total # Invoices</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Lines__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestcalculateSPEndDate.cls
/**
@Name            : TestcalculateSPEndDate 
@Author          : MONIKA CONAM
@Date            : Jan 23 2017
@Description     : Test class for 'CalculateSPEndDate' Trigger
**/
@isTest(seeAllData=true)
private class TestcalculateSPEndDate 
{   

    static final boolean softFail = false; //if true tests will fail softly - that is they will not be marked as failed but may not contribute full code coverage
    
    static testmethod void calculateSPEndDate() {
    Test.startTest();  

        try{
        
            Account acc=new Account(Name='College Planning Services');
            insert acc; 
            Account accRecord = [Select Id,Name from Account where Name = 'College Planning Services'];
            System.assertEquals('College Planning Services',accRecord.name);
            
            Account acc2=new Account(Name='College Planning Services 1');
            insert acc2;  
            
            Contact con=new Contact(LastName='Doe',Ambassador_Account__c=acc.id,FirstName = 'John',AccountId = acc.Id);
            insert con;
            
            Contact conRecord = [Select Id,Ambassador_Account__r.Name from Contact where Ambassador_Account__r.Name = 'College Planning Services'];
            System.assertEquals('College Planning Services',conRecord.Ambassador_Account__r.Name);
            
            Contact con2=new Contact(LastName='Doe2',Ambassador_Account__c=acc.id,FirstName = 'First Name',AccountId = acc.Id);
            insert con2;  
            
            Opportunity opp = new Opportunity(Name = 'Opp 2016', AccountId = acc.Id, Type = 'Standard', LeadSource = 'RFI', CloseDate = Date.newInstance(System.today().year(), 5, 10), StageName = 'Prospecting');
            insert opp; 
            
            Opportunity opp2 = new Opportunity(Name = 'Opp 2017', AccountId = acc.Id, Type = 'Standard', LeadSource = 'RFI', CloseDate = Date.newInstance(System.today().year(), 5, 10), StageName = 'Prospecting');
            insert opp2;
            
            Contract cont = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
            insert cont;
            
            Contract_Lines__c conLines = new Contract_Lines__c();
            conLines.Contract__c = cont.Id;
            conLines.Total_number_invoices__c = 3;
            conLines.Invoice_Count__c = 2;
            conLines.Unit_Price__c = 50;
            conLines.Invoice_Freq__c = 3;
            insert conLines;
            
            Contract cont2 = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
            insert cont2;
            
            Contract_Lines__c conLines2 = new Contract_Lines__c();
            conLines2.Contract__c = cont2.Id;
            conLines2.Total_number_invoices__c = 3;
            conLines2.Invoice_Count__c = 2;
            conLines2.Unit_Price__c = 50;
            conLines2.Invoice_Freq__c = 12;
            //conLines2.Next_Invoice_Date__c = Date.today().addDays(12);
            insert conLines2;
            
            Contract cont3 = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
            insert cont3;
            
            Contract_Lines__c conLines3 = new Contract_Lines__c();
            conLines3.Contract__c = cont3.Id;
            conLines3.Total_number_invoices__c = 3;
            conLines3.Invoice_Count__c = 2;
            conLines3.Unit_Price__c = 50;
            conLines3.Invoice_Freq__c = 6;
            //conLines3.Next_Invoice_Date__c = Date.today().addDays(12);
            insert conLines3;
            
            Contract cont4 = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
            insert cont4;
            
            Contract_Lines__c conLines4 = new Contract_Lines__c();
            conLines4.Contract__c = cont4.Id;
            conLines4.Total_number_invoices__c = 3;
            conLines4.Invoice_Count__c = 2;
            conLines4.Unit_Price__c = 50;
            conLines4.Invoice_Freq__c = 1;
            //conLines4.Next_Invoice_Date__c = Date.today().addDays(12);
            insert conLines4;
            
            Contract cont5 = new Contract(AccountId=acc.id,Contact_Name__c=con.id,Opportunity__c=opp.id);
            insert cont5;
            
            Contract_Lines__c conLines5 = new Contract_Lines__c();
            conLines5.Contract__c = cont5.Id;
            conLines5.Total_number_invoices__c = 2;
            conLines5.Invoice_Count__c = 2;
            conLines5.Unit_Price__c = 50;
            conLines5.Invoice_Freq__c = 6;
            //conLines5.Next_Invoice_Date__c = Date.today().addDays(12);
            insert conLines5;
            
            Contract cont6 = new Contract(AccountId=acc.id,Contact_Name__c=con2.id,Opportunity__c=opp2.id);
            insert cont6;
            
            Contract_Lines__c conLines6 = new Contract_Lines__c();
            conLines6.Contract__c = cont6.Id;
            conLines6.Total_number_invoices__c = 4;
            conLines6.Invoice_Count__c = 2;
            conLines6.Unit_Price__c = 50;
            conLines6.Invoice_Freq__c = 6;
            conLines6.Next_Invoice_Date__c = Date.today().addDays(12);
            insert conLines6;
            
            Contract_Lines__c conLines7 = new Contract_Lines__c();
            conLines7.Contract__c = cont6.Id;
            conLines7.Total_number_invoices__c = 4;
            conLines7.Invoice_Count__c = 2;
            conLines7.Unit_Price__c = 50;
            conLines7.Invoice_Freq__c = 6;
            conLines7.Next_Invoice_Date__c = Date.today().addDays(10);
            insert conLines7;
            
            User u1 = [SELECT Id FROM User WHERE Name='Andrew Marley' and isActive = true LIMIT 1];
            
            System.RunAs(u1){   
                c2g__codaInvoice__c newInvoice = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont.id,c2g__InvoiceDate__c = Date.today());
                insert newInvoice;
                
                c2g__codaInvoice__c newInvoice2 = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont2.id,c2g__InvoiceDate__c = Date.today());
                insert newInvoice2;
                
                c2g__codaInvoice__c newInvoice3 = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont3.id,c2g__InvoiceDate__c = Date.today());
                insert newInvoice3;
                
                c2g__codaInvoice__c newInvoice4 = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont4.id,c2g__InvoiceDate__c = Date.today());
                insert newInvoice4;
                
                c2g__codaInvoice__c newInvoice5 = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont5.id,c2g__InvoiceDate__c = Date.today());
                insert newInvoice5;
                
                
                c2g__codaInvoice__c newInvoice6 = new c2g__codaInvoice__c(c2g__Account__c = acc.id,Contract__c=cont6.id,c2g__InvoiceDate__c = Date.today(),
                                                                        Service_Period_Start_Date__c = Date.Today(),c2g__DueDate__c = Date.today().addDays(5));
                try{
                    insert newInvoice6;
                }
                catch(Exception e){
                    System.debug('An exception has occurred: ' + e.getMessage() + ' - ' + e.getLineNumber());
                }
            }          
                  
        }
        catch(Exception e){
            if(softFail){
                System.debug(LoggingLevel.Error,'Soft fail enabled. Test marked as passed but it really failed with '+e.getMessage());
            }
            else{
                throw e;
            }
        }
           
    Test.stopTest();   
    }    
}