force-app/main/default/objects/Contact/fields/Annual_Taxable_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Taxable_Income__c</fullName>
    <label>Annual Taxable Income</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>$0 – 18,210</fullName>
            </value>
            <value>
                <fullName>$18,211 – 24,690</fullName>
            </value>
            <value>
                <fullName>$24,691 – 31,170</fullName>
            </value>
            <value>
                <fullName>$31,171 – 37,650</fullName>
            </value>
            <value>
                <fullName>$37,651 – 44,130</fullName>
            </value>
            <value>
                <fullName>$44,131 – 50,610</fullName>
            </value>
            <value>
                <fullName>$50,611 – 57,090</fullName>
            </value>
            <value>
                <fullName>$57,091 – 63,570</fullName>
            </value>
            <value>
                <fullName>Over $63,570</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Not available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Are_you_a_US_Citizen__c.field-meta.xml
<CustomField>
    <fullName>Are_you_a_US_Citizen__c</fullName>
    <label>Are you a US Citizen?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/At_Risk_Alg_Not_Completed_10th_ATOIS__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Alg_Not_Completed_10th_ATOIS__c</fullName>
    <inlineHelpText>At Risk: Pre-Algebra or Algebra Course Not Successfully Completed by Beginning of 10th Grade (at time of initial selection).</inlineHelpText>
    <label>At Risk: Alg Not Completed 10th (ATOIS)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No algebra (or pre-) by 10th grade start</fullName>
            </value>
            <value>
                <fullName>Algebra (or pre-) completed by 10th gr</fullName>
            </value>
            <value>
                <fullName>n/a (not yet available)</fullName>
            </value>
            <value>
                <fullName>n/a (prior to 2012)</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/At_Risk_Low_GPA_ATOIS__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Low_GPA_ATOIS__c</fullName>
    <inlineHelpText>At Risk: Low-Grade Point Average (at time of initial selection).</inlineHelpText>
    <label>At Risk: Low GPA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GPA of 2.5 or less</fullName>
            </value>
            <value>
                <fullName>GPA above 2.5</fullName>
            </value>
            <value>
                <fullName>n/a (prior to 2012)</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/At_Risk_Reading_LA_or_Math_ATOIS__c.field-meta.xml
<CustomField>
    <fullName>At_Risk_Reading_LA_or_Math_ATOIS__c</fullName>
    <inlineHelpText>At Risk: Reading/Language Arts or Math Proficiency Not Achieved (at time of initial selection).</inlineHelpText>
    <label>At Risk: Reading/LA or Math (ATOIS)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOT Proficient in State assessments</fullName>
            </value>
            <value>
                <fullName>Proficient in State assessments</fullName>
            </value>
            <value>
                <fullName>n/a (no results)</fullName>
            </value>
            <value>
                <fullName>n/a (prior to 2012)</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Client_Signature_Needed_Received__c.field-meta.xml
<CustomField>
    <fullName>Client_Signature_Needed_Received__c</fullName>
    <label>Client Signature Needed/Received</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Needed/NOT Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>NOT Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Eligibility__c.field-meta.xml
<CustomField>
    <fullName>Eligibility__c</fullName>
    <inlineHelpText>Eligibility (at time of initial selection)</inlineHelpText>
    <label>Eligibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic Risk only (UB)</fullName>
            </value>
            <value>
                <fullName>First-Gen and academic risk (UB)</fullName>
            </value>
            <value>
                <fullName>First-Gen College only</fullName>
            </value>
            <value>
                <fullName>Low-income and academic risk (UB)</fullName>
            </value>
            <value>
                <fullName>Low-Income and First-Gen College</fullName>
            </value>
            <value>
                <fullName>Low-income-first-gen-academic risk (UB)</fullName>
            </value>
            <value>
                <fullName>Low-Income only</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Income_Source__c.field-meta.xml
<CustomField>
    <fullName>Income_Source__c</fullName>
    <label>Primary Income Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Child support</fullName>
            </value>
            <value>
                <fullName>No income</fullName>
            </value>
            <value>
                <fullName>Signed Statement</fullName>
            </value>
            <value>
                <fullName>Social Security</fullName>
            </value>
            <value>
                <fullName>SSI or SSDI</fullName>
            </value>
            <value>
                <fullName>TAFDC (welfare)</fullName>
            </value>
            <value>
                <fullName>Unemployment</fullName>
            </value>
            <value>
                <fullName>Wages/salary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Intake_Location__c.field-meta.xml
<CustomField>
    <fullName>Intake_Location__c</fullName>
    <label>Intake Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CPS_Intake_location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Media_Release_Authorized__c.field-meta.xml
<CustomField>
    <fullName>Is_Media_Release_Authorized__c</fullName>
    <label>Is Media Release Authorized?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Is_Text_ED_Participant__c.field-meta.xml
<CustomField>
    <fullName>Is_Text_ED_Participant__c</fullName>
    <label>Is Text ED Participant? (BPL only)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Limited_English_Proficiency__c.field-meta.xml
<CustomField>
    <fullName>Limited_English_Proficiency__c</fullName>
    <inlineHelpText>Limited English Proficiency (at time of initial selection)</inlineHelpText>
    <label>Limited English Proficiency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Parent_Signature_Needed_Received__c.field-meta.xml
<CustomField>
    <fullName>Parent_Signature_Needed_Received__c</fullName>
    <label>Parent Signature Needed/Received</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Needed/NOT Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>NOT Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Permanent_Resident_ID_Text__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Resident_ID_Text__c</fullName>
    <label>Permanent Resident ID</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Permanent_Resident_ID_Verified__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Resident_ID_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permanent Resident ID Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_School_at_Intake_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Secondary_School_at_Intake_Picklist__c</fullName>
    <label>Secondary School Talent Search</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Talent_Search_Target_Schools</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SSN_text__c.field-meta.xml
<CustomField>
    <fullName>SSN_text__c</fullName>
    <label>SSN</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPSMissingDataAlertCtrl.cls
public class CPSMissingDataAlertCtrl{
//SFD-74   
    @AuraEnabled
    public static List<String> getTargetInfo(String recordId)
    {
        Contact conRec = [Select Id,Eligibility__c,Annual_Taxable_Income__c,Income_Source__c,RecordTypeId,SSN_text__c,Permanent_Resident_ID_Text__c,
                          Are_you_a_US_Citizen__c,Is_Media_Release_Authorized__c,Limited_English_Proficiency__c,MobilePhone,Intake_Location__c,
                          At_Risk_Reading_LA_or_Math_ATOIS__c,At_Risk_Low_GPA_ATOIS__c,At_Risk_Alg_Not_Completed_10th_ATOIS__c,recordtype.name,
                          Parent_Signature_Needed_Received__c,Client_Signature_Needed_Received__c,Secondary_School_at_Intake_Picklist__c,Is_Text_ED_Participant__c,
                          Permanent_Resident_ID_Verified__c From Contact Where Id =:recordId];
                          
                          System.debug('conRec @@@@'+conRec);
                          
        List<String> allErrMsg=new List<String>();

        if(conRec.recordType.name=='CPS - EOC')
        {
            if(conRec.Secondary_School_at_Intake_Picklist__c != '' && conRec.Secondary_School_at_Intake_Picklist__c != 'None of these' && conRec.Secondary_School_at_Intake_Picklist__c != null)
                allErrMsg.add('ALERT! This Client is attending a Talent Search Target School.');
        }
        return allErrMsg;
    }
    
    @AuraEnabled
    public static List<String> getAllMissingInfo(String recordId)
    {
        Contact conRec = [Select Id,Eligibility__c,Annual_Taxable_Income__c,Income_Source__c,RecordTypeId,SSN_text__c,Permanent_Resident_ID_Text__c,
                          Are_you_a_US_Citizen__c,Is_Media_Release_Authorized__c,Limited_English_Proficiency__c,MobilePhone,Intake_Location__c,
                          At_Risk_Reading_LA_or_Math_ATOIS__c,At_Risk_Low_GPA_ATOIS__c,At_Risk_Alg_Not_Completed_10th_ATOIS__c,recordtype.name,
                          Parent_Signature_Needed_Received__c,Client_Signature_Needed_Received__c,Secondary_School_at_Intake_Picklist__c,Is_Text_ED_Participant__c,
                          Permanent_Resident_ID_Verified__c  From Contact Where Id =:recordId];//: ApexPages.currentPage().getParameters().get('id') AND (RecordTypeId =: recTypeCPS_TS OR RecordTypeId =: recTypeCPS_EOC OR RecordTypeId =: recTypeCPS_UB)];
        
        List<String> allErrMsg=new List<String>();
        if(conRec.recordType.name=='CPS - EOC' || conRec.recordType.name=='CPS - TS' || conRec.recordType.name=='CPS - UB')
        {
            if(conRec.Eligibility__c == ''|| conRec.Eligibility__c == 'Unknown/Not disclosed'|| conRec.Eligibility__c ==null )
                allErrMsg.add('Eligibility');
                
            if(conRec.Annual_Taxable_Income__c == ''|| conRec.Annual_Taxable_Income__c == 'Unknown'|| conRec.Annual_Taxable_Income__c ==null)
                allErrMsg.add('Annual Taxable Income');
                
            if((conRec.SSN_text__c == '' || conRec.SSN_text__c ==null) && (conRec.Permanent_Resident_ID_Text__c == ''|| conRec.Permanent_Resident_ID_Text__c == '000000000' || conRec.Permanent_Resident_ID_Text__c == null))
                allErrMsg.add('SSN OR Permanent Resident ID');
                
            if(conRec.Are_you_a_US_Citizen__c == 'No' && (conRec.Permanent_Resident_ID_Text__c == ''|| conRec.Permanent_Resident_ID_Text__c == '000000000' || conRec.Permanent_Resident_ID_Text__c == null))
                allErrMsg.add('Are you a US citizen?/Permanent Resident ID');
    
            if(conRec.Parent_Signature_Needed_Received__c == null || conRec.Parent_Signature_Needed_Received__c =='Needed/NOT Received' ||  conRec.Parent_Signature_Needed_Received__c =='' || conRec.Parent_Signature_Needed_Received__c == 'Unknown')
                allErrMsg.add('Parent Signature Needed/Received');
                
            if(conRec.Client_Signature_Needed_Received__c == null || conRec.Client_Signature_Needed_Received__c =='Needed/NOT Received' ||  conRec.Client_Signature_Needed_Received__c =='' || conRec.Client_Signature_Needed_Received__c == 'Unknown')
                allErrMsg.add('Client Signature Needed/Received');
            
            if(conRec.Is_Media_Release_Authorized__c == '' || conRec.Is_Media_Release_Authorized__c ==null)
                allErrMsg.add('Is Media Release Authorized?');
            
            if(conRec.Limited_English_Proficiency__c == null ||  conRec.Limited_English_Proficiency__c  =='' || conRec.Limited_English_Proficiency__c == 'Unknown')
                allErrMsg.add('Limited English Proficiency');
                
            if((conRec.Is_Text_ED_Participant__c == null ||  conRec.Is_Text_ED_Participant__c =='' || conRec.Is_Text_ED_Participant__c == 'Unknown') && (conRec.MobilePhone != ''&& conRec.MobilePhone!=null)  && conRec.Intake_Location__c == 'EOC Boston')
                allErrMsg.add('Is Text ED Participant?');
                
            if(conRec.Permanent_Resident_ID_Text__c != null && conRec.Permanent_Resident_ID_Verified__c == False )
                allErrMsg.add('Permanent Resident ID is not verified');
                
            if(conRec.recordType.name=='CPS - EOC')
            {
                if(conRec.Income_Source__c == '' || conRec.Income_Source__c == 'Unknown' || conRec.Income_Source__c == null)
                    allErrMsg.add('Income Source');
            }
            
            if(conRec.recordType.name=='CPS - UB')
            {
                if(conRec.At_Risk_Reading_LA_or_Math_ATOIS__c == '' || conRec.At_Risk_Reading_LA_or_Math_ATOIS__c == 'Unknown' || conRec.At_Risk_Reading_LA_or_Math_ATOIS__c == null)
                    allErrMsg.add('At Risk: Reading/LA or Math (ATOIS)');
                
                if(conRec.At_Risk_Low_GPA_ATOIS__c == '' || conRec.At_Risk_Low_GPA_ATOIS__c == 'Unknown' || conRec.At_Risk_Low_GPA_ATOIS__c == null)
                    allErrMsg.add('At Risk: Low GPA');
                
                if(conRec.At_Risk_Alg_Not_Completed_10th_ATOIS__c == '' || conRec.At_Risk_Alg_Not_Completed_10th_ATOIS__c == 'Unknown' || conRec.At_Risk_Alg_Not_Completed_10th_ATOIS__c == null)
                    allErrMsg.add('At Risk: Alg Not Completed 10th (ATOIS)');
            }
        }
        if(allErrMsg.size()>0)
            allErrMsg.add(0,'ALERT! The following field(s) are missing data:');
        return allErrMsg;
    }
}