force-app/main/default/objects/CampaignMember/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active/Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Secondary_School__c.field-meta.xml
<CustomField>
    <fullName>Secondary_School__c</fullName>
    <label>Secondary School</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abington High School</fullName>
            </value>
            <value>
                <fullName>Attleboro High School</fullName>
            </value>
            <value>
                <fullName>Avon High School</fullName>
            </value>
            <value>
                <fullName>Blue Hills Regional High School</fullName>
            </value>
            <value>
                <fullName>Boston Latin Academy</fullName>
            </value>
            <value>
                <fullName>Breed Middle School</fullName>
            </value>
            <value>
                <fullName>Bridgewater-Raynham Regional High School</fullName>
            </value>
            <value>
                <fullName>Brighton High School</fullName>
            </value>
            <value>
                <fullName>Brockton High School</fullName>
            </value>
            <value>
                <fullName>Brook Farm Business and Service Career</fullName>
            </value>
            <value>
                <fullName>Brookline High School</fullName>
            </value>
            <value>
                <fullName>Canton High School</fullName>
            </value>
            <value>
                <fullName>Cardinal Spellman High School</fullName>
            </value>
            <value>
                <fullName>Career Development Center School</fullName>
            </value>
            <value>
                <fullName>Charlestown High School</fullName>
            </value>
            <value>
                <fullName>Community Academy of Science &amp; Health (CASH)</fullName>
            </value>
            <value>
                <fullName>Dorchester High School</fullName>
            </value>
            <value>
                <fullName>East Boston High School</fullName>
            </value>
            <value>
                <fullName>English High School</fullName>
            </value>
            <value>
                <fullName>Everett High School</fullName>
            </value>
            <value>
                <fullName>Jeremiah Burke High School</fullName>
            </value>
            <value>
                <fullName>Lynn Alternative High School</fullName>
            </value>
            <value>
                <fullName>Lynn Classical High School</fullName>
            </value>
            <value>
                <fullName>Lynn English High School</fullName>
            </value>
            <value>
                <fullName>Lynn Vocational Technical Institute School</fullName>
            </value>
            <value>
                <fullName>Madison Park High School</fullName>
            </value>
            <value>
                <fullName>Mario Umana Academy</fullName>
            </value>
            <value>
                <fullName>Mary Lyon High School</fullName>
            </value>
            <value>
                <fullName>Medford High School</fullName>
            </value>
            <value>
                <fullName>Media Communications Technology High School</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Targeted_School__c.field-meta.xml
<CustomField>
    <fullName>Targeted_School__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Targeted School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Targeted_School__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Targeted_School__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Secondary_School__c/Secondary_School__c.object-meta.xml
<CustomObject>
    <label>Secondary School</label>
    <nameField>
        <label>Secondary School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Secondary Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_School__c/Targeted_School__c.object-meta.xml
<CustomObject>
    <label>Targeted School</label>
    <nameField>
        <label>Targeted School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targeted Schools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Targeted_School__c/fields/Is_Target_School_for_Program_s__c.field-meta.xml
<CustomField>
    <fullName>Is_Target_School_for_Program_s__c</fullName>
    <label>Is Target School for Program(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EOC Brockton</fullName>
            </value>
            <value>
                <fullName>EOC Boston</fullName>
            </value>
            <value>
                <fullName>TS Brockton</fullName>
            </value>
            <value>
                <fullName>TS Boston</fullName>
            </value>
            <value>
                <fullName>UB Brockton</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Targeted_School__c/fields/Secondary_School__c.field-meta.xml
<CustomField>
    <fullName>Secondary_School__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Is Target School</description>
    <label>Secondary School</label>
    <referenceTo>Secondary_School__c</referenceTo>
    <relationshipLabel>Targeted Schools</relationshipLabel>
    <relationshipName>Targeted_Schools</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Targeted_School__c/fields/Secondary_School_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_School_Name__c</fullName>
    <formula>Secondary_School__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Secondary School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CPS_TestUtility.cls
//
// (c) 2017 Appirio, Inc.
//
// Apex Class Name: CPS_TestUtility
// Description: This is a utility class to generate test data.
//
// 11th October 2017  Abhimanyu Singh Tanwar  Original (Task # T-637587) - Please see the task description for more details.
//
@isTest
public class CPS_TestUtility {
  
  // This method is used to insert/instantiate "Account" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Account> toBeInserted
  /*public static List<Account> createAccounts( Boolean isInsert, Integer counter ) {
    List<Account> toBeInserted = new List<Account>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Account(
        Name = 'Test Account #' + (i + 1),
        BillingCity = 'Test City',
        BillingPostalCode = '123', 
        BillingStreet = 'Mariff Street'
      ));
    }

    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }*/
  
  // This method is used to insert/instantiate "Contact" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Contact> toBeInserted
  public static List<Contact> createContacts( Boolean isInsert, Integer counter,Id AccountId ) {
    List<Contact> toBeInserted = new List<Contact>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Contact(
        FirstName = 'First #' + (i + 1),
        LastName = 'Last',
        AccountId = AccountId
      ));
    }

    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }
  
  // This method is used to insert/instantiate "Campaign" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Campaign> toBeInserted
  public static List<Campaign> createCampaign( Boolean isInsert, Integer counter ) {
    List<Campaign> toBeInserted = new List<Campaign>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Campaign(
        Name = 'First #' + (i + 1)
      ));
    }
    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }
  
  // This method is used to insert/instantiate "CampaignMember" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<CampaignMember> toBeInserted
  public static List<CampaignMember> createCampaignMember( Boolean isInsert, Integer counter, Id campaignId, Id contactId ) {
    List<CampaignMember> toBeInserted = new List<CampaignMember>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new CampaignMember(
        CampaignId = campaignId,
        contactId = contactId,
        Status = 'Sent',
        Active__c = true
      ));
    }
    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }
  
  // This method is used to insert/instantiate "Targeted_School__c" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Targeted_School__c> toBeInserted
  public static List<Targeted_School__c> createTargetedSchool( Boolean isInsert, Integer counter, Id SchoolId ) {
    List<Targeted_School__c> toBeInserted = new List<Targeted_School__c>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Targeted_School__c(
        Name = 'First #' + (i + 1),
        Secondary_School__c = SchoolId,
        Is_Active__c = true,
        Is_Target_School_for_Program_s__c = 'TS Boston'
      ));
    }
    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }
  
  // This method is used to insert/instantiate "Secondary_School_Name__c" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Secondary_School_Name__c> toBeInserted
  public static List<Secondary_School__c> createSecondarySchool( Boolean isInsert, Integer counter ) {
    List<Secondary_School__c> toBeInserted = new List<Secondary_School__c>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Secondary_School__c(
        Name = 'First #' + (i + 1)
      ));
    }
    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }
  
  /* 
  // This method is used to insert/instantiate "Opportunity" records.
  // @param   Boolean isInsert, Integer counter
  // @return  List<Opportunity> toBeInserted
  public static List<Opportunity> createOpportunities(Boolean isInsert, Integer counter) {
    return createOpportunities(isInsert,counter,null);
  }
  
  // This method is used to insert/instantiate "Opportunity" records.
  // @param   Boolean isInsert, Integer counter, Id accountId
  // @return  List<Opportunity> toBeInserted
  public static List<Opportunity> createOpportunities( Boolean isInsert, Integer counter, Id accountId ) {
    List<Opportunity> toBeInserted = new List<Opportunity>();
    for(Integer i = 0;i < counter;i++) {
      toBeInserted.add(new Opportunity(
        Name = 'Test Opportunity #' + (i + 1),
        CloseDate = System.Today(),
        StageName = 'New',
        AccountId = accountId
      ));
    }

    if(isInsert) {
      insert toBeInserted;
    }
    return toBeInserted;
  }*/
}