force-app/main/default/objects/Salt_Client_Reports__c/Salt_Client_Reports__c.object-meta.xml
<CustomObject>
    <label>Salt Client Reports</label>
    <nameField>
        <label>Salt Client Reports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salt Client Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salt_Client_Reports__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salt Client Reports</relationshipLabel>
    <relationshipName>Salt_Client_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SF_Community__c/SF_Community__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SF Community</label>
</CustomObject>

force-app/main/default/objects/Tracking_Detail__c/Tracking_Detail__c.object-meta.xml
<CustomObject>
    <label>Tracking Detail</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Tracking Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tracking Details</relationshipLabel>
    <relationshipName>Tracking_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Logged_In_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logged In User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tracking_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/recordTypes/Login.recordType-meta.xml
<RecordType>
    <fullName>Login</fullName>
    <active>true</active>
    <label>Login</label>
</RecordType>

force-app/main/default/classes/TestSaltClientReportController.cls
@isTest(seeAllData=true)
private class TestSaltClientReportController
{
    static testmethod void SaltClientReportController() {
        Test.startTest();
            
        Account acc = new Account(Name='Acc1');
        insert acc;
                
        //Profile p = [SELECT Id FROM Profile WHERE Name='Customer Community User']; 
            
        //User userName = [Select id,Email,UserName,ContactId from User where Name='Kelly Matera'];
        
         Account a = new Account(Name=' College Planning Services');
          insert a;
         
          Contact c = new Contact(LastName = 'Contact Last Name', AccountId = a.id,FirstName = 'First Name');
          insert c;
 
          user user = new User();
          user.ProfileID = [Select Id From Profile Where Name='Customer Community User'].id;
          user.EmailEncodingKey = 'ISO-8859-1';
          user.LanguageLocaleKey = 'en_US';
          user.TimeZoneSidKey = 'America/New_York';
          user.LocaleSidKey = 'en_US';
          user.FirstName = 'first';
          user.LastName = 'last';
          user.Username = 'test@appirio.com';   
          user.CommunityNickname = 'testUser123';
          user.Alias = 't1';
          user.Email = 'no@email.com';
          user.IsActive = true;
          user.ContactId = c.Id;
         insert user;
                
        Salt_Client_Reports__c saltreport = new Salt_Client_Reports__c(Name='Salt Report',Account__c= acc.id);
        insert saltreport;
        
        Id loginRecordTypeId=Schema.SObjectType.Tracking_Detail__c.getRecordTypeInfosByName().get('Login').getRecordTypeId();
        
        Tracking_Detail__c tDetail = new Tracking_Detail__c();
        tDetail.Login_Time__c = System.now();
        tDetail.Logged_In_User__c = user .Id;
        tDetail.RecordTypeId = loginRecordTypeId;
        tDetail.Account__c = acc.Id;
        insert tDetail; 
        
        SF_Community__c sfComm = new  SF_Community__c();
        sfComm.Community_Url__c='abc.com';
        sfComm.Name='url';
        insert sfComm;
                
        System.runAs(user) {
            SaltClientReportController.hasCreatePermission();
            SaltClientReportController.getUserId();
            SaltClientReportController.findAll();
            SaltClientReportController.getColumns();
            SaltClientReportController.getURL();
            SaltClientReportController.sortByCreatedDate();
            SaltClientReportController.getCurrentSortedByName();
            SaltClientReportController.saveRecord(saltreport.id);
            SaltClientReportController.getAvailableListviews();
        }        
        Test.stopTest();
    }
    
    static testmethod void SaltClientReportController2() {
        Test.startTest();
            
        Account acc = new Account(Name=' College Planning Services');
        insert acc;
        
        Contact con=new Contact();
        con.lastname='Doe';
        con.accountId=acc.id;
        con.FirstName = 'First Name';
        insert con;
        Profile p = [SELECT Id FROM Profile WHERE Name='Customer Community User']; 
            
      //  User userName = [Select id,Email,UserName,ContactId from User where Name='Kelly Matera'];
        User u = new User(Alias = 'standt', Email='standarduser@testasaorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Testingasas', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, contactId=con.id,
                            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testasaorg.com');
      
           
        Salt_Client_Reports__c saltreport = new Salt_Client_Reports__c(Name='Salt Report',Account__c= acc.id);
        insert saltreport;
                
        System.runAs(u) {
            SaltClientReportController.getUserId();
        }        
        Test.stopTest();
    }
    
    
    
}