force-app/main/default/objects/Salt_Client_Reports__c/Salt_Client_Reports__c.object-meta.xml
<CustomObject>
    <label>Salt Client Reports</label>
    <nameField>
        <label>Salt Client Reports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salt Client Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Salt_Client_Reports__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salt Client Reports</relationshipLabel>
    <relationshipName>Salt_Client_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SF_Community__c/SF_Community__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SF Community</label>
</CustomObject>

force-app/main/default/objects/Tracking_Detail__c/Tracking_Detail__c.object-meta.xml
<CustomObject>
    <label>Tracking Detail</label>
    <nameField>
        <displayFormat>TD-{0000}</displayFormat>
        <label>Tracking Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tracking_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tracking Details</relationshipLabel>
    <relationshipName>Tracking_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Clicked_By__c.field-meta.xml
<CustomField>
    <fullName>Clicked_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clicked By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tracking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Clicked_Time__c.field-meta.xml
<CustomField>
    <fullName>Clicked_Time__c</fullName>
    <label>Clicked Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Clicked_Url__c.field-meta.xml
<CustomField>
    <fullName>Clicked_Url__c</fullName>
    <label>Clicked Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Logged_In_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_In_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Logged In User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tracking_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/fields/Login_Time__c.field-meta.xml
<CustomField>
    <fullName>Login_Time__c</fullName>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tracking_Detail__c/recordTypes/Login.recordType-meta.xml
<RecordType>
    <fullName>Login</fullName>
    <active>true</active>
    <label>Login</label>
</RecordType>

force-app/main/default/classes/SaltClientReportController.cls
public with sharing class SaltClientReportController {
    static Id userId;
    static String sortedby;
    public static List<SALTColumnWrapper> colList=new List<SALTColumnWrapper>();
    public static SALTTableWrapper tableWrapper=new SALTTableWrapper();
    
    
    @AuraEnabled
    public static Boolean hasCreatePermission()
    {
        Boolean canCreate=false;
        canCreate=Schema.SObjectType.Salt_Client_Reports__c.isCreateAble();
        return canCreate;
    }
    @AuraEnabled
    public static SALTTableWrapper findAll() {
        sortedby='Sorted by Salt Client Report Names';
        System.Debug(userId);
        Id currentUser=[Select contactId from user where id=:userId].contactId;
        Id currentUserCommAcc=[Select accountId from contact where id=: currentUser].accountId;
        
        SALTColumnWrapper elem1=new SALTColumnWrapper();
        elem1.name='Name';
        elem1.label='Salt Client Report Name';
        elem1.sortDirection='ASC';
        
        SALTColumnWrapper elem2=new SALTColumnWrapper();
        elem2.name='CreatedDate';
        elem2.label='Created Date';
        elem2.sortDirection='ASC';
        
        colList.add(elem1);
        colList.add(elem2);
        
        tableWrapper.satCols=new List<SALTColumnWrapper>();        
        tableWrapper.satCols=colList;
         
        tableWrapper.clientRecords=new List<Salt_Client_Reports__c>();
        tableWrapper.clientRecords=[SELECT Id, Name, CreatedDate 
                FROM Salt_Client_Reports__c where Account__c=:currentUserCommAcc ORDER BY Name];
        /*
        List<Salt_Client_Reports__c> saltReports=[SELECT Id, Name, CreatedDate 
                FROM Salt_Client_Reports__c where Account__c=:currentUserCommAcc ORDER BY Name];
        */
        System.debug(tableWrapper);
        return tableWrapper;
    }
    
   /* @AuraEnabled
    public static List<SALTColumnWrapper> sort(String fieldName, String sortDirection)
    {
        if(fieldName=='Name')
        {
            
        }
        return null;
    }*/
    
    @AuraEnabled
    public static Id getUserId()
    {
        LoginHistory lastSuccessFullLogin=null;
        userId=UserInfo.getUserID();
        
        List<LoginHistory> lHistory=[Select 
                                            userId,LoginTime,status 
                                    From 
                                            LoginHistory 
                                    Where 
                                            userId= :UserInfo.getUserID()
                                    AND
                                            LoginUrl like'%customers/s/login'
                                    Order by  
                                            loginTime desc];
        //get the last successfull loging as status is not filterable in the query
        
        for(LoginHistory lTemp : lHistory)
        {
            if(lTemp.status.toLowerCase()=='success')
            {
                lastSuccessFullLogin=lTemp;
                break;
            }
        }
        
        Id loginRecordTypeId=Schema.SObjectType.Tracking_Detail__c.getRecordTypeInfosByName().get('Login').getRecordTypeId();
 
        List<Tracking_Detail__c> lastLogin=[Select 
                                                    Login_Time__c 
                                            from 
                                                    Tracking_Detail__c 
                                            where 
                                                    Logged_In_User__c =: userId 
                                            AND   
                                                    recordTypeId=:loginRecordTypeId
                                            order by 
                                                    createddate desc Limit 1];
        if((lastLogin!=null) && (lastLogin.size()>0) && (lastSuccessFullLogin != null))
        {
            if(lastLogin.get(0).Login_Time__c !=lastSuccessFullLogin.LoginTime)
            {
                Tracking_Detail__c newrecordDetails=new Tracking_Detail__c ();
                Id relatedContactId=[Select contactId from user where id=: userinfo.getUserId()].contactId;
                
                Contact relatedContact=[Select accountId from contact where id= : relatedContactId];
                if(relatedContact!=null)
                {
                    newrecordDetails.account__c=relatedContact.accountId;
                }
                newrecordDetails.Logged_In_User__c= userId;
                newrecordDetails.Login_Time__c = lastSuccessFullLogin.LoginTime;
                newrecordDetails.recordTypeId=loginRecordTypeId;
                insert newrecordDetails;
            }
        }
        else
        {
            Tracking_Detail__c newrecordDetails=new Tracking_Detail__c ();
            Id relatedContactId=[Select contactId from user where id=: userinfo.getUserId()].contactId;
            System.Debug(relatedContactId); 
            Contact relatedContact=[Select accountId from contact where id= : relatedContactId];
            System.Debug(relatedContact);
            if(relatedContact!=null)
            {
                newrecordDetails.account__c=relatedContact.accountId;
            }
            newrecordDetails.Logged_In_User__c= userId;
            if(lastSuccessFullLogin!=null)
                newrecordDetails.Login_Time__c = lastSuccessFullLogin.LoginTime;
            newrecordDetails.recordTypeId=loginRecordTypeId;
            insert newrecordDetails; 
        }
        //userId='00532000005Tozg';
        System.debug('logged in user is  '+userId);
        return userId;
    }

    @AuraEnabled
    public static List<SALTColumnWrapper> getColumns()
    {
        SALTColumnWrapper elem1=new SALTColumnWrapper();
        elem1.name='Name';
        elem1.label='Salt Client Report Name';
        elem1.sortDirection='ASC';
        
        SALTColumnWrapper elem2=new SALTColumnWrapper();
        elem2.name='CreatedDate';
        elem2.label='Created Date';
        elem2.sortDirection='ASC';
        
        colList.add(elem1);
        colList.add(elem2);
        return colList;
    }

    
    @AuraEnabled
    public static String getURL()
    {
        return SF_Community__c.getInstance('URL').Community_Url__c;
    }
    
    /*@AuraEnabled
    public static List<Salt_Client_Reports__c> sortByName(String columnName, String orderby) {
        System.debug(columnName +'----'+orderby);
        sortedby='Sorted by Salt Client Report Names';
        Id currentUser=[Select contactId from user where id=:userId].contactId;
        Id currentUserCommAcc=[Select accountId from contact where id=: currentUser].accountId;
        
        List<Salt_Client_Reports__c> saltReports=[SELECT Id, Name, CreatedDate 
                FROM Salt_Client_Reports__c where Account__c=:currentUserCommAcc ORDER BY Name];
        return saltReports;
    }*/
    
    @AuraEnabled
    public static List<Salt_Client_Reports__c> sortByCreatedDate() {
        sortedby='Sorted by Salt Client Report Names';
        Id currentUser=[Select contactId from user where id=:userId].contactId;
        Id currentUserCommAcc=[Select accountId from contact where id=: currentUser].accountId;
        
        List<Salt_Client_Reports__c> saltReports=[SELECT Id, Name, CreatedDate 
                FROM Salt_Client_Reports__c where Account__c=:currentUserCommAcc ORDER BY CreatedDate];
        return saltReports;
    }
    
    @AuraEnabled
    public static String getCurrentSortedByName()
    {
        return sortedby;
    }
    
    @AuraEnabled
    public static Tracking_Detail__c saveRecord (String curl) {
        Tracking_Detail__c newrecordDetails=new Tracking_Detail__c ();
        Id relatedContactId=[Select contactId from user where id=: userinfo.getUserId()].contactId;
        
        Contact relatedContact=[Select accountId from contact where id= : relatedContactId];
        if(relatedContact!=null)
        {
            newrecordDetails.account__c=relatedContact.accountId;
        }
        
        newrecordDetails.Clicked_By__c = userinfo.getUserId();
        newrecordDetails.Clicked_Time__c = DateTime.now();
        newrecordDetails.Clicked_Url__c = URL.getSalesforceBaseUrl().toExternalForm()+'/'+curl;   
        upsert newrecordDetails;
        return newrecordDetails;
    }
    @AuraEnabled
    public static String getAvailableListviews()
    {
        List<ListView> viewList=new List<ListView>();
        Set<id> listViewId=new Set<id>();
        try
        {
            ApexPages.StandardSetController sc=new ApexPages.StandardSetController(Database.getQueryLocator
                                                    ('Select id from Salt_client_reports__c Limit 1'));
            
            List<System.SelectOption> listViews = sc.getListViewOptions();
            for(System.SelectOption listView : listViews)
            {
                System.debug('List View Name : ' + listView.getValue());
                System.debug('List View Label : ' + listView.getLabel());
                listViewId.add(listView.getValue());
            }
            
            if(listViewId.size()>0)
            {
                viewList=[Select id, name from Listview where SobjectType= 'salt_client_reports__c' and Id in : listViewId];
            }
        }
        catch(Exception e)
        {
            System.debug(e.getMessage());
        }
        return JSON.serialize(viewList);
    }
   
    /*@AuraEnabled
    public static SALTTableWrapper findAllByFilter(Id filterId)
    {
        sortedby='Sorted by Salt Client Report Names';
        Id currentUser=[Select contactId from user where id=:userId].contactId;
        Id currentUserCommAcc=[Select accountId from contact where id=: currentUser].accountId;
        
        SALTColumnWrapper elem1=new SALTColumnWrapper();
        elem1.name='Name';
        elem1.label='Salt Client Report Name';
        elem1.sortDirection='ASC';
        
        SALTColumnWrapper elem2=new SALTColumnWrapper();
        elem2.name='CreatedDate';
        elem2.label='Created Date';
        elem2.sortDirection='ASC';
        
        colList.add(elem1);
        colList.add(elem2);
        
        tableWrapper.satCols=new List<SALTColumnWrapper>();        
        tableWrapper.satCols=colList;
         
        tableWrapper.clientRecords=new List<Salt_Client_Reports__c>();
        
        String query='SELECT Id, Name, CreatedDate FROM Salt_Client_Reports__c where Account__c ='+currentUserCommAcc +' ORDER BY Name';
                
        ApexPages.StandardSetController ssc=new ApexPages.StandardSetController(Database.getQueryLocator(query));          
        ssc.setFilterId(filterId);
        
        Set<id> rIds=new Set<id>();
        
        for(Sobject s : ssc.getRecords())
        {
            rIds.add(s.id);
        }
        
        if(rIds.size()>0)
        {
            tableWrapper.clientRecords=[SELECT Id, Name, CreatedDate 
                FROM Salt_Client_Reports__c where id in :rIds ORDER BY Name];
        }
       
        System.debug(tableWrapper);
        return tableWrapper;
    } */
}