force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/Mutually_Agreed_to_Objectives__c.object-meta.xml
<CustomObject>
    <description>M20</description>
    <label>Mutually Agreed to Objectives</label>
    <nameField>
        <label>Mutually Agreed to Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mutually Agreed to Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Expected_Contract_1_Recv_d_Closed__c.field-meta.xml
<CustomField>
    <fullName>Expected_Contract_1_Recv_d_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expected Contract 1 Recv&#39;d/Closed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Expected_Contract_2_Recv_d_Closed__c.field-meta.xml
<CustomField>
    <fullName>Expected_Contract_2_Recv_d_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expected Contract 2 Recv&#39;d/Closed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Expected_Contract_3_Recv_d_Closed__c.field-meta.xml
<CustomField>
    <fullName>Expected_Contract_3_Recv_d_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expected Contract 3 Recv&#39;d/Closed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Number_of_Contracts_Received__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Contracts_Received__c</fullName>
    <label>Number of Contracts Received</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Number_of_Expected_Contracts__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Expected_Contracts__c</fullName>
    <label>Number of Expected Contracts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/objective_plan_date__c.field-meta.xml
<CustomField>
    <fullName>objective_plan_date__c</fullName>
    <description>Please put in the Date of mutually agreed to objective plan</description>
    <label>Objective Plan Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Regional_Manager__c.field-meta.xml
<CustomField>
    <fullName>Regional_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mutually_Agreed_to_Objectives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/fields/Targeted_Substantive_Visits_for_Month__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Substantive_Visits_for_Month__c</fullName>
    <description>Please put in the target number of substantive visits</description>
    <label>Targeted Substantive Visits for Month</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mutually_Agreed_to_Objectives__c/recordTypes/M2O.recordType-meta.xml
<RecordType>
    <fullName>M2O</fullName>
    <active>true</active>
    <description>Mutually Agreed to Objectives</description>
    <label>M2O</label>
</RecordType>

force-app/main/default/classes/TestAutomateNoOfContractRcvd.cls
@isTest
public class TestAutomateNoOfContractRcvd {
        
     Static testMethod void AutomateNoOfContractRcvdTest(){
        Test.StartTest();
        Integer noOfChecked = -4; 
        User us = [select id from user where Profile.Name = 'System Administrator' and IsActive = True LIMIT 1];
        Mutually_Agreed_to_Objectives__c M2O = new Mutually_Agreed_to_Objectives__c();
        M2O.Number_of_Contracts_Received__c = null ;
        M2O.objective_plan_date__c = System.Today() ;
        M2O.Name = 'TestName' ;
        M2O.Regional_Manager__c = us.id ;
        M2O.Targeted_Substantive_Visits_for_Month__c = 1 ;
        M2O.Number_of_Expected_Contracts__c = 1;
        M2O.Expected_Contract_1_Recv_d_Closed__c = true ;
        M2O.Expected_Contract_2_Recv_d_Closed__c = true ;
        M2O.Expected_Contract_3_Recv_d_Closed__c = true ;
        insert M2O ;       
        
        M2O.Number_of_Contracts_Received__c = 4 ;
        M2O.Expected_Contract_1_Recv_d_Closed__c = false ;
        M2O.Expected_Contract_2_Recv_d_Closed__c = false ;
        M2O.Expected_Contract_3_Recv_d_Closed__c = false ;
        update M2O ;
        
        M2O.Number_of_Contracts_Received__c = null ;
        M2O.Expected_Contract_1_Recv_d_Closed__c = true ;
        M2O.Expected_Contract_2_Recv_d_Closed__c = true ;
        M2O.Expected_Contract_3_Recv_d_Closed__c = true ;
        update M2O ;        
        
        Test.StopTest();  
    }
}